VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts
https://tools.hmcts.net/jira/browse/VIH-7206
Change the bandwidth value for the self-test to the default (Default value is 1280).
```
[X ] Yes
[ ] No
```
=> VIH-7206 change default max bandwidth

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.html
https://tools.hmcts.net/jira/browse/VIH-7231
The enter consultation button for JOH should be disabled until the connection is established
```
[ X] Yes
[ ] No
```
=> VIH-7231 consultation btn for joh disable

VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs
https://tools.hmcts.net/jira/browse/VIH-7059
- Remove parallel execution workaround
```
[ ] Yes
[X] No
```
=> VIH-7059 Remove Parallel Execution Workaround

VideoWeb/VideoWeb.Services/BookingsApiClient.cs, VideoWeb/VideoWeb.Services/TestApiClient.cs, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/mock-video-call-service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/tests/judge-waiting-room.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.non-event.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/typings.d.ts
VIH-7154
* release media when switching devices rather than disconnecting from Pexip altogether
* release media when switching to audio only
```
[ ] Yes
[x] No
```
=> VIH-7154 improve audio only

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.scss
https://tools.hmcts.net/jira/browse/VIH-7118
The button consultation made disabled until the connection is established and fix the layout of the buttons for iPad portrait view.
```
[X ] Yes
[ ] No
```
=> VIH-7118 Buttons layout for wr judge

VideoWeb/VideoWeb.Contract/Responses/ConferenceForJudgeResponse.cs, VideoWeb/VideoWeb.UnitTests/Mappings/ConferenceForJudgeResponseMapperTests.cs, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-table.component.html, VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/JudgeHearingSummary.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing-base.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing-status-reader.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing-status-reader.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing-summary.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing-summary.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/judge-hearing-summary.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html, VideoWeb/VideoWeb/Mappings/ConferenceForJudgeResponseMapper.cs
VIH-7122
allow judges to enter a closed video hearing
```
[] Yes
[x] No
```
=> VIH-7122 allow judges to enter a closed video hearing

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature, VideoWeb/VideoWeb.AcceptanceTests/Pages/WaitingRoomPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
https://tools.hmcts.net/jira/browse/VIH-7004
-- Updated acceptance with Judge close hearing scenario
```
[ ] Yes
[x] No
```
=> VIH-7004 update judge close hearing scenario

VideoWeb/VideoWeb.AcceptanceTests/Features/Accessibility.feature, VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature, VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature, VideoWeb/VideoWeb.AcceptanceTests/Pages/VhoHearingListPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs
https://tools.hmcts.net/jira/browse/VIH-7122
-Added scenario judge enters closer hearing's waiting room
```
[ ] Yes
[x] No
```
=> VIH-7122 Added scenario judge enters closer hearing's waiting room

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html
https://tools.hmcts.net/jira/browse/VIH-7289
Hide IM window if Judge in consultation with VHO
```
[ X] Yes
[ ] No
```
=> VIH-7289 hide IM window for judge in VHO consultation

VideoWeb/VideoWeb/ClientApp/src/app/services/api/consultation.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/shared.module.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/toast/vh-toast.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/mock-events-service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/tests/individual-participant-status-list.component.consultation.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/invite-participant/invite-participant.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/invite-participant/invite-participant.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/invite-participant/invite-participant.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/join-private-consultation/join-private-consultation.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/notification-toastr.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base-setup.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/wr-participant-list-shared.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/wr-participant-list-shared.component.ts
=> VIH-6988 lint fixes

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-7018
- Updated acceptance library to latest
```
[ ] Yes
[x] No
```
=> VIH-7018 Updated acceptance library to fix ipad run

VideoWeb/VideoWeb.UnitTests/Mappings/RoomResponseMapperTest.cs
https://tools.hmcts.net/jira/browse/VIH-7291
Added unit tests for RoomResponseMapper.cs
```
[ ] Yes
[x] No
```
=> VIH-7291 - Added unit tests for RoomResponseMapper.cs

VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/mock-consultation-service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/invite-participant/invite-participant.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/invite-participant/invite-participant.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/notification-toastr.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base-setup.ts
https://tools.hmcts.net/jira/browse/VIH-7299
added more tests for private consultation room UI
```
[ ] Yes
[x] No
```
=> VIH-7299 private consultation room tests

VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/ConsultationHelper.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/InviteToConsultationTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/LeaveConsultationTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/LockConsultationRoomRequestTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/RequestConsultationTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/StartConsultationTest.cs, VideoWeb/VideoWeb/Controllers/ConsultationsController.cs
VIH-7299 
Additional controller tests
```
[ ] Yes
[X] No
```
=> VIH-7299 additional tests

VideoWeb/VideoWeb.AcceptanceTests/Pages/VhoHearingListPage.cs, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-table.component.html
VIH-7321
fix typo
```
[ ] Yes
[x] No
```
=> VIH-7321 fix typo

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.ts
VIH-7299
private consultation participant tests
```
[ ] Yes
[X] No
```
=> VIH-7299 private consultation participant tests

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.video-call-events.spec.ts
VIH-7299
added test for waiting room base
```
[ ] Yes
[X] No
```
=> VIH-7299 : added test for waiting room base

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
Reverting this change as it is no longer needed
```
[ ] Yes
[x] No
```
=> VIH-7195 Fixing spotlight removal upon muting camera REVERT

VideoWeb/VideoWeb/ClientApp/src/app/services/api/consultation.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/mock-consultation-service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/consultation-leave/consultation-leave.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/consultation-leave/consultation-leave.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/consultation-leave/consultation-leave.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/consultation-leave/consultation-leave.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.non-event.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-space.module.ts
VIH-6522
```
[ ] Yes
[x] No
```
=> VIH-6522 Leave modal

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VIH-7328
```
[ ] Yes
[x] No
```
=> VIH-7328 waiting room joinable bug

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/start-private-consultation/start-private-consultation.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/start-private-consultation/start-private-consultation.component.scss
https://tools.hmcts.net/jira/browse/VIH-7339
Scrolling for the invited popup in consultation
```
[ X] Yes
[ ] No
```
=> VIH-7339 scroll list of invited participants in consultation

VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/mock-consultation-service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/notification-sounds.service.spec.ts
https://tools.hmcts.net/jira/browse/VIH-7353
accordion details not expanded after has been hidden
```
[X ] Yes
[ ] No
```
=> VIH-7353 expand accordion details after hidden

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html
https://tools.hmcts.net/jira/browse/VIH-7356
Corrected tooltip texts
```
[ ] Yes
[x] No
```
=> VIH-7356 corrected private consultation room controls button tooltips

VideoWeb/VideoWeb.AcceptanceTests/Pages/HearingRoomPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Pages/JudgeWaitingRoomPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/JudgePrivateConsultationSteps.cs, VideoWeb/VideoWeb.Services/TestApiClient.cs
- update to JOH/Judge private consultation locators and test steps
```
[ ] Yes
[X] No
```
=> VIH-5552 Update to JOH Private Consultation locators and tests

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html
VIH-6905
Only show the "Share screen" button for certain roles
* Litigant in Person
* Representative
* Witness
* Judicial Office Holder
* Judge
```
[ ] Yes
[x] No
```
=> VIH-6905 Only show the "Share screen" button for certain roles

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/join-private-consultation/join-private-consultation.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/join-private-consultation/join-private-consultation.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/join-private-consultation/join-private-consultation.component.ts
https://tools.hmcts.net/jira/browse/VIH-7332
Fixed a bug where a user could join a locked private consultation room.
```
[ ] Yes
[x] No
```
=> VIH-7332 fixed locked room joining bug

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/notification-toastr.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/notification-toastr.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
https://tools.hmcts.net/jira/browse/VIH-7354
Fix alert for poor network connection
```
[ ] Yes
[ ] No
```
=> VIH-7354 alert for network poor consultation

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-global-styles.scss
VIH-7105
set width on the secondary video feed
```
[ ] Yes
[x] No
```
=> VIH-7105 set width on the secondary video feed

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.html
https://tools.hmcts.net/jira/browse/VIH-7358
Added close hearing dialog back to hearing controls
```
[ ] Yes
[x] No
```
=> VIH-7358 added close hearing dialog back to hearing controls

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html
https://tools.hmcts.net/jira/browse/VIH-7371
updated copy for locked private consultation rooms
```
[ ] Yes
[x] No
```
=> VIH-7371 updated copy for locked rooms

VideoWeb/VideoWeb/ClientApp/src/app/services/user-media.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base-setup.ts
VIH-6905
Show the "share screen" button for anyone who isn't an observer
```
[ ] Yes
[x] No
```
=> VIH-6905 - Show the "share screen" button for anyone who isn't a witness

VideoWeb/VideoWeb/ClientApp/src/app/home/home.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/home/home.component.ts, azure-pipelines.nightly.yml
https://tools.hmcts.net/jira/browse/VIH-7073
- revert allow of tablets
```
[ ] Yes
[x] No
```
=> VIH-7073 Revert-Enable_tablets_for_iOS_and_Android_for_all_participant_types

VideoWeb/VideoWeb.AcceptanceTests/Api/PollForParticipantStatus.cs, VideoWeb/VideoWeb.AcceptanceTests/Features/PrivateConsultation.feature, VideoWeb/VideoWeb.AcceptanceTests/Features/PrivateConsultations.feature, VideoWeb/VideoWeb.AcceptanceTests/Pages/JudgeWaitingRoomPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Pages/PrivateCallPopupPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Pages/PrivateConsultationRoomPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Pages/WaitingRoomPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/JudgePrivateConsultationSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/PrivateConsultationSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/ProgressionSteps.cs
https://tools.hmcts.net/jira/browse/VIH-6988
https://tools.hmcts.net/jira/browse/VIH-6521
https://tools.hmcts.net/jira/browse/VIH-6522
https://tools.hmcts.net/jira/browse/VIH-6989
- batch of acceptance tests around private consultations
```
[ ] Yes
[X] No
```
=> VIH-6988 acceptance tests for starting and joining private consultations

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/wr-participant-list-shared.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/wr-participant-list-shared.component.ts
https://tools.hmcts.net/jira/browse/VIH-7378
non-JOH user could not invite to JOH consultation room
```
[ X] Yes
[ ] No
```
=> VIH-7378 non JOH user could not invite in JOH consultation

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/join-private-consultation/join-private-consultation.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/join-private-consultation/join-private-consultation.component.ts
https://tools.hmcts.net/jira/browse/VIH-7377
Removed JOH rooms from joinable room list
```
[ ] Yes
[X] No
```
=> VIH-7377 removed JOH rooms from joinable room list

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-global-styles.scss
VIH-7352 
Changed header to be more responsive
```
[ ] Yes
[X No
```
=> VIH-7352 to use grid for header bar

VideoWeb/VideoWeb.Common/Caching/CivilianRoomCacheMapper.cs, VideoWeb/VideoWeb.Common/Caching/ConferenceCacheMapper.cs, VideoWeb/VideoWeb.Common/Models/CivilianRoom.cs, VideoWeb/VideoWeb.Common/Models/Conference.cs, VideoWeb/VideoWeb.UnitTests/Controllers/VideoEventController/SendHearingEventTests.cs, VideoWeb/VideoWeb/Controllers/VideoEventsController.cs
VIH-7167
Map civilian rooms to conference cache model
```
[ ] Yes
[x] No
```
=> VIH-7167 Map civilian rooms to conference cache model

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html
https://tools.hmcts.net/jira/browse/VIH-7265
Added text explaining why start button is disabled to judge waiting room
```
[ ] Yes
[X] No
```
=> VIH-7265 added text explaining why start button is disabled to judge waiting room

VideoWeb/VideoWeb.Contract/Responses/ParticipantContactDetailsResponseVho.cs, VideoWeb/VideoWeb.Contract/Responses/ParticipantResponse.cs, VideoWeb/VideoWeb.Services/TestApiClient.cs, VideoWeb/VideoWeb.Services/VideoApiClient.cs, VideoWeb/VideoWeb.UnitTests/Builders/ParticipantSummaryResponseBuilder.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForVHOfficerTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ParticipantController/GetParticipantsByConferenceIdTest.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ParticipantController/GetParticipantsWithContactDetailsByConferenceIdAsync.cs, VideoWeb/VideoWeb.UnitTests/Mappings/ConferenceCacheMapperTests.cs, VideoWeb/VideoWeb.UnitTests/Mappings/LinkedParticipantResponseMapperTests.cs, VideoWeb/VideoWeb.UnitTests/Mappings/ParticipantForUserResponseMapperTests.cs, VideoWeb/VideoWeb.UnitTests/Mappings/ParticipantStatusResponseForVhoMapperTests.cs, VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts, VideoWeb/VideoWeb/Controllers/ParticipantsController.cs, VideoWeb/VideoWeb/Mappings/ParticipantForUserResponseMapper.cs, VideoWeb/VideoWeb/Mappings/ParticipantStatusResponseForVhoMapper.cs
VIH-6559
Update models for judge and VHO participant list to include the links between other participants
```
[ ] Yes
[x] No
```
=> VIH-6559 Update models for judge and VHO participant lists to show links

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/start-private-consultation/start-private-consultation.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/start-private-consultation/start-private-consultation.component.ts
https://tools.hmcts.net/jira/browse/VIH-7390
updated JOH consultation room display names
```
[ ] Yes
[X] No
```
=> VIH-7390 updated JOH consultation room display names

VideoWeb/VideoWeb/ClientApp/src/scripts/pexrtc.js
VIH-6959
upgrade pexip client Upgrade to Pexip 24.3
```
[ ] Yes
[x] No
```
=> VIH-6959 upgrade pexip client

VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature, VideoWeb/VideoWeb.AcceptanceTests/Pages/HearingRoomPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Pages/PrivateCallPopupPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/VideoHearingsOfficerCallSteps.cs
- update to locators and scripts for VHO calls
```
[ ] Yes
[X] No
```
=> VIH-5552 Update to VHO call test scripts

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingAlerts.feature
- Update to hearing alert test
```
[ ] Yes
[X] No
```
=> VIH-5552 Update to hearing alerts test

VideoWeb/VideoWeb.Contract/Responses/RoomResponse.cs, VideoWeb/VideoWeb.Services.Generator/video-api.nswag, VideoWeb/VideoWeb.Services/VideoApiClient.cs, VideoWeb/VideoWeb.UnitTests/Mappings/RoomResponseMapperTest.cs, VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/mappers/participant-panel-model-mapper.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant-event.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/video-call-test-data.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-context-menu/judge-context-menu.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/linked-participant-panel-model.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/panel-model-base.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/participant-panel-model.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/participant-panel.model.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/video-call-models.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/video-endpoint-panel-model.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/video-endpoint-panel.model.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts, VideoWeb/VideoWeb/ClientApp/src/typings.d.ts, VideoWeb/VideoWeb/Mappings/RoomResponseMapper.cs
VIH-7190
* Display linked participants together in the judge panel list
```
[ ] Yes
[x] No
```
=> VIH-7190 display linked participants together in judge panel list

VideoWeb/VideoWeb.AcceptanceTests/Helpers/GetChatMessages.cs, VideoWeb/VideoWeb.AcceptanceTests/Pages/InstantMessagerPage.cs
- update to locators of IM messages
```
[ ] Yes
[X] No
```
=> VIH-5552 Update to IM locators

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/admin-im-list/admin-im-list.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/admin-im-list/admin-im-list.component.ts
https://tools.hmcts.net/jira/browse/VIH-7133
Judge now shows as unavailable to VHO when in private consultation.
```
[ ] Yes
[x] No
```
=> VIH-7133 updated judge status for VHO

VideoWeb/VideoWeb/ClientApp/src/app/security/login/login.component.html, VideoWeb/VideoWeb/ClientApp/src/app/security/logout/logout.component.html, VideoWeb/VideoWeb/ClientApp/src/app/security/unauthorised/unauthorised.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/back-navigation/back-navigation.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/beta-banner/beta-banner.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/chat-body-window/chat-body-window.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/chat-input-box/chat-input-box.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/chat/chat-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/chat/chat-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/chat-panel/chat-panel.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/chat-window-base.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-7316
Translation for security folder and some of shared
```
[X] Yes
[ ] No
```
=> VIH-7316 extract security shared for translation

VideoWeb/VideoWeb.Services/VideoApiClient.cs, VideoWeb/VideoWeb/ClientApp/src/app/shared/pipes/multiline.pipe.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/pipes/multiline.pipe.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/shared.module.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-context-menu/judge-context-menu.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/linked-participant-panel-model.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/linked-participant-panel-model.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/panel-model-base.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/participant-panel-model.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/video-endpoint-panel-model.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/video-endpoint-panel.model.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts, VideoWeb/VideoWeb/Controllers/VideoEventsController.cs
VIH-7185
* replace usages of properties in the panel member with methods
* split linked participants into multiple lines for judge participant panel during a hearing
* remote mute VMR
```
[ ] Yes
[x] No
```
=> VIH-7185 update models so participants in VMR are updated

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/notification-toastr.service.ts
https://tools.hmcts.net/jira/browse/VIH-7406
changed VHO to Video hearings officer in incoming call alert
```
[ ] Yes
[x] No
```
=> VIH-7406 Video hearings officer in incoming call alert

VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs, VideoWeb/VideoWeb.EventHub/Hub/IEventHubClient.cs, VideoWeb/VideoWeb.UnitTests/Hub/EventHubBaseTests.cs, VideoWeb/VideoWeb.UnitTests/Hub/UpdateParticipantHandStatusTests.cs, VideoWeb/VideoWeb.UnitTests/Hub/UpdateParticipantRemoteMuteStatusTests.cs, VideoWeb/VideoWeb/ClientApp/src/app/services/events.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/mock-events-service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
VIH-7201 
Participants in a VMR do not receive callbacks like other participants, nor can they raise their hand like other participants. The `EventHubClient` is extended to provide this to room participants
```
[ ] Yes
[x] No
```
=> VIH-7201 update eventhub clients to publish mute and hand raised for vmr

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
- update to the latest acceptance test package
```
[ ] Yes
[X] No
```
=> VIH-5552 Upgrade to latest acceptance test version

VideoWeb/VideoWeb/ClientApp/src/app/services/events.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant-hand-raised-message.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant-remote-mute-message.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/mock-events-service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
VIH-7201
* Publish remote mute status so that room participants know when they have been muted
* Raise and lower hands for all participants in a room when any participant in the room raises or lowers their hand
* Judges can lower hands of rooms
```
[ ] Yes
[x] No
```
=> VIH-7201 capture and publish hand raise messages

VideoWeb/VideoWeb.sln, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
VIH-7315
* Add missing translation
* Fix path to docker-compose.dcproj
```
[ ] Yes
[x] No
```
=> VIH-7315 extract on the day components for translation

VideoWeb/VideoWeb.AcceptanceTests/Steps/VideoHearingsOfficerCallSteps.cs
- update to VHO call tests
```
[ ] Yes
[X] No
```
=> VIH-5552 Update to VHO call tests

VideoWeb/VideoWeb.AcceptanceTests/Features/Accessibility.feature, VideoWeb/VideoWeb.AcceptanceTests/Steps/PrivateConsultationSteps.cs
- added accessibility tests for private consultation rooms
```
[ ] Yes
[X] No
```
=> VIH-5552 Adding accessibility tests for private consultation rooms

VideoWeb/VideoWeb/appsettings.json
VIH-7167
Update the config value for eventhub path to not contain a VIH ticket number
```
[ ] Yes
[x] No
```
=> VIH-7167 update eventhub config path for prod slot

VideoWeb/VideoWeb.AcceptanceTests/Pages/PrivateConsultationRoomPage.cs
- update to a private consultation locator
```
[ ] Yes
[X] No
```
=> VIH-5552 Update to PC locator

VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/linked-participant-panel-model.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/linked-participant-panel-model.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VIH-7192 
* Interpreters linked to a witness share the same journey as their witness
```
[ ] Yes
[x] No
```
=> VIH-7192 interpreter for witness handled like the witness

VideoWeb/VideoWeb.UnitTests/Middleware/CheckParticipantCanAccessConferenceAttributeTests/CheckParticipantCanAccessConferenceAttributeTest.cs, VideoWeb/VideoWeb.UnitTests/Middleware/CheckParticipantCanAccessConferenceAttributeTests/when_action_has_conferenceId.cs, VideoWeb/VideoWeb.UnitTests/Middleware/CheckParticipantCanAccessConferenceAttributeTests/when_action_has_neither_participantId_or_conferenceId.cs, VideoWeb/VideoWeb.UnitTests/Middleware/CheckParticipantCanAccessConferenceAttributeTests/when_action_has_participantId.cs, VideoWeb/VideoWeb.UnitTests/Middleware/CheckParticipantCanAccessConferenceAttributeTests/when_action_has_participantId_and_conferenceId.cs, VideoWeb/VideoWeb.UnitTests/Middleware/CheckParticipantCanAccessConferenceAttributeTests/when_user_has_VhOfficerRole.cs, VideoWeb/VideoWeb/Controllers/ConferencesController.cs, VideoWeb/VideoWeb/Controllers/InstantMessagesController.cs, VideoWeb/VideoWeb/Controllers/ParticipantsController.cs, VideoWeb/VideoWeb/Extensions/ConfigureServicesExtensions.cs, VideoWeb/VideoWeb/Middleware/CheckParticipantCanAccessConferenceAttribute.cs, VideoWeb/VideoWeb/Startup.cs
VIH-7085
attributes
```
[ ] Yes
[X] No
```
=> VIH-7085 attributes

VideoWeb/VideoWeb.AcceptanceTests/Data/Test.cs, VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature, VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
- added hearing closed time to test data to use on link
```
[ ] Yes
[X] No
```
=> VIH-5552 Added hearing closed time to test data

VideoWeb/VideoWeb.AcceptanceTests/Features/ParticipantStatus.feature, VideoWeb/VideoWeb.AcceptanceTests/Steps/ParticipantStatusSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/ProgressionSteps.cs
Update to participant status BDD scenarios and step definitions
```
[ ] Yes
[X] No
```
=> VIH-5552 Update to participant status BDD scenarios

VideoWeb/VideoWeb.AcceptanceTests/Features/Login.feature, VideoWeb/VideoWeb.AcceptanceTests/Steps/BrowserSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/LoginSteps.cs
- Update to Login BDD scenarios and step definitions
```
[ ] Yes
[X] No
```
=> VIH-5552 Update to Login BDD Scenarios

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/WRTestComponent.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.non-event.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VIH-7434
mute video stream until the countdown is complete
```
[ ] Yes
[x] No
```
=> VIH-7434 mute video stream until countdown is complete

VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.EventHub/VideoWeb.EventHub.csproj, VideoWeb/VideoWeb.IntegrationTests/packages.lock.json, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/CallWitnessTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/ConferenceManagementControllerTestBase.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/DismissWitnessTests.cs, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/Controllers/ConferenceManagementController.cs, VideoWeb/VideoWeb/packages.lock.json
VIH-7194
update Call and Dismiss witness to support rooms
```
[ ] Yes
[x] No
```
=> VIH-7194 update Call and Dismiss witness to support rooms

VideoWeb/VideoWeb/ClientApp/src/app/shared/accessibility/accessibility.component.html, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-7446
Translations for Accessibility page
```
[ ] Yes
[x ] No
```
=> VIH-7446 Accessibility translations

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.ts
included observers and witnesses in judge private consultation participants list
https://tools.hmcts.net/jira/browse/VIH-7418
```
[ ] Yes
[X] No
```
=> VIH-7418 include observers and witnesses in judge consultation participants

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature, VideoWeb/VideoWeb.AcceptanceTests/Features/WaitingRoom.feature, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
- Workaround fix for retry logic
```
[ ] Yes
[X] No
```
=> VIH-5552 Workaround fix for retry logic

VideoWeb/VideoWeb/ClientApp/src/app/shared/mappers/participant-panel-model-mapper.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/mappers/participant-panel-model-mapper.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts
VIH-7194 
fix judge in hearing participant panel list to separate multiple linked participants
```
[ ] Yes
[x] No
```
=> VIH-7194  fix judge in hearing panel list

VideoWeb/VideoWeb.UnitTests/Controllers/VirtualRoomController/GetInterpreterRoomForParticipantTests.cs, VideoWeb/VideoWeb.UnitTests/Mappings/SharedParticipantRoomMapperTests.cs, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html, VideoWeb/VideoWeb/Controllers/VirtualRoomsController.cs, VideoWeb/VideoWeb/Mappings/SharedParticipantRoomMapper.cs
VIH-7166
Update tile prefix for room participants
```
[ ] Yes
[x] No
```
=> VIH-7166 create vmr with correct tile prefix

VideoWeb/VideoWeb.UnitTests/Controllers/VideoEventController/SendHearingEventTests.cs, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json, VideoWeb/VideoWeb/Controllers/VideoEventsController.cs
VIH-7421
events controller map and change type before sending to api
```
[ ] Yes
[X] No
```
=> VIH-7421 - events controller map and change type before sending to api

VideoWeb/VideoWeb/ClientApp/src/app/shared/toast/room-closing/room-closing-toast.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/start-private-consultation/start-private-consultation.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/start-private-consultation/start-private-consultation.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
VIH-7421
set room to null if disconnected and endpoint on room transfer
```
[ ] Yes
[X] No
```
=> VIH-7421 Room transfer fix

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature, VideoWeb/VideoWeb.AcceptanceTests/Helpers/Users.cs, VideoWeb/VideoWeb.AcceptanceTests/Journeys/ParticipantJourney.cs, VideoWeb/VideoWeb.AcceptanceTests/Pages/HearingRoomPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/ProgressionSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
https://tools.hmcts.net/jira/browse/VIH-7190
https://tools.hmcts.net/jira/browse/VIH-6899
- Updated interpreter hearing room scenario
```
[ ] Yes
[x] No
```
=> VIH-7190 Updated Interpreter hearing room scenario

VideoWeb/VideoWeb.AcceptanceTests/Features/Errors.feature, VideoWeb/VideoWeb.AcceptanceTests/Features/HearingStatus.feature, VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature
- fix to a missing step definition
```
[ ] Yes
[X] No
```
=> VIH-5552 Fix to missing step definition

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html
VIH-7427
removed duplicate alert icon
```
[ ] Yes
[x] No
```
=> VIH-7427 - removed duplicate alert icon

VideoWeb/VideoWeb/ClientApp/src/app/services/api/consultation.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/api/consultation.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/mock-consultation-service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/start-private-consultation/start-private-consultation.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/start-private-consultation/start-private-consultation.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
VIH-7421
refactor and fix room names
```
[ ] Yes
[X] No
```
=> VIH-7421 refactor and fix room names

VideoWeb/VideoWeb/ClientApp/src/app/app.module.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.html, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
VIH-7314
added missing date translations
```
[ ] Yes
[x] No
```
=> VIH-7314 - added missing date translations

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.eventhub.events.spec.ts
https://tools.hmcts.net/jira/browse/VIH-7453
move witness on hearing start
```
[ ] Yes
[X] No
```
=> VIH-7453 move witness on hearing start

VideoWeb/VideoWeb.AcceptanceTests/Features/Accessibility.feature, VideoWeb/VideoWeb.AcceptanceTests/Steps/BrowserSteps.cs
- added an accessibility test for new account type selection page
```
[ ] Yes
[X] No
```
=> VIH-5552 Add Axe test for new account type selection

VideoWeb/VideoWeb.EventHub/Handlers/EndpointTransferEventHandler.cs, VideoWeb/VideoWeb.EventHub/Handlers/TransferEventHandler.cs
https://tools.hmcts.net/jira/browse/VIH-7499
- update to participant status (in consultation)
```
[ ] Yes
[x] No
```
=> VIH-7499 VideoWeb Callback event (In Consultation) failure issue

VideoWeb/VideoWeb.EventHub/Handlers/Core/EventHandlerBase.cs, VideoWeb/VideoWeb/Controllers/VideoEventsController.cs
VIH-7167 
* switch to for loops since handlers are not thread-safe
```
[ ] Yes
[x] No
```
=> VIH-7167 switch to for loops when processing events for linked participants

VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.EventHub/VideoWeb.EventHub.csproj, VideoWeb/VideoWeb.IntegrationTests/packages.lock.json, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/CallWitnessTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/DismissWitnessTests.cs, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/linked-participant-panel-model.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts, VideoWeb/VideoWeb/Controllers/ConferenceManagementController.cs, VideoWeb/VideoWeb/packages.lock.json
VIH-7194
revert to using participant id when transferring linked participants into and out of a hearing
```
[ ] Yes
[x] No
```
=> VIH-7194 revert to using participant id for transfers

VideoWeb/VideoWeb.UnitTests/Services/ConsultationNotifierTests.cs, VideoWeb/VideoWeb/Helpers/ConsultationNotifier.cs, VideoWeb/VideoWeb/appsettings.Development.json
VIH-7505 
only clear responses for participants in a room
```
[ ] Yes
[x] No
```
=> VIH-7505 fix private consultations for non-linked participants

VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
Removed space at end of 'consultation-room-will-close-at'
```
[ ] Yes
[X] No
```
=> VIH-5552 Remove space from consultation-room-will-close-at

VideoWeb/VideoWeb.AcceptanceTests/Pages/PrivateConsultationRoomPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Pages/RulesPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
- update to some locators
```
[ ] Yes
[X] No
```
=> VIH-5552 Update test locators

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature, VideoWeb/VideoWeb.AcceptanceTests/Pages/HearingRoomPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
https://tools.hmcts.net/jira/browse/VIH-7201
- Updated interpreter scenario and refactored participant list assessment
```
[ ] Yes
[x] No
```
=> VIH-7201 update interpreter scenario

VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VIH-7508
only update hand raise status for linked participants via SignalR
```
[ ] Yes
[x] No
```
=> VIH-7508 linked participant hand raised status updating by two sources

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
VIH-7517
Allow participant to change their camera or device mid-hearing and consultation without triggering a disconnect event
```
[ ] Yes
[x] No
```
=> VIH-7517 change camera or mic device during a hearing

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-hearing-list/vho-hearing-list.component.html, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-hearing-list/vho-hearing-list.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-hearing-list/vho-hearing-list.component.ts
https://tools.hmcts.net/jira/browse/VIH-7467
Fix for IM icon
```
[ X] Yes
[ ] No
```
=> VIH-7467 fix IM icon behaviour on refresh

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, VideoWeb/VideoWeb.UnitTests/Middleware/CheckParticipantCanAccessConferenceAttributeTests/CheckParticipantCanAccessConferenceAttributeTest.cs, VideoWeb/VideoWeb.UnitTests/Middleware/CheckParticipantCanAccessConferenceAttributeTests/when_action_has_conferenceId.cs, VideoWeb/VideoWeb.UnitTests/Middleware/CheckParticipantCanAccessConferenceAttributeTests/when_action_has_neither_participantId_or_conferenceId.cs, VideoWeb/VideoWeb.UnitTests/Middleware/CheckParticipantCanAccessConferenceAttributeTests/when_action_has_participantId.cs, VideoWeb/VideoWeb.UnitTests/Middleware/CheckParticipantCanAccessConferenceAttributeTests/when_action_has_participantId_and_conferenceId.cs, VideoWeb/VideoWeb.UnitTests/Middleware/CheckParticipantCanAccessConferenceAttributeTests/when_user_has_VhOfficerRole.cs
- Fixed unit test warnings
```
[ ] Yes
[X] No
```
=> VIH-5552 Fixed unit test warnings

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
VIH-7314
fix typo
```
[ ] Yes
[X] No
```
=> VIH-7314 fix typo

VideoWeb/VideoWeb/Controllers/ConsultationsController.cs
https://tools.hmcts.net/jira/browse/VIH-7526
Judge cannot enter JOH consultation room
```
[ ] Yes
[ x] No
```
=> VIH-7526 Check for username case sensitivity

VideoWeb/VideoWeb.Common/Models/Participant.cs, VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs, VideoWeb/VideoWeb.UnitTests/Hub/EventHubBaseTests.cs, VideoWeb/VideoWeb.UnitTests/Hub/TransferRequestTests.cs, VideoWeb/VideoWeb.UnitTests/Hub/UpdateParticipantHandStatusTests.cs, VideoWeb/VideoWeb.UnitTests/Hub/UpdateParticipantRemoteMuteStatusTests.cs
VIH-7183
VIH-7435
* raise/lower hands for all johs collectively
* remote mute all johs collectively
```
[ ] Yes
[x] No
```
=> VIH-7183 hand and remote mute for JOHs in a room

VideoWeb/VideoWeb/ClientApp/src/app/services/events.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/events.service.ts
VIH-7314
event hub auth to use access token and subscribe
```
[ ] Yes
[x] No
```
=> VIH-7314 - event hub auth to use access token and subscribe

VideoWeb/VideoWeb/ClientApp/package-lock.json, VideoWeb/VideoWeb/ClientApp/package.json, VideoWeb/VideoWeb/ClientApp/src/app/shared/mappers/participant-panel-model-mapper.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/mappers/participant-panel-model-mapper.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/linked-participant-panel-model.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/linked-participant-panel-model.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/appsettings.Development.json
VIH-7435
link JOHs in judge hearing controls list like interpreters
```
[ ] Yes
[x] No
```
=> VIH-7435 link johs in judge hearing controls list

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/tests/individual-participant-status-list.component.consultation.spec.ts
VIH-7537
* check linked participant availability
* add a test
```
[ ] Yes
[x] No
```
=> VIH-7537 check for linked participant availability

VideoWeb/VideoWeb.AcceptanceTests/Hooks/DriverHooks.cs, VideoWeb/VideoWeb.AcceptanceTests/Pages/LogoutPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Pages/Page.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/LoginSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/appsettings.json, VideoWeb/VideoWeb/ClientApp/src/app/security/oidc-config-setup.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/shared-routing.module.ts
VIH-7553
- Fixed sign out redirect issue
- Fixed tests for new behaviour on sign out
```
[ ] Yes
[X] No
```
=> VIH-7553 Fixed sign out redirect issue

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-7568
- added missing translations for case types
```
[ ] Yes
[X] No
```
=> VIH-7568 Adding missing case types to English translations

VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature, VideoWeb/VideoWeb.AcceptanceTests/Pages/AdminPanelPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/JudgePrivateConsultationSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/VideoHearingsOfficerCallSteps.cs
https://tools.hmcts.net/jira/browse/VIH-7413
- Added VHO interpreter private consultation scenario
```
[ ] Yes
[x] No
```
=> VIH-7413 vho interpreter private consultation

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature, VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature, VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature, VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/ProgressionSteps.cs
https://tools.hmcts.net/jira/browse/VIH-7413
- Refactored datasetup
```
[ ] Yes
[x] No
```
=> VIH-7413 Refactored DataSetup

VideoWeb/VideoWeb.UnitTests/Mappings/SharedParticipantRoomMapperTests.cs, VideoWeb/VideoWeb/Mappings/SharedParticipantRoomMapper.cs
https://tools.hmcts.net/jira/browse/VIH-7514
Kinly integration: update display name for shared room (participants)
before: W2010410188123;Witness Interpreter Doe;09dd41bc-9f2f-488a-ba97-16e6caf77969
after: WITNESS;Witness Interpreter Doe;09dd41bc-9f2f-488a-ba97-16e6caf77969
```
[x] Yes
[ ] No
```
=> VIH-7514 Shared Room: Display name updated

VideoWeb/VideoWeb.AcceptanceTests/Configuration/VideoWebConfig.cs, VideoWeb/VideoWeb.AcceptanceTests/Hooks/ConfigHooks.cs, VideoWeb/VideoWeb.AcceptanceTests/Pages/AccountTypeSelectionPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/LoginSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/appsettings.json, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, azure-pipelines.beta.yml, azure-pipelines.nightly.yml, azure-pipelines.release.yml, azure-pipelines.wowza-check.yml, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-7529
- Allow tests to run with eJud Test Users
- Added a config setting to turn this on and off if eJud is unavailable
```
[ ] Yes
[X] No
```
=> VIH-7529 Use Ejud Users for tests

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/tests/individual-participant-status-list.component.consultation.spec.ts
VIH-7567
* remove fdescribe accidentally left in
```
[ ] Yes
[x] No
```
=> VIH-7567 chore: remove fdescribe

VideoWeb/VideoWeb/ClientApp/src/app/security/auth.guard.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/idp-selection/idp-selection.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/login/login.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/mock-oidc-security.service.ts
VIH-7553
```
[ ] Yes
[x ] No
```
=> VIH-7553 Video web login logout config issue

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/linked-participant-panel-model.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.non-event.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.video-call-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VIH-7577 
* 🐛  Only show call witness icon for linked participants that have a witness
* 🐛  Remove translate icon for panel members 
* 🐛  auto-enable a participant's camera when upgrading to a full video call
```
[ ] Yes
[x] No
```
=> VIH-7577 switch camera on from audio only mid hearing

VideoWeb/VideoWeb/ClientApp/package-lock.json, VideoWeb/VideoWeb/ClientApp/src/app/app-routing.module.ts, VideoWeb/VideoWeb/ClientApp/src/app/app.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/home/home.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/home/home.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/idp-selection/ejud-sign-in.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/idp-selection/ejud-sign-in.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/idp-selection/idp-selection.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/idp-selection/vh-sign-in.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/idp-selection/vh-sign-in.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/login/login.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/login/login.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/security-routing.module.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/security.module.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/page-url.constants.ts
VIH-7391
```
[ ] Yes
[ x ] No
```
=> VIH-7391 Redirect eJud and Vh aad users when new url used 

VideoWeb/VideoWeb.AcceptanceTests/Features/PrivateConsultations.feature, VideoWeb/VideoWeb.AcceptanceTests/Pages/PrivateCallPopupPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/PrivateConsultationSteps.cs
… the interpreter
```
[ ] Yes
[ ] No
```
=> VIH-7415 - Add a scenario where the interpreter declines a private consultation invitation request from a representative.

VideoWeb/VideoWeb/ClientApp/src/app/app.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/app.component.ts
VIH-7631
* remove the redirect to IDP selection on logout & not authenticated
* remove associated test
> the UI authentication pieces should be re-written to use angular modules/routes/guards appropriately - AppComponent should not be handling the redirection/authentication - this should exist in a separate authentication component whose children are protected by a guard
```
[ ] Yes
[x] No
```
=> VIH-7631 remove redirect

VideoWeb/VideoWeb/ClientApp/src/app/app.module.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/logging/loggers/app-insights-logger.service.ts, azure-pipelines.yml
TBC
add isVho to custom dimensions to help filter logging
```
[ ] Yes
[x] No
```
=> VIH-4072 update logging details

VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature
```
[ ] Yes
[ ] No
```
Removing the user 'interpreter' from this test as this has been rewritten as a separate test based on VIH-7413
=> VIH-7413 removing-Interpreter-from-test-as-it-has-already-been-rewritten

VideoWeb/VideoWeb.AcceptanceTests/Hooks/ConfigHooks.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/LoginSteps.cs, VideoWeb/VideoWeb/ClientApp/src/app/security/auth.guard.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/auth.guard.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/logout/logout.component.ts
https://tools.hmcts.net/jira/browse/VIH-7702
* Hide IDP selection page on login to Video Web
* Setting the EJud flag to False in Acceptance Test and make EJud does not run through  the Acceptance Tests
```
[ ] Yes
[X] No
```
=> VIH-7702 Implementation for masking EJud for Release 1.26

VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
https://tools.hmcts.net/jira/browse/VIH-7720
Added a wait time for the element using the Selenium driver's approach.
```
[ ] Yes
[x] No
```
=> VIH-7720 Wait time added to allow time for the interpreter display element

VideoWeb/VideoWeb/ClientApp/src/app/app.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/app.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/events-hub.service.ts
VIH-7732
* Stop treating successful renewal of refresh tokens as a first time login
```
[ ] Yes
[x] No
```
=> VIH-7732 handle refresh tokens better

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature, VideoWeb/VideoWeb.AcceptanceTests/Pages/PanelMemberHearingListPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs
https://tools.hmcts.net/jira/browse/VIH-7729
Panel Member now has it's own class of selectors
```
[ ] Yes
[x] No
```
=> VIH-7729 alternative fix for panel member scripts unable to locate case number element

VideoWeb/VideoWeb.AcceptanceTests/Steps/LoginSteps.cs
https://tools.hmcts.net/jira/browse/VIH-7733
Added the line of code that will select the account to sign out of.
```
[ ] Yes
[x] No
```
=> VIH-7638 Fix for login scripts that fail on sign out

VideoWeb/VideoWeb/ClientApp/src/app/home/home.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/home/home.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/events-hub.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/events-hub.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/logging/loggers/app-insights-logger.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/session-storage.ts
VIH-7732
* improve token refresh stability
* differentiate between first-time login and token refreshes
* remove cookie usage from app insights logging
* better null checks with session storage to avoid unnecessary errors in the app
```
[ ] Yes
[x] No
```
=> VIH-7732 improve token refresh stability

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/linked-participant-panel-model.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/panel-model-base.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
VIH-7731
Do not rely on Pexip buzz time when the participant is in a VMR
```
[ ] Yes
[x] No
```
=> VIH-7731 hand icon lowered for VMR participant incorrectly

azure-pipelines.beta.yml, azure-pipelines.nightly.yml, azure-pipelines.release.yml, azure-pipelines.wowza-check.yml, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-7660
```
[ ] Yes
[X] No
```
=> VIH-7660 changed PAT

VideoWeb/VideoWeb.AcceptanceTests/Data/Test.cs, VideoWeb/VideoWeb.AcceptanceTests/Features/Accessibility.feature, VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature, VideoWeb/VideoWeb.AcceptanceTests/Features/WaitingRoom.feature, VideoWeb/VideoWeb.AcceptanceTests/Hooks/HealthcheckHooks.cs, VideoWeb/VideoWeb.AcceptanceTests/Journeys/JudgeJourney.cs, VideoWeb/VideoWeb.AcceptanceTests/Journeys/JudgeSelfTestJourney.cs, VideoWeb/VideoWeb.AcceptanceTests/Journeys/PanelMemberOrWingerJourney.cs, VideoWeb/VideoWeb.AcceptanceTests/Pages/Page.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/JudgeHearingListSteps .cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/ProgressionSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.Contract/VideoWeb.Contract.csproj, VideoWeb/VideoWeb.EventHub/VideoWeb.EventHub.csproj, VideoWeb/VideoWeb.IntegrationTests/VideoWeb.IntegrationTests.csproj, VideoWeb/VideoWeb.IntegrationTests/packages.lock.json, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-7783
Revised code to support the new Judge Hearing list pages and related changes for Accessibility.
```
[ ] Yes
[ ] No
```
=> VIH-7783 - Judge Hearing List Accessibility

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-7793
Additional change to Video Web to use the updated version of acceptance-tests
```
[ ] Yes
[ ] No
```
=> VIH-7793 - Updated dependency versions

VideoWeb/VideoWeb.AcceptanceTests/Features/Filters.feature
Will not remove as there could be changes later,
VIH-7889
```
[ ] Yes
[ ] No
```
=> VIH-7889 - Disable test as it currently does not work.

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/tests/judge-waiting-room.component.spec.ts
https://tools.hmcts.net/jira/browse/VIH-7866
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> VIH-7866 removed logic to add total audio recording time when in consultation room

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VIH-7894
Cleanup presentationStream when the conference status is changed
```
[ ] Yes
[x] No
```
=> VIH-7894 Cleanup presentationStream when the conference status is changed

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VIH-7894 
cleanup presentation stream before transfer from WR to conference
```
[ ] Yes
[x] No
```
=> VIH-7894 Fix panel member don't stop screen share when resume or start hearing

azure-pipelines.release.yml
https://tools.hmcts.net/jira/browse/VIH-6831
Added new parameter to be passed to release pipeline which contains the prod urls
```
[ ] Yes
[X] No
```
=> VIH-6831 Automate_Vanity_urls

VideoWeb/VideoWeb/ClientApp/src/app/shared/unsupported-browser/unsupported-browser.component.ts
https://tools.hmcts.net/jira/browse/VIH-7913
Remove IE from unsupported browsers
```
[ ] Yes
[x] No
```
=> VIH-7913 remove-IE-from-unsupported-browsers-page

VideoWeb/VideoWeb/ClientApp/src/app/shared/unsupported-browser/unsupported-browser.component.html, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-7977
Update wording for Unsupported browsers page
```
[ ] Yes
[X] No
```
=> VIH-7977 Update content-wording on unsupported page

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json
VIH-7981
Adding Welsh tranlation for "hearing-role.litigation-friend"
```
[ ] Yes
[x] No
```
=> VIH-7981 Adding welsh for litigation friend

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8056
- added translation for grc - ej case type 
```
[ ] Yes
[x] No
```
=> VIH-8056 added translation for new case type

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json
VIH-8032
Add Welsh Translation for label in IM input box
```
[ ] Yes
[x] No
```
=> VIH-8032 Add Welsh Translation for label in IM input box

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8031
```
[ ] Yes
[ x] No
```
=> VIH-8031 - Type correction of claimant and removed unused property.

VideoWeb/VideoWeb.AcceptanceTests/Features/LastMinuteBooking.feature, VideoWeb/VideoWeb.AcceptanceTests/Pages/HearingRoomPage.cs
https://tools.hmcts.net/jira/browse/VIH-8055
corrected feature file name so that it can be found in the Test Explorer window
```
[ ] Yes
[x] No
```
=> VIH-8055 corrected feature file name

VideoWeb/VideoWeb/ClientApp/src/app/app.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/header/header.component.html
https://tools.hmcts.net/jira/browse/VIH-8063
- nested headers was causing the accessibility tests to fail
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> VIH-8063 removed nested header, promoted aria header role to parent header

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/select-hearing-layout/select-hearing-layout.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/select-hearing-layout/select-hearing-layout.component.ts
VIH-8077
Properly unsubscribe subscriptions
```
[ ] Yes
[x] No
```
=> VIH-8077 Properly unsubscribe subscriptions

VideoWeb/VideoWeb/ClientApp/src/app/shared/unsupported-browser/unsupported-browser.component.html, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8014
- Removed unused translation.
- Updated required wording.
```
[ ] Yes
[x] No
```
=> VIH-8014 Update wording for unsupported browsers page

VideoWeb/VideoWeb/ClientApp/src/app/services/conference/conference.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/conference.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/participant.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/participant.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/video-control-cache.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/video-control-cache.service.ts
https://tools.hmcts.net/jira/browse/VIH-8083
- CORS errors not fixed.
- Fixed errors from participant, conference and video control cache services where the conference was undefined due to navigating away from a conference specific page.
```
[ ] Yes
[x] No
```
=> VIH-8083 Fixed console errors on judge navigation back to hearing list

VideoWeb/VideoWeb/ClientApp/src/app/services/device-type.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/device-type.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/browser.constants.ts, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-8141
- added samsung as supported browser
```
[ ] Yes
[x] No
```
=> VIH-8141 added constants for browser names, added samsung as supported browser

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/quick-links/quick-links.component.ts
VIH-8152
Handling error if a non guid is passed in url
```
[ ] Yes
[x] No
```
=> VIH-8152 Handling error if a non guid is passed in url

VideoWeb/VideoWeb/ClientApp/package-lock.json, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/quick-links/quick-links.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/quick-links/quick-links.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/error.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/error.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.html
VIH-8158
Storing translation key for error message and translating in the component rather than at the time of the error
```
[ ] Yes
[x] No
```
=> VIH-8158 error translation

VideoWeb/VideoWeb/ClientApp/src/app/shared/mic-visualiser/mic-visualiser.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/mic-visualiser/mic-visualiser.component.ts
VIH-8100
Moving fill style setting back to fillMeter function.
```
[ ] Yes
[x] No
```
=> VIH-8100 mic visualizer color

VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant-contact-details.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant-contact-details.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-status/participant-status.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/wr-participant-list-shared.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/wr-participant-list-shared.component.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json, VideoWeb/VideoWeb/Controllers/ConferencesController.cs, VideoWeb/VideoWeb/Controllers/QuickLinksController.cs
VIH-7904
Fixing errors in waiting room and command center to display quick link users status
```
[ ] Yes
[x] No
```
=> VIH-7904 display quick links users on waiting room command center

VideoWeb/VideoWeb/ClientApp/src/app/services/media-stream.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/media-stream.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.ts
VIH-8041
* switch between original and filtered streams
```
[ ] Yes
[x] No
```
=> VIH-8041 switch between original and filtered streams

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/switch-on-camera-microphone/switch-on-camera-microphone.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/switch-on-camera-microphone/switch-on-camera-microphone.component.ts
VIH-8183
Redirecting to service error when error occurs
```
[ ] Yes
[x] No
```
=> VIH-8183  Camera and Microphone are in use/blocked error not displayed

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
Update of nuget packages for AC Tests
```
[ ] Yes
[ ] No
```
=> VIH-8151 - update of nuget packages for AC Tests

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/on-the-day-routing.module.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/participant-status.guard.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/participant-status.guard.ts
https://tools.hmcts.net/jira/browse/VIH-8193
Added Equipment check url to Participant AuthGuard: Unauthorized redirection if user is not authenticated
```
[ ] Yes
[x] No
```
=> VIH-8193 unauthorized equipment-check url redirection

VideoWeb/VideoWeb/ClientApp/src/app/security/security-config-setup.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/api/quick-links.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.spec.ts
VIH-8208
Setting provider if quick link
```
[ ] Yes
[x] No
```
=> VIH-8208 Quick link user logged out on refresh 

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
Change script to assert Judge status as "Available" instead of "Disconnected", after the hearing has been closed.
```
[ ] Yes
[x] No
```
=> VIH-8151 Change VHO monitors hearing script Judge status assertion

VideoWeb/VideoWeb/ClientApp/src/app/services/unload-detector.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/unload-detector.service.ts
[VIH-8236](https://tools.hmcts.net/jira/browse/VIH-8236)
- Added page hide event as on some versions of iOS the visibility change may not be raised under some conditions i.e. refreshing the page.
```
[ ] Yes
[x] No
```
=> VIH-8236 PM disconnection causes duplication

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-global-styles.scss, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8111
=> VIH-8112 responsive control post rebase

VideoWeb/VideoWeb.AcceptanceTests/Pages/HearingRoomPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Pages/JudgeParticipantPanel.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
=> VIH-8151 status fix for panel members

VideoWeb/VideoWeb/ClientApp/src/app/shared/custom-validators.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json
https://tools.hmcts.net/jira/browse/VIH-8181
- added missing special cases for validation
- added welsh translation
**Does this PR introduce a breaking change?** 
```
[ ] Yes
[x] No
```
=> VIH-8181 updated cases to include missing characters for validation and added welsh translation

VideoWeb/VideoWeb.AcceptanceTests/Pages/HearingRoomPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Pages/JudgeParticipantPanel.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
Correctly identifying elements
```
[ ] Yes
[ ] No
```
=> VIH-8151 wingers hearing-script fix

VideoWeb/VideoWeb.EventHub/Handlers/LeaveEventHandler.cs, VideoWeb/VideoWeb.UnitTests/EventHandlers/LeaveEventHandlerTests.cs
[VIH-8261](https://tools.hmcts.net/jira/browse/VIH-8261)
- Only handle the leave callback if the participant is in the correct state.
```
[ ] Yes
[x] No
```
=> VIH-8261 Disconnect issue with hearing 

VideoWeb/VideoWeb.AcceptanceTests/Pages/HearingRoomPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/JudgePrivateConsultationSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
element id change
```
[ ] Yes
[ ] No
```
=> VIH-8151 Judge pauses and closes hearing script fix

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-context-menu/judge-context-menu.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-context-menu/judge-context-menu.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-context-menu/judge-context-menu.component.ts
VIH-8235
Adding translation to case type group/party for judge context menu. Also changing the way ids for elements are set.
```
[ ] Yes
[x] No
```
=> VIH-8235 translate party in judge context menu

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/switch-on-camera-microphone/switch-on-camera-microphone.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/switch-on-camera-microphone/switch-on-camera-microphone.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/user-media.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/user-media.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts
[VIH-8263](https://tools.hmcts.net/jira/browse/VIH-8263)
- Stopped initialising cameras when the user media service is constructed.
- Initialise user media service in switch on component and video call service.
```
[ ] Yes
[x] No
```
=> VIH-8263 camera and microphone permission requested too early

VideoWeb/VideoWeb/Controllers/InternalEventController.cs, VideoWeb/VideoWeb/Controllers/QuickLinksController.cs
https://tools.hmcts.net/jira/browse/VIH-8252
Amended the missing step of updating the Conference Cache with updated participants.
```
[ ] Yes
[X] No
```
=> VIH-8252 Bridge Updating the Conference Cache with updated participants

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json
https://tools.hmcts.net/jira/browse/VIH-8253
Add Welsh translation for admit/dismiss participant 
```
[ ] Yes
[x] No
```
=> VIH-8253 Add Welsh translation for admin/dismiss 

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/self-view/self-view.component.scss
https://tools.hmcts.net/jira/browse/VIH-8170
=> VIH-8170 Reduced self view size

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json
VIH-8255
Adding Welsh translation
```
[ ] Yes
[x] No
```
Change in the UI
=> VIH-8255 Adding translation for judge table

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/copy-id/copy-id.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/copy-id/copy-id.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/copy-quick-link/copy-quick-link.component.html, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/copy-quick-link/copy-quick-link.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/copy-telephone-id/copy-telephone-id.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/copy-telephone-id/copy-telephone-id.component.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8176
- added welsh translation for copy links
```
[ ] Yes
[x] No
```
=> VIH-8176 added welsh translation for copy links component

VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.scss
https://tools.hmcts.net/jira/browse/VIH-8279
=> VIH-8279 Fixed microphone width and self test misalignment

VideoWeb/VideoWeb/ClientApp/src/app/services/conference/conference.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/conference.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/kinly-heartbeat.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/kinly-heartbeat.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts
[VIH-8294](https://tools.hmcts.net/jira/browse/VIH-8294)
- Will not initialise heartbeat until current conference and current participant have been received.
- Initialising current conference in conference service from the active route.
```
[ ] Yes
[x] No
```
=> VIH-8249 heartbeat issues

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/context-menu-header/context-menu-header.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/context-menu-header/context-menu-header.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/context-menu-header/context-menu-header.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/context-menu-header/context-menu-header.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-space.module.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json, VideoWeb/VideoWeb/ClientApp/src/styles.scss
https://tools.hmcts.net/jira/browse/VIH-8306
https://tools.hmcts.net/jira/browse/VIH-8307
- added missing header for context menu
- added logic to switch header between consultation and hearing
- added welsh translation
```
[ ] Yes
[x] No
```
consultation-controls-english
consultation-controls-welsh
hearing-controls-english
hearing-controls-welsh
=> VIH-8306 VIH-8307 missing context menu header

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-table.component.scss
https://tools.hmcts.net/jira/browse/VIH-8320
=> VIH-8320 Hide horizontal scroll bar when not required

VideoWeb/VideoWeb/ClientApp/src/app/services/device-type.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/device-type.service.ts
VIH-8332
Update Supported browsers page to remove Chrome on iPad/iPhone
```
[ ] Yes
[x] No
```
=> VIH-8332 Update Supported browsers page to remove Chrome on iPad/iPhone

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts
https://tools.hmcts.net/jira/browse/VIH-8267
Added Role(Observer) control logic to avoid sharing their screen
```
[ ] Yes
[X] No
```
=> VIH-8267 Observer role cannot share screen

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.scss
https://tools.hmcts.net/jira/browse/VIH-8334
Hearing control UI alignment on mobile responsive version
```
[ ] Yes
[x] No
```
=> VIH-8334 Mobile hearing controls:UI alignment (#1647)

VideoWeb/VideoWeb/ClientApp/src/app/services/conference/participant.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/participant.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/video-control.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.spec.ts
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/VIH-8298
Change description
Participants-panel component to set pexip properties on updated list of participant
```
[ ] Yes
[X] No
```
=> VIH-8298 Fix for release 1.28

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts
[VIH-8358](https://tools.hmcts.net/jira/browse/VIH-8358)
- Reworked handle connect method
```
[ ] Yes
[x] No
```
=> VIH-8358 Incoming stream being lost when stream is modified

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.html, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8121
- welsh translation to staffmember
```
[ ] Yes
[x] No
```
=> VIH-8121 Added welsh transaltions

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
Simple change to versions 
```
[ ] Yes
[ ] No
```
=> VIH-8323 Acceptance tests version update

VideoWeb/VideoWeb.AcceptanceTests/Features/StaffMember.feature, VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs
https://tools.hmcts.net/jira/browse/VIH-8266
Changes made for the creation of Staff Member scripts had caused some previous smoke tests to fail. This fix is to correct that.
```
[ ] Yes
[ ] No
```
=> VIH-8266 - fix for broken smoke test bindings

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json
https://tools.hmcts.net/jira/browse/VIH-8411
- added missing translation for leave hearing
```
[ ] Yes
[x] No
```
=> VIH-8411 Added missing translations

VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts
[VIH-8452](https://tools.hmcts.net/jira/browse/VIH-8452)
[VIH-8445](https://tools.hmcts.net/jira/browse/VIH-8445)
- Disabled h264 encoding on iOS devices
```
[ ] Yes
[x] No
```
=> VIH-8452 disable h264 for iOS users (#1696)

VideoWeb/VideoWeb/ClientApp/src/app/services/user-media.service.ts
VIH-8464
Change default value to true
```
[ ] Yes
[x] No
```
=> VIH-8464 Participant Camera Turned Off by default

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.ts
VIH-8500
Leave button displayed with Dual Host Toggled Off
```
[ ] Yes
[x] No
```
=> VIH-8502 Leave button displayed with Dual Host Toggled Off

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8030
Update of acceptance test project dependencies
```
[ ] Yes
[ ] No
```
=> VIH-8030 update to latest acceptance test proj

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-hearings/hearing-list-table.component.html, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8521
- aria labels for the hearing table
```
[ ] Yes
[x] No
```
aria label in welsh:
aria label in english:
=> VIH-8521 added aria labels for hearing tables with welsh translation

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.non-event.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
https://tools.hmcts.net/jira/browse/VIH-8536
Added a logic to switch the flag used to display the transfer participant page, this will affect quick link participants, witness and interpreters for witness.
**Does this PR introduce a breaking change?** 
```
[ ] Yes
[x] No
```
=> VIH-8536 - fix for participants being stuck in call transfer page

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, VideoWeb/VideoWeb.Common/SignalR/AdUserProfileService.cs, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.Contract/VideoWeb.Contract.csproj, VideoWeb/VideoWeb.EventHub/VideoWeb.EventHub.csproj, VideoWeb/VideoWeb.IntegrationTests/VideoWeb.IntegrationTests.csproj, VideoWeb/VideoWeb.IntegrationTests/packages.lock.json, VideoWeb/VideoWeb.UnitTests/Hub/AdUserProfileServiceTests.cs, VideoWeb/VideoWeb.UnitTests/Hub/CachedProfileServiceTests.cs, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json
VIH-8524
Calling User API for quick link participants to find the user
```
[ ] Yes
[x] No
```
=> VIH-8524 Calling User API for quick link participants to find the user

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/independent-self-test/independent-self-test.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/independent-self-test/independent-self-test.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-self-test/judge-self-test.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-self-test/judge-self-test.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/models/base-self-test.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-self-test/participant-self-test.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-self-test/participant-self-test.component.ts
VIH-8533 
Staff Member navigation errors
```
[ ] Yes
[x] No
```
=> VIH-8533 Staff Member navigation errors

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts, VideoWeb/VideoWeb/ClientApp/src/typings.d.ts, VideoWeb/VideoWeb/Controllers/VideoEventsController.cs, VideoWeb/VideoWeb/Extensions/TelemetryClientExtensions.cs
[VIH-8560](https://tools.hmcts.net/jira/browse/VIH-8560)
- Enabled PexRTC to log to AI.
- Logging kinly callback and related generated events as events in AI
```
[ ] Yes
[x] No
```
=> VIH-8560 enhance logging

VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/StartVideoHearingTests.cs, VideoWeb/VideoWeb/Controllers/ConferenceManagementController.cs
https://tools.hmcts.net/jira/browse/VIH-8472
=> VIH-8472 Remote lock is turned off by default when starting a hearing

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/self-view/self-view.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
[VIH-8575](https://tools.hmcts.net/jira/browse/VIH-8575)
- Added a flag for join / leave consultation to ensure video mutes before video element is hidden.
- Added a condition that will mute video unless in consultation and flag is false.
```
[ ] Yes
[x] No
```
=> VIH-8575 participants unable to hear each other in consultation with button work around

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-shared/participant-status-base/participant-status-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-shared/tests/participant-status-base.component.spec.ts
https://tools.hmcts.net/jira/browse/VIH-8535
=> VIH-8535 Fixed issue with host status not updating correctly in vho view

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.Contract/Responses/ConferenceForVHOfficerResponse.cs, VideoWeb/VideoWeb.Contract/VideoWeb.Contract.csproj, VideoWeb/VideoWeb.EventHub/VideoWeb.EventHub.csproj, VideoWeb/VideoWeb.IntegrationTests/VideoWeb.IntegrationTests.csproj, VideoWeb/VideoWeb.IntegrationTests/packages.lock.json, VideoWeb/VideoWeb.UnitTests/Controllers/ParticipantController/StaffMemberJoinConferenceTests.cs, VideoWeb/VideoWeb.UnitTests/Mappings/ConferenceForVhOfficerResponseMapperTests.cs, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing-summary.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/copy-telephone-id/copy-telephone-id.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/copy-telephone-id/copy-telephone-id.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-hearing-list/vho-hearing-list.component.html, VideoWeb/VideoWeb/ClientApp/src/scripts/pexrtc.js, VideoWeb/VideoWeb/Mappings/ConferenceForVhOfficerResponseMapper.cs, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8435
=> VIH-8435 Welsh number copied along with English

VideoWeb/VideoWeb/ClientApp/src/scripts/pexrtc.js
https://tools.hmcts.net/jira/browse/VIH-8561
=> VIH-8561 Updated pexrtc.js file

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts
https://tools.hmcts.net/jira/browse/VIH-8592
Removed console log errors 
```
[ ] Yes
[x ] No
```
=> VIH-8952 - fixed console log errors

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participant-status/private-consultation-participant-status.component.scss
https://tools.hmcts.net/jira/browse/VIH-8583
Calling and Declined font colour are now Yellow and Red in the Consultation.
```
[ ] Yes
[x ] No
```
=> VIH-8583 calling and declined font colour change

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8505
```
[ ] Yes
[ x] No
```
=> VIH-8505 Added english and Welsh translations to Upper Tribunal Tax case type.

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.ts
VIH-8600
Excluding interpreter as a separate row in consultation room participants panel.
```
[ ] Yes
[x] No
```
=> VIH-8600 Exclude interpreter from consultation

VideoWeb/VideoWeb.AcceptanceTests/appsettings.json, VideoWeb/VideoWeb.Common/Configuration/QuickLinksConfiguration.cs, VideoWeb/VideoWeb.IntegrationTests/appsettings.json, VideoWeb/VideoWeb.UnitTests/AuthenticationSchemes/QuickLinksSchemeTests.cs, VideoWeb/VideoWeb/AuthenticationSchemes/QuickLinksScheme.cs, VideoWeb/VideoWeb/Extensions/ConfigureAuthSchemeExtensions.cs, azure-pipelines.beta.yml, azure-pipelines.nightly.yml, azure-pipelines.release.yml, azure-pipelines.yml
VIH-8630
Changing to use RSA public key. Changes required to library variable groups. Video api also needs to be updated for matching private key
```
[x] Yes
[ ] No
```
=> VIH-8630 Updating to use RSA public key

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/participant-item/participant-item.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/participant-item/participant-item.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participant-display-name/private-consultation-participant-display-name.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participant-display-name/private-consultation-participant-display-name.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participant-display-name/private-consultation-participant-display-name.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participant-display-name/private-consultation-participant-display-name.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-space.module.ts, VideoWeb/VideoWeb/ClientApp/src/sass/_components.scss, VideoWeb/VideoWeb/ClientApp/src/sass/components/_colors.scss
https://tools.hmcts.net/jira/browse/VIH-8603
Fixed endpoint display name not showing on participant panel during consultation. Also, added a new component to display this information and updated the participant-item and private-consultation-participants components   
```
[ ] Yes
[x] No
```
=> VIH-8603 Endpoint display name not displayed on participant panel

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
Usual update to dependencies.
```
[ ] Yes
[ ] No
```
=> VIH-8692 - Dependancy update

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8656
VIH-8656 hearing Role Translations - Appellant for SSCS
```
[ ] Yes
[X] No
```
=> VIH-8656 Translations for Appellant for SSCS

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8701
- added translations
```
[ ] Yes
[x] No
```
=> VIH-8701 Added translations

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8665
- Added translations
```
[ ] Yes
[x] No
```
=> VIH-8665 Added translations

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8646
- Added translations
```
[ ] Yes
[x] No
```
=> VIH-8646 Added translations

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/select-hearing-layout/hearing-layout.component.html
VIH-8738
VIH-8723
VIH-8724
VIH-8725
Changing ambiguous alts to null
```
[ ] Yes
[x] No
```
=> VIH-8738 Changing ambiguous alts to null

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8652
Welsh Translations added
```
[ ] Yes
[x ] No
```
=> VIH-8652 Added Welsh translations for new Mental Health Case type and roles

VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/ConsultationHelper.cs, VideoWeb/VideoWeb.UnitTests/Controllers/EndpointController/GetEndpointsLinkedToUserTests.cs, VideoWeb/VideoWeb/Controllers/EndpointsController.cs
https://tools.hmcts.net/jira/browse/VIH-8741
=> VIH-8741 staff member now receives available endpoints

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/VIH-8703
```
[ ] Yes
[x ] No
```
=> VIH-8703 Added translation for new case type for english and welsh

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8703
```
[ ] Yes
[x ] No
```
=> VIH-7903 added translation for case type group.

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.ts
https://tools.hmcts.net/jira/browse/VIH-8754
=> VIH-8754 Fix unable to call multiple endpoints into consultation

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8703
```
[ ] Yes
[ x] No
```
=> VIH-8703 - Fixed transalation for secretary of state

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/wr-participant-list-shared.component.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8650
- Updated participant-list-shared component and fixed typo in translation files 
```
[ ] Yes
[x ] No
```
=> VIH-8650 - Fixed 'Mackenzie friend' hearing role text not showing on participant panel list

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.ts
https://tools.hmcts.net/jira/browse/VIH-8765
=> VIH-8765 Fixed staff member being able to change another SM's display name

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
https://tools.hmcts.net/jira/browse/VIH-8720
Created  a new function called 'updateLocalAudioMutedForWitnessInterpreterVmr'. This will be called before a linked participant is transferred into a hearing. It will set each linked participant's 'localAudioMuted' flag to true in the 'participantRemoteMuteStoreService' and update the linked participant accordingly.
```
[ ] Yes
[x ] No
```
=> VIH-8720 - Fix for witness interpreter vmr incorrect mic status

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.html
https://tools.hmcts.net/jira/browse/VIH-8725
=> VIH-8725 - Changed joh crests to have empty alt tags

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8733
- Added English and Welsh translations for new case types
```
[ ] Yes
[x] No
```
=> VIH-8733 - Added English and Welsh translations for new case types

VideoWeb/VideoWeb/AuthenticationSchemes/AadSchemeBase.cs, VideoWeb/VideoWeb/Startup.cs
https://tools.hmcts.net/jira/browse/VIH-8774
VIH-8774 - We need to expose PII key to find out more information in app insights. Also in Startup Authentication should come before Authorization in the middleware pipeline.
```
[ ] Yes
[x] No
```
=> VIH-8774 - Signature Validation failed and Audience Validation failed errors persist in prod

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8752
https://tools.hmcts.net/jira/browse/VIH-8752
```
[ ] Yes
[X] No
```
=> VIH-8752 Adding translations to Case Type Asylum Support

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
Fixed Interventer to Interventor
=> VIH-8747 EAP translations Interventer to Interventor change 

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
VIH-7956
```
[ ] Yes
[ ] No
```
=> VIH-7956 update to latest dependency versions

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.html
https://tools.hmcts.net/jira/browse/VIH-8828
=> VIH-8828 Added translation to individual participant status list case role types.

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8805
Adds english and welsh translations for the new war pensions appeals case type
```
[ ] Yes
[x] No
```
=> VIH-8805 Add translations for war pensions appeals

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8753
```
[ ] Yes
[x ] No
```
=> VIH-8753 New Casetype for Criminal Injuries Compensation

VideoWeb/VideoWeb/ClientApp/src/app/security/authentication/quick-link-security.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/authentication/quick-link-security.service.ts
- VIH-8859
- unsubsribed from subject and re setting config when clearing token
```
[ ] Yes
[x] No
```
=> VIH-8859 re setting security config when clearing token

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
- [VIH-8803](https://tools.hmcts.net/jira/browse/VIH-8803)
- added new case type for lands chamber case
```
[ ] Yes
[x] No
```
=> VIH-8803 added new translation for new case type

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts
https://tools.hmcts.net/jira/browse/VIH-8855
- updated config for turn server config
```
[ ] Yes
[x] No
```
=> VIH-8855 update turn server config

VideoWeb/VideoWeb/ClientApp/src/app/services/user-media.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/user-media.service.ts
https://tools.hmcts.net/jira/browse/VIH-8880
=> VIH-8880 Navigate to error page if device is in use

VideoWeb/VideoWeb/ClientApp/src/scripts/pexrtc.js
[VIH-8917](https://tools.hmcts.net/jira/browse/VIH-8917)
```
[ x] Yes
[ ] No
```
=> VIH-8917 Updated pexrtc.js to Pexip 27.3

VideoWeb/VideoWeb/ClientApp/src/scripts/pexrtc.js
[VIH-8917](https://tools.hmcts.net/jira/browse/VIH-8917)
```
[ ] Yes
[x] No
```
=> VIH-8917 Added version comment to pexrtc

VideoWeb/VideoWeb/ClientApp/src/scripts/pexrtc.js
VIH-8915
- reformatting pexrtc.js file
```
[ ] Yes
[x] No
```
=> VIH-8915 reformatting pexrtc.js file

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json
https://tools.hmcts.net/jira/browse/VIH-8921
Update the translation file JIRA Ref VH-8921.
```
[ ] Yes
[x ] No
```
=> VIH-8921 Updated  cy.json To Correct Translation 

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.html
https://tools.hmcts.net/jira/browse/VIH-7848
=> VIH-7848 Added IM accessibility

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/feedback-banner/feedback-banner.component.html
https://tools.hmcts.net/jira/browse/VIH-8981
Survey link update
=> VIH-8981 - survey link update

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.ts
https://tools.hmcts.net/jira/browse/VIH-9039
Fix for SM and Witness displaying in private consultations.
```
[ ] Yes
[ x] No
```
=> VIH-9039 Fix to remove witnesses and staff members from private consultation

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html
https://tools.hmcts.net/jira/browse/VIH-9035
removed keyup event from button element
=> VIH-9035 - removed keyup event from button element

VideoWeb/VideoWeb/ClientApp/src/app/security/idp-selection/idp-selection.component.html, VideoWeb/VideoWeb/ClientApp/src/app/security/idp-selection/idp-selection.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/idp-selection/idp-selection.component.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-9036
=> VIH-9036 Wording changes to idp-selection page.

VideoWeb/VideoWeb/ClientApp/src/app/services/media-stream.service.ts
https://tools.hmcts.net/jira/browse/VIH-9055
Added extra logging to capture MediaStream tracks when a new stream is initialised
```
[ ] Yes
[x] No
```
=> VIH-9055 Added extra logging to capture MediaStream tracks when a new stream is initialised

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json
https://tools.hmcts.net/jira/browse/VIH-9122
Fixed translation text
```
[ ] Yes
[x] No
```
=> VIH-9122 Fixed translation text

VideoWeb/VideoWeb/ClientApp/src/app/app.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/security-config-setup.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/security-config-setup.service.ts
https://tools.hmcts.net/jira/browse/VIH-9072
=> VIH-9072 Sign in pages redirect to unauthorised

VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.html
https://tools.hmcts.net/jira/browse/VIH-9010
- Added missing contact details to the service error page
```
[ ] Yes
[x] No
```
=> VIH-9010 Added missing contact details to the service-error page

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/start-private-consultation/start-private-consultation.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/start-private-consultation/start-private-consultation.component.ts
https://tools.hmcts.net/jira/browse/VIH-9056
Updated condition that checks linked participants status, updated it to bring it inline with check to regular participant type.
```
[ ] Yes
[X] No
```
=> VIH-9056 Fix for linked participants not being able to be invited into private consultations

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/participant-item/participant-item.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/participant-item/participant-item.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/participant-item/participant-item.component.ts
https://tools.hmcts.net/jira/browse/VIH-8606
- Prevent an interpretee from being called into a private consultation when the interpreter is not available
- Display the interpreter's availability status in the participant list
```
[ ] Yes
[x] No
```
=> VIH-8606 Participant with unavailable interpreter shows as available for consultation

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.Contract/VideoWeb.Contract.csproj, VideoWeb/VideoWeb.EventHub/VideoWeb.EventHub.csproj, VideoWeb/VideoWeb.IntegrationTests/VideoWeb.IntegrationTests.csproj, VideoWeb/VideoWeb.IntegrationTests/packages.lock.json, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-9147
Added ui element that exposes the current internet connection status to the user; this shows if a user attempts to reconnect but it fails. This is to allow the user to know why, rather than them keep clicking reconnect and not know what's happening. Screenshots attached to jira ticket
```
[ ] Yes
[X] No
```
=> VIH-9147 Added UI element to error.component.html that displays current connection status

VideoWeb/VideoWeb/ClientApp/src/app/shared/constants/div-ids.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/modal/modal-trap-focus.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/consultation-leave/consultation-leave.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/consultation-leave/consultation-leave.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/consultation-leave/consultation-leave.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
https://tools.hmcts.net/jira/browse/VIH-8946
Added trap focus and focus on the leave button in the modal window
=> VIH-8946 - modal window focus

VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.spec.ts, VideoWeb/VideoWeb/VideoWeb.csproj
https://tools.hmcts.net/jira/browse/VIH-9160
```
[ ] Yes
[X] No
```
=> VIH-9160 Switched self view default to true

VideoWeb/VideoWeb.Common/Caching/DistributedJOHConsultationRoomLockCache.cs, VideoWeb/VideoWeb.Common/Caching/IDistributedJOHConsultationRoomLockCache.cs, VideoWeb/VideoWeb.UnitTests/Common/Caching/DistributedJOHConsultationRoomLockCacheTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/StartConsultationTest.cs, VideoWeb/VideoWeb/Controllers/ConsultationsController.cs, VideoWeb/VideoWeb/Extensions/ConfigureServicesExtensions.cs
https://tools.hmcts.net/jira/browse/VIH-9001
Added a Redis cache class to implement the locking .   
The new change blocks the creation of new room when two parallel request are sent . It will delay the second request to prevent the creation of a new room.
```
[ ] Yes
[ x] No
```
=> VIH-9001 Restrict Joh Consultation Room

charts/vh-video-web/Chart.yaml, charts/vh-video-web/values.demo.template.yaml, charts/vh-video-web/values.dev.template.yaml, charts/vh-video-web/values.yaml
VIH-9236
Update Resource ID
```
[ ] Yes
[ x ] No
```
=> VIH-9236 - Update Resource ID

azure-pipelines.sds.pr-close.yml, azure-pipelines.sds.pr-release.yml
VIH-9254
Add/Remove Reply URLs
```
[ ] Yes
[ x ] No
```
=> VIH-9254 - Add/Remove Reply URLs

VideoWeb/VideoWeb/ClientApp/src/app/shared/directives/hook-element.directive.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/directives/hook-element.directive.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/modal/modal-trap-focus.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/shared.module.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/consultation-leave/consultation-leave.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
[VIH-7850](https://tools.hmcts.net/jira/browse/VIH-7850)
creating a trap focus on the focusable element in the modal window
=> VIH-7850 - bleed through in consultation and hearing room

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html
https://tools.hmcts.net/jira/browse/VIH-7850
=> VIH-7850 - bug fix

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-info-tooltip/participant-info-tooltip.component.html, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-info-tooltip/participant-info-tooltip.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-info-tooltip/participant-info-tooltip.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-info-tooltip/participant-info-tooltip.spec.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-9286
```
[ ] Yes
[X] No
```
=> VIH-9286 updated quicklinks text

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-9298
```
[ ] Yes
[X] No
```
=> VIH-9298 Welsh Translation for Care Standards added

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html
https://tools.hmcts.net/jira/browse/VIH-9461
implement show/hide context menu
=> VIH-9461 - implement show/hide context menu

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.Contract/Responses/ConferenceResponse.cs, VideoWeb/VideoWeb.IntegrationTests/VideoWeb.IntegrationTests.csproj, VideoWeb/VideoWeb.IntegrationTests/packages.lock.json, VideoWeb/VideoWeb.UnitTests/Controllers/AudioRecordingControllerTest.cs, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/ClientApp/src/app/services/api/audio-recording.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/notification-toastr.service.ts, VideoWeb/VideoWeb/Controllers/AudioRecordingController.cs, VideoWeb/VideoWeb/Mappings/ConferenceResponseMapper.cs, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-9467
See commits
```
[ ] Yes
[X] No
```
=> VIH-9467 increased recording alerts since hotfix

VideoWeb/VideoWeb/ClientApp/src/app/services/api/config.service.ts
https://tools.hmcts.net/jira/browse/VIH-9486
added no cache headers
=> VIH-9486 - added no cache headers

VideoWeb/VideoWeb/Dockerfile
https://tools.hmcts.net/jira/browse/VIH-9477
VIH-9477 Add curl to docker build
```
[ ] Yes
[ X] No
```
=> VIH-9477 Add curl to docker build

azure-pipelines.sds.master-release.yml, azure-pipelines.sds.pr-close.yml, azure-pipelines.sds.pr-release.yml, azure-pipelines.sds.release.yml
VIH-9517 - add master release pipeline
VIH-9517 - add master release pipeline
```
[ ] Yes
[x  ] No
```
=> VIH-9517 - add master release pipeline

azure-pipelines.sds.pr-release.yml, charts/vh-video-web/Chart.yaml, charts/vh-video-web/values.yaml
VIH-9532 - Amend PR release pipeline
VIH-9532 - Amend PR release pipeline
```
[ ] Yes
[x ] No
```
=> VIH-9532 - Amend PR release pipeline

charts/vh-video-web/Chart.yaml, charts/vh-video-web/values.yaml
VIH-9999 - remove additional URLs PR releases,bump chart
VIH-9999 - remove additional URLs PR releases,bump chart
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - remove additional URLs PR releases - bump chart

VideoWeb/VideoWeb/ClientApp/src/app/shared/chat-input-box/chat-input-box.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/chat-input-box/chat-input-box.component.scss
https://tools.hmcts.net/jira/browse/VIH-8612
added css class for white text in chat info
=> VIH-8612 - added css class for white text in chat info

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.EventHub/Mappers/HeartbeatRequestMapper.cs, VideoWeb/VideoWeb.EventHub/Models/Heartbeat.cs, VideoWeb/VideoWeb.IntegrationTests/packages.lock.json, VideoWeb/VideoWeb.UnitTests/Mappings/HeartbeatRequestMapperTests.cs, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/kinly-heartbeat.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/kinly-heartbeat.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/device-type.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/device-type.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/mappers/heartbeat-model-mapper.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/mappers/heartbeat-model-mapper.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/heartbeat.ts, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json, charts/vh-video-web/Chart.yaml, charts/vh-video-web/values.dev.template.yaml, charts/vh-video-web/values.yaml
https://tools.hmcts.net/jira/browse/VIH-9495
```
[ ] Yes
[ x] No
```
=> VIH-9495 AddDeviceInfoToHeartbeatTable

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.scss
https://tools.hmcts.net/jira/browse/VIH-7856
Changes the participant details lists to use `<dl>` elements for improved screen reader accessibility.
```
[ ] Yes
[x] No
```
=> VIH-7856 Update markup for participant lists

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/abstract/equipment-check-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/tasks-test-data.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/services/models/session-keys.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/tasks-table/tasks-table.component.html, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/tasks-table/tasks-table.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/tasks-table/tasks-table.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/tasks-table/tasks-table.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts
https://tools.hmcts.net/jira/browse/VIH-9687
Self test form result saved in a SessionStorage if test have successfully completed.
Check added on tasks-table.component.html to prevent to show "Failed self-test" message
=> VIH-9687 - Alert-Failed-On-Self-Test

CODEOWNERS
=> VIH-9698 Update CODEOWNERS add qa group as reviewer

VideoWeb/VideoWeb/ClientApp/src/app/shared/directives/tooltip.directive.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/directives/tooltip.directive.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-global-styles.scss
https://tools.hmcts.net/jira/browse/VIH-8609
Key event added to show tooltip on for top nav when tabbing to the icons
=> VIH-8609 - Key event added to show tooltip

VideoWeb/VideoWeb/ClientApp/src/styles.css
[VIH-9842](https://tools.hmcts.net/jira/browse/VIH-9842)
Update css to position toaster below the button
=> VIH-9842 - VideoWeb hearings-messages is accessible when notification is shown

VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/venue-list.component.html
https://tools.hmcts.net/jira/browse/VIH-9861
Enables csos to be searched on by their full name, rather than just their first name
```
[ ] Yes
[x] No
```
=> VIH-9861 Enable searching on csos by full name

VideoWeb/VideoWeb/ClientApp/src/app/security/auth-base.guard.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/auth-base.guard.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/auth.guard.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/judge.guard.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/judge.guard.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/logout/logout.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/logout/logout.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/participant.guard.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/participant.guard.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/launch-darkly.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/launch-darkly.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/staff-member-venue-list/staff-member-venue-list.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/venue-list.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/venue-list.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/vh-officer-venue-list/vh-officer-venue-list.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/command-centre.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/tests/command-centre.component-core.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/tests/command-centre.component-events.spec.ts, VideoWeb/VideoWeb/Controllers/FeatureFlagController.cs, azure-pipelines.sds.pr-release.yml
VIH-9882
* refactor launch darkly to publish feature flag changes once client is ready
* moved away from feature flag service where possible
* replace `ejudfeature` with `multi-idp-selection` where relating to idp selection component
```
[ ] Yes
[x] No
```
=> VIH-9882 launch darkly client waits until ready

VideoWeb/VideoWeb.UnitTests/Helpers/AllocationHearingsEventNotifierTests.cs, VideoWeb/VideoWeb/ClientApp/package-lock.json, VideoWeb/VideoWeb/ClientApp/package.json, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/command-centre.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/tests/command-centre.component-events.spec.ts, VideoWeb/VideoWeb/Helpers/AllocationHearingsEventNotifier.cs
VIH-9877
Better defensive against empty allocation hearings
Do not show toast notifications when allocation hearings list is empty
```
[ ] Yes
[x] No
```
=> VIH-9877 allocation notifications for same day only 

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/command-centre.component.html
VIH-9833
*  Update text form 'Change courts' to 'Change selection' in the command centre component
```
[ ] Yes
[x] No
```
=> VIH-9833 text change

VideoWeb/VideoWeb/ClientApp/src/app/shared/directives/tooltip.directive.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts, azure-pipelines.sds.pr-release.yml
VIH-9858
* wait for conference to be resolved before publishing media status (this would throw an exception because the participant id was not set quick enough)
* null check on tooltip method - without it the app would throw a fatal error
```
[ ] Yes
[x] No
```
=> VIH-9858 error on menu item hover

VideoWeb/VideoWeb.EventHub/Exceptions/ParticipantNotFoundException.cs, VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs, VideoWeb/VideoWeb.EventHub/Hub/IEventHubClient.cs, VideoWeb/VideoWeb.UnitTests/Hub/ToggleAllParticipantLocalMuteTests.cs, VideoWeb/VideoWeb.UnitTests/Hub/ToggleParticipantLocalMuteTests.cs, VideoWeb/VideoWeb/ClientApp/src/app/services/events.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/events.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant-event.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant-toggle-local-mute-message.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/mock-events-service.ts
VIH-9804
Add new toggle local mute methods to event hub client
```
[ ] Yes
[x] No
```
=> VIH-9804 add toggle local mute methods on eventhub client

VideoWeb/VideoWeb/Startup.cs
[VIH-9863](https://tools.hmcts.net/jira/browse/VIH-9863)
=> VIH-9863 - enable hsts

VideoWeb/VideoWeb/ClientApp/src/app/services/conference/participant.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/participant.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VIH-9937
VIH-9960
VIH-9961 
* Adding Video Endpoints last minute bug fixes:
* Update list of endpoints in participant service when endpoints have changed (updates the participant list)
* stop publishing endpoint updated notifications (this DTO needs to correctly state if there is a change to notify)
* stop unhandled error thrown when pausing a hearing after adding a new endpoint
```
[ ] Yes
[x] No
```
=> VIH-9937 last minute endpoint add bug fixes

VideoWeb/VideoWeb/ClientApp/src/app/shared/providers/global-error-handler.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/providers/global-error-handler.ts
https://tools.hmcts.net/jira/browse/VIH-9973
Reverts a change made to redirect users to an error page when there is an unhandled exception
```
[ ] Yes
[x] No
```
=> VIH-9973 Revert error handling to swallow errors rather than redirect

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-9976
Adds english and welsh translations for the Damages case type
```
[ ] Yes
[x] No
```
=> VIH-9976 Add translations for Damages case type

VideoWeb/VideoWeb/ClientApp/src/app/shared/providers/global-error-handler.ts
Fixes a DI error on startup
```
[ ] Yes
[x] No
```
=> VIH-0000 Fix for DI error on startup

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-global-styles.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.non-event.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VIH-8305
* update the max width of the room title label based on screen  width
Note: to avoid `ExpressionChangedAfterItHasBeenCheckedError` the expression to check overflow has been moved out from the templates's ngIf and moved to afterContentChecked. There is room to optimise this page by updating the change strategy to `onPush`
```
[ ] Yes
[x] No
```
=> VIH-8305 update the max width of the room title label based on screen width

VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json, charts/vh-video-web/values.dev.template.yaml
[VIH-9775](https://tools.hmcts.net/jira/browse/VIH-9775)
=> VIH-9775 - update bookings api package

.github/workflows/main.yml
VIH-10015
Update pr title lint rule
```
[ ] Yes
[x] No
```
=> VIH-10015 update pr title lint rule

.github/CODEOWNERS
https://tools.hmcts.net/jira/browse/VIH-10016
Add codeowner file so all code changes need vh and vh-qa & so that devops approve the pipeline files and the .github folder
```
[ ] Yes
[x] No
```
=> VIH-10016 Add CodeOwner file

VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.UnitTests/Extensions/ConferenceForVhOfficerResponseExtensionsTests.cs, VideoWeb/VideoWeb.UnitTests/Mappings/ConferenceForVhOfficerResponseMapperTests.cs, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/Mappings/ConferenceForVhOfficerResponseMapper.cs, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json
VIH-10001
provide allocated cso name or not required if venue does not suppport work allocation
```
[ ] Yes
[x] No
```
=> VIH-10001 utilise the SupportsWorkAllocation property to correctly assign AllocatedTo 

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
VIH-10012
Dismiss is misleading to hosts because the same word is used to dismiss participants from hearings as well as closing notification popups
```
[ ] Yes
[x] No
```
=> VIH-10012 Update text for toast notification dismiss to OK

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/hearing-role-model.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/start-private-consultation/start-private-consultation.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/start-private-consultation/start-private-consultation.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json, charts/vh-video-web/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10087
- Adds translations for the Crime Crown Court case type
- Prevents participants in the Victim and Police hearing roles from starting or joining private consultations
```
[ ] Yes
[x] No
```
=> VIH-10087 Add new case type for Chester Crime Pathfinder

VideoWeb/VideoWeb/ClientApp/package.json, VideoWeb/VideoWeb/ClientApp/src/app/shared/accessibility/accessibility.component.html, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-9859
content and translations
```
[ ] Yes
[X] No
```
=> VIH-9859 New accessibility page content and translations

VideoWeb/VideoWeb/Middleware/RequestBodyLoggingMiddleware.cs, VideoWeb/VideoWeb/Startup.cs
N/A
Add logging for request body
```
[ ] Yes
[x] No
```
=> VIH-0000 Add RequestBodyLoggingMiddleware.cs

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, VideoWeb/VideoWeb.Common/Models/Conference.cs, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.Contract/Responses/ConferenceForIndividualResponse.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferenceByIdTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferenceByIdVHOTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForHostTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForIndividualTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForVHOfficerTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/HealthController/HealthTests.cs, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/Controllers/ConferencesController.cs, VideoWeb/VideoWeb/Controllers/HealthCheckController.cs, VideoWeb/VideoWeb/Helpers/ConferenceHelper.cs, VideoWeb/VideoWeb/Mappings/BookingForHostResponseMapper.cs, VideoWeb/VideoWeb/Mappings/BookingForIndividualResponseMapper.cs, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json, charts/vh-video-web/values.dev.template.yaml
VIH-10162
Use Bookings API as primary source for hearing list
```
[ ] Yes
[x] No
```
=> VIH-10162 Use bookings as primary source for host and individual hearing list

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.ts
https://tools.hmcts.net/jira/browse/VIH-10167
Fix for tabbed items to be actionable when "enter" or "space" is pressed on the keyboard
```
[ ] Yes
[X] No
```
=> VIH-10167 Keyboard navigation unable to select buttons in hearing consultion room

VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.UnitTests/Extensions/ConferenceForVhOfficerResponseExtensionsTests.cs, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json, charts/vh-video-web/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10130
Updates Video Web to use the updated HearingAllocationExcludedVenueList from Bookings API
=> VIH-10130 Add Teesside venues back in to work allocation script

VideoWeb/VideoWeb/ClientApp/package-lock.json, VideoWeb/VideoWeb/ClientApp/package.json
[VIH-10010](https://tools.hmcts.net/jira/browse/VIH-10010)
update govuk-frontend package
=> VIH-10010 - update govuk-frontend package

VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForIndividualTests.cs, VideoWeb/VideoWeb/Controllers/ConferencesController.cs
https://tools.hmcts.net/jira/browse/VIH-10232
Bug introduced in change to query hearings for participants from booking api. Quicklinks are not created in the booking api so, this causing the query to fall over for them when they log in,
=> VIH-10232 Reintroduced logic to queryhearing data from videoapi if participant is a quicklink user

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/admin-im-list/admin-im-list.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-status/participant-status.component.html, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-hearing-list/vho-hearing-list.component.scss
VIH-10155
Change the cursor to a pointer for hearing list and participant IM list
=> VIH-10155 change the cursor to a pointer for hearing list and participant IM list

VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForVHOfficerTests.cs, VideoWeb/VideoWeb.UnitTests/Helpers/Sorting/SortConferenceForVhoOfficerHelperTests.cs, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/introduction/introduction.component.spec.ts, VideoWeb/VideoWeb/Controllers/ConferencesController.cs, VideoWeb/VideoWeb/Helpers/Sorting/SortConferenceForVhoOfficerHelper.cs
VIH-10224
Update the conference order list of VHOs
=> VIH-10224 Update VHO conference list order

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/host-hearing-list/host-hearing-table/host-hearing-table.component.html, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/introduction/introduction.component.html, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-hearings/hearing-list-table.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/shared.module.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/truncatable-text/truncatable-text.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/truncatable-text/truncatable-text.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/shared/truncatable-text/truncatable-text.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/truncatable-text/truncatable-text.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/command-centre.component.html, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearing-header/hearing-header.component.html, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-hearing-list/vho-hearing-list.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/assets/images/favicons/manifest.json, VideoWeb/VideoWeb/ClientApp/src/styles.scss
VIH-7601
truncate case name and number
add a truncate text component to simplify the display
=> VIH-7601 Truncate text with very long words in lists

VideoWeb/VideoWeb.Common/Caching/DistributedConferenceCache.cs, VideoWeb/VideoWeb.Common/Caching/DistributedConferenceVideoControlStatusCache.cs, VideoWeb/VideoWeb.Common/Caching/DistributedConsultationInvitationCache.cs, VideoWeb/VideoWeb.Common/Caching/DistributedHearingLayoutCache.cs, VideoWeb/VideoWeb.Common/Caching/DistributedJOHConsultationRoomLockCache.cs, VideoWeb/VideoWeb.Common/Caching/DistributedTestCallCache.cs, VideoWeb/VideoWeb.Common/Caching/DistributedUserClaimsCache.cs, VideoWeb/VideoWeb.Common/Caching/DistributedUserProfileCache.cs, VideoWeb/VideoWeb.Common/Caching/RedisCacheBase.cs, VideoWeb/VideoWeb.UnitTests/Cache/DistributedConferenceCacheTests.cs, VideoWeb/VideoWeb.UnitTests/Cache/DistributedTestCallCacheTests.cs, VideoWeb/VideoWeb.UnitTests/Cache/DistributedUserCacheTests.cs, VideoWeb/VideoWeb.UnitTests/Common/Caching/DistributedConsultationInvitationCacheTests.cs, VideoWeb/VideoWeb.UnitTests/Common/Caching/DistributedJOHConsultationRoomLockCacheTests.cs, charts/vh-video-web/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10207
Catch and handle redis exceptions and fall back to reading from the database
=> VIH-10207 Graceful handling of redis exceptions

VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs, VideoWeb/VideoWeb.EventHub/Hub/IEventHubClient.cs, VideoWeb/VideoWeb.EventHub/Models/SendMessageDto.cs, VideoWeb/VideoWeb.UnitTests/Hub/EventHubBaseTests.cs, VideoWeb/VideoWeb.UnitTests/Hub/SendMessageTests.cs, VideoWeb/VideoWeb/ClientApp/src/app/services/events.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/chat/chat-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/chat/chat-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/chat-panel/chat-panel.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/chat-window-base.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.ts
VIH-10265
Include the sender's display name for instant messages.
Removes the dependency on the profile service and the cache to retrieve display names
=> VIH-10265 provide the IM sender display name and remove profile dependency

VideoWeb/VideoWeb.Common/Models/Conference.cs, VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs, VideoWeb/VideoWeb.EventHub/Services/InstantMessageRules.cs, VideoWeb/VideoWeb.UnitTests/Hub/SendMessageTests.cs, VideoWeb/VideoWeb.UnitTests/Services/InstantMessageRulesTests.cs
VIH-10308
Bug fix update rules of engagement for IM
=> VIH-10308 Bug fix update rules of engagement for IM

charts/vh-video-web/Chart.yaml
=> VIH-10233 upping java chart

README.md, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
https://tools.hmcts.net/jira/browse/VIH-8576
=> VIH-8576 Added fix so that unlock all also unlocks manually muted participants

VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/AddEndpointToConsultationTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/StartConsultationTest.cs, VideoWeb/VideoWeb.UnitTests/Controllers/EndpointController/GetEndpointsLinkedToUserTests.cs, VideoWeb/VideoWeb/Controllers/ConsultationsController.cs, VideoWeb/VideoWeb/Controllers/EndpointsController.cs, charts/vh-video-web/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10389
https://tools.hmcts.net/jira/browse/VIH-10427
Updated Endpoint controller to get the person logged in and check both their contact email and user name against the endpoint defence advocate, as a new user at the time of creation doesnt have a username yet.
=> VIH-10389 New created reps unable to start private consultation with linked JVS

VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/AddEndpointToConsultationTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/StartConsultationTest.cs, VideoWeb/VideoWeb.UnitTests/Controllers/EndpointController/GetEndpointsLinkedToUserTests.cs, VideoWeb/VideoWeb/Controllers/ConsultationsController.cs, VideoWeb/VideoWeb/Controllers/EndpointsController.cs, charts/vh-video-web/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10462
Reverted previous change, used to fix https://tools.hmcts.net/jira/browse/VIH-10389
=> VIH-10462 quicklink participant can not start a private consultation

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
https://tools.hmcts.net/jira/browse/VIH-10514
Re-adds a line to set the participants, that previously been removed
=> VIH-10514 Fix - judge cannot resume hearing after pausing

VideoWeb/VideoWeb/ClientApp/src/app/services/launch-darkly.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/admin-hearing/admin-hearing.component.html, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/admin-hearing/admin-hearing.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/admin-hearing/admin-hearing.component.ts
[VIH-10607](https://tools.hmcts.net/jira/browse/VIH-10607)
added feature flag for vodafone
=> VIH-10607 - added feature flag for vodafone

VideoWeb/VideoWeb/ClientApp/package-lock.json, VideoWeb/VideoWeb/ClientApp/package.json, VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/venue-list.component.html, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
[VIH-10570](https://tools.hmcts.net/jira/browse/VIH-10570)
added label tag
=> VIH-10570 - Axe Failure: Venue-list-component

VideoWeb/VideoWeb/ClientApp/package-lock.json, VideoWeb/VideoWeb/ClientApp/package.json, VideoWeb/VideoWeb/ClientApp/src/app/shared/shared.module.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-legal-rep-terms-of-service/private-consultation-legal-rep-terms-of-service.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-legal-rep-terms-of-service/private-consultation-legal-rep-terms-of-service.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-legal-rep-terms-of-service/private-consultation-legal-rep-terms-of-service.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/start-private-consultation/start-private-consultation.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/start-private-consultation/start-private-consultation.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/start-private-consultation/start-private-consultation.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-space.module.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
VIH-9722
display a terms of service if user is a rep and starts a private consultation with private endpoints
=> VIH-9722 Display Terms of Service before private consultation

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/on-the-day-routing.module.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/judge-or-judicial-office-holder.guard.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/judge-or-judicial-office-holder.guard.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/judge.guard.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/judicial-office-holder.guard.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/judicial-office-holder.guard.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/participant.guard.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/participant.guard.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/role-guard.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/staff-member.guard.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/security/staff-member.guard.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-space-routing.module.ts
https://tools.hmcts.net/jira/browse/VIH-8648
- Fixes an issue where a joh can access the judge waiting room, or vice versa, by changing the url
- Fixes an issue where non-participants can access the participant waiting room by changing the url
- Use separate guards for judges, johs and a combination. Refactor using a common `RoleGuard`
=> VIH-8648 Fix for impersonating roles in waiting room by changing url

VideoWeb/VideoWeb.UnitTests/AuthenticationSchemes/Dom1SchemeTests.cs, VideoWeb/VideoWeb.UnitTests/AuthenticationSchemes/EJudiciarySchemeTests.cs, VideoWeb/VideoWeb/AuthenticationSchemes/AadSchemeBase.cs, VideoWeb/VideoWeb/AuthenticationSchemes/EJudiciaryScheme.cs
https://tools.hmcts.net/jira/browse/VIH-10720
Add support for `JsonWebToken`, introduced with .NET 8
=> VIH-10720 Fix for ejud and dom1 login

VideoWeb/VideoWeb/ClientApp/package-lock.json, VideoWeb/VideoWeb/ClientApp/package.json, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/models/pexip-display-name-model.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/models/pexip-display-name.model.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/participant.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/participant.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/reducers/conference.reducer.ts, VideoWeb/VideoWeb/ClientApp/src/scripts/kinly/pexrtc.js
VIH-10753
Pexip participant events are randomly pushing events with no display name or id. we should handle this to stop components from crashing
=> VIH-10753 handle undefined pexip participants

VideoWeb/VideoWeb/ClientApp/src/app/app.component.html, VideoWeb/VideoWeb/ClientApp/src/app/app.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/app.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/header/header.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/header/header.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/shared/header/header.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/header/header.component.ts
VIH-10752
display username in header
=> VIH-10752 display username in header

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/models/vh-conference.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/reducers/conference.reducer.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/reducers/conference.reducer.ts, azure-pipelines.sds.pr-release.yml
VIH-10771 
map pexip participant to endpoints
without the Pexip uuid it is not possible to remote mute the endpoint specifically
=> VIH-10771 map pexip participant to endpoints

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.scss
https://tools.hmcts.net/jira/browse/VIH-10757
Fixes an issue where clicking the Leave Hearing button via the Enter key bypasses the confirmation popup.
Additional changes made to pass sonar checks
- Convert buttons from divs to button elements
- CSS tweaks to keep the original styling intact
=> VIH-10757 Fix for leave hearing confirmation bypassed when pressing Enter

VideoWeb/VideoWeb.UnitTests/Controllers/EndOfDayController/GetActiveConferencesTests.cs, VideoWeb/VideoWeb/Controllers/EndOfDayController.cs
VIH-10778
Capture an empty list when selecting active sessions to behave as the other filters
=> VIH-10778 - handle no active sessions

VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts
https://tools.hmcts.net/jira/browse/VIH-10781
- Fixes an issue for keyboard navigation, where focus is lost on the hearing controls after selecting a camera and mic on Firefox and Safari
- Additional sonar fixes
=> VIH-10781 Fix for loss of focus when tabbing through hearing controls

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts
VIH-10786
dispatch actions for update and delete callbacks from pexip
=> VIH-10786 dispatch actions for update and delete callbacks from pexip

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/notification-toastr.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/notification-toastr.service.ts
https://tools.hmcts.net/jira/browse/VIH-10805
Missing null coalescing operator for name ?? display name needed for quicklink participants to be displayed (who have no full name property anymore)
=> VIH-10805 Quicklink Participants and Observers not showing in participant status list in waiting room

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.scss
[VIH-10789](https://tools.hmcts.net/jira/browse/VIH-10789)
changed layout of the participant panel
=> VIH-10789 - Judge Screen - In Waiting Room number pushed on to 2nd line when 10 or more participants in a hearing

VideoWeb/VideoWeb.Common/ConferenceService.cs, VideoWeb/VideoWeb.EventHub/Handlers/Core/EventHandlerBase.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferenceByIdTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferenceByIdVHOTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/ConferenceManagementControllerTestBase.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/StartConsultationTest.cs, VideoWeb/VideoWeb.UnitTests/Controllers/EndpointController/GetEndpointsLinkedToUserTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/InternalEventController/ParticipantsUpdatedTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ParticipantController/StaffMemberJoinConferenceTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/QuickLinkController/JoinConferenceAsAQuickLinkUser.cs, VideoWeb/VideoWeb.UnitTests/Controllers/VideoEventController/BaseSendHearingEventTests.cs, VideoWeb/VideoWeb.UnitTests/EventHandlers/EventHandlerTestBase.cs, VideoWeb/VideoWeb.UnitTests/EventHandlers/VhOfficerCallEventHandlerTests.cs, VideoWeb/VideoWeb.UnitTests/Services/ParticipantsServiceTests.cs, VideoWeb/VideoWeb/ClientApp/src/app/services/events.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts, VideoWeb/VideoWeb/Controllers/ConsultationsController.cs, VideoWeb/VideoWeb/Controllers/ParticipantsController.cs, VideoWeb/VideoWeb/Controllers/QuickLinksController.cs, VideoWeb/VideoWeb/Controllers/VideoEventsController.cs, VideoWeb/VideoWeb/Services/IParticipantService.cs, VideoWeb/VideoWeb/Services/ParticipantService.cs, VideoWeb/VideoWeb/appsettings.Development.json
VIH-10795
* Filter for duplicate messages in the event hub client
* Filter for empty Pexip participants that has caused unexpected bugs recently
* bug fix the adding a staff member to the cache
* stopped using the mapper factory for a mapper type that does not exist
=> VIH-10795 staff member joined dupe notification

VideoWeb/VideoWeb.UnitTests/AuthenticationSchemes/EJudiciarySchemeTests.cs, VideoWeb/VideoWeb/AuthenticationSchemes/AadSchemeBase.cs, VideoWeb/VideoWeb/AuthenticationSchemes/EJudiciaryScheme.cs
VIH-10815 
Do not check for additional claims if logging in with an ejud account
=> VIH-10815 bugfix ejud accounts are querying for justice roles when they should not

VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.Contract/Request/StartOrResumeVideoHearingRequest.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/GetLayoutForHearingTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/GetRecommendedLayoutForHearingTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/StartVideoHearingTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/UpdateLayoutForHearingTests.cs, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts, VideoWeb/VideoWeb/Controllers/ConferenceManagementController.cs, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json, charts/vh-video-web/values.dev.template.yaml
VIH-10812
* Only transfer the host into a hearing who triggered it. This logic has moved into the video api rather than video web
* Introduced a leaner start hearing dto to avoid exposing extra properties needed that was replaced by video api anyway
=> VIH-10812 stop forcing all hosts to join a hearing on start

VideoWeb/VideoWeb.Common/AppRoleService.cs, VideoWeb/VideoWeb.Common/Caching/DistributedUserProfileCache.cs, VideoWeb/VideoWeb.Common/Caching/RedisCacheBase.cs, VideoWeb/VideoWeb.Common/VhApiLoggingDelegatingHandler.cs, VideoWeb/VideoWeb.UnitTests/Cache/DistributedUserCacheTests.cs, VideoWeb/VideoWeb.UnitTests/Services/AppRoleServiceTests.cs, VideoWeb/VideoWeb/AuthenticationSchemes/AadSchemeBase.cs, VideoWeb/VideoWeb/Extensions/ConfigureServicesExtensions.cs
VIH-10836
Handle concurrent requests to check for additional claims Log VH API request, times and other info
=> VIH-10836 Handle concurrent requests to check for additional claims Log VH API request info

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.eventhub.events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/tests/judge-waiting-room.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.analogue-time.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.eventhub.events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/WRTestComponent.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base-setup.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.non-event.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.video-call-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/scripts/kinly/pexrtc.js, VideoWeb/VideoWeb/ClientApp/src/scripts/vodafone/pexrtc.js, VideoWeb/VideoWeb/ClientApp/src/typings.d.ts
VIH-10826
connect to VMR rooms only if vodafone toggle is off
=> VIH-10826 connect to VMR rooms only if vodafone toggle is off

VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/ClientApp/src/app/services/launch-darkly.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/staff-member-venue-list/staff-member-venue-list.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/venue-list.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/venue-list.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/venue-list.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/vh-officer-venue-list/vh-officer-venue-list.component.spec.ts, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json
VIH-10879
add a feature flag for active sessions filter
=> VIH-10879 add a feature flag for active sessions filter

VideoWeb/VideoWeb.Common/FeatureToggles.cs, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/Startup.cs, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json
VIH-10886 
Add Microsoft.ApplicationInsights.Profiler
> Applied behind a feature toggle
=> VIH-10886 Add Microsoft.ApplicationInsights.Profiler

VideoWeb/VideoWeb/ClientApp/angular.json, VideoWeb/VideoWeb/ClientApp/package-lock.json, VideoWeb/VideoWeb/ClientApp/package.json, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/heartbeat.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/select-hearing-layout/select-hearing-layout.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/select-hearing-layout/select-hearing-layout.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts, VideoWeb/VideoWeb/ClientApp/src/globals.d.ts, VideoWeb/VideoWeb/ClientApp/src/index.html, VideoWeb/VideoWeb/ClientApp/src/typings.d.ts
VIH-10898 bugfix import for heartbeat
update import for heartbeat js directly rather via angular
add global typings for pexrtc and heartbeat js to simplify component imports
init accordions as advised by the post v5 upgrade for GDS
=> VIH-10898 bugfixes post package upgrades

VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs, VideoWeb/VideoWeb/ClientApp/package-lock.json, VideoWeb/VideoWeb/ClientApp/package.json, VideoWeb/VideoWeb/ClientApp/src/app/app.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/app.component.testbed.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/app.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/quick-links/quick-links.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/quick-links/quick-links.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/events-hub.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/events-hub.service.ts
VIH-10915
* connect to signalR AFTER a user is authenticated
When an unauthenticated user makes a connection to signalR, it seems the same connection id is maintained and the user is not correctly registered to the correct groups. To minimise red herrings in the logs only authenticated users were subscribing to the appropriate groups. To complete this change the ng client app will not initiate the connection until the user is authenticated.
=> VIH-10915 connect to signalR AFTER a user is authenticated

VideoWeb/VideoWeb.EventHub/Hub/IEventHubClient.cs, VideoWeb/VideoWeb.EventHub/Services/ConferenceManagementService.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagementNonHost/NonHostLeaveHearingTests.cs, VideoWeb/VideoWeb.UnitTests/Services/ConferenceManagementServiceTests.cs, VideoWeb/VideoWeb/Controllers/ConferenceManagementNonHostController.cs
VIH-10918
Add an API operation to allow non host participants to dismiss themselves from a hearing.
Publish a new message via the EventHubClient
=> VIH-10918 add an API operation to allow non-host participants to leave and publish the message to the conference channel

VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.Contract/VideoWeb.Contract.csproj, VideoWeb/VideoWeb.EventHub/VideoWeb.EventHub.csproj, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/CallParticipantTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/DismissParticipantTests.cs, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-context-menu/judge-context-menu.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-context-menu/judge-context-menu.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-context-menu/judge-context-menu.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel-item/participants-panel-item.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel-item/participants-panel-item.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts, VideoWeb/VideoWeb/Controllers/ConferenceManagementController.cs, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json
VIH-10584
dismiss participant to waiting room
=> VIH-10584 admit and dismiss participant in and out of the waiting room

VideoWeb/VideoWeb/ClientApp/src/app/services/launch-darkly.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/directives/feature-flag.directive.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/directives/feature-flag.directive.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/shared.module.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.ts
VIH-10916 
language change should be behind the feature flag 'interpreter-enhancements'
=> VIH-10916 language selection to be behind a feature flag

.github/workflows/close-pr.yml
https://tools.hmcts.net/jira/browse/VIH-10784
Enables for closed pr's to be removed from url's when not merged
=> VIH-10784 close pr fix

.github/workflows/close-pr.yml
https://tools.hmcts.net/jira/browse/VIH-10784
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
Change pr close
=> VIH-10784 Update close pr

VideoWeb/VideoWeb/ClientApp/src/app/services/launch-darkly.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/launch-darkly.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/effects/video-call.effects.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/effects/video-call.effects.ts
VIH-10930
Only Pexip V35 and above have the necessary api operations for this to work. Not all environments have been upgraded
=> VIH-10930 filter for interpreter enhancements enabled before running video call effects

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
VIH-10928
update key name for case type translation
=> VIH-10928 update key name for case type translation

VideoWeb/VideoWeb.Common/Security/Tokens/Base/JwtTokenProvider.cs, VideoWeb/VideoWeb/appsettings.json
=> VIH-10990 add audience and issuer for vodafone api

VideoWeb/VideoWeb.Common/Caching/ConferenceCacheMapper.cs, VideoWeb/VideoWeb.Common/Caching/EndpointCacheMapper.cs, VideoWeb/VideoWeb.Common/Caching/TelephoneParticipantCacheMapper.cs, VideoWeb/VideoWeb.Common/Models/Conference.cs, VideoWeb/VideoWeb.Common/Models/TelephoneParticipant.cs, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.EventHub/Enums/EventType.cs, VideoWeb/VideoWeb.EventHub/Handlers/TelephoneJoinedEventHandler.cs, VideoWeb/VideoWeb.EventHub/Models/CallbackEvent.cs, VideoWeb/VideoWeb.UnitTests/Builders/EventComponentHelper.cs, VideoWeb/VideoWeb.UnitTests/Controllers/VideoEventController/SendHearingEventTests.cs, VideoWeb/VideoWeb.UnitTests/EventHandlers/EventHandlerFactoryTests.cs, VideoWeb/VideoWeb.UnitTests/EventHandlers/TelephoneDisconnectedEventHandlerTests.cs, VideoWeb/VideoWeb.UnitTests/EventHandlers/TelephoneJoinedEventHandlerTests.cs, VideoWeb/VideoWeb.UnitTests/EventHandlers/TelephoneTransferEventHandlerTests.cs, VideoWeb/VideoWeb.UnitTests/Mappings/ConferenceCacheMapperTests.cs, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/Controllers/VideoEventsController.cs, VideoWeb/VideoWeb/Mappings/CallbackEventMapper.cs, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json
VIH-10950
support telephone events
update the conference cache model
=> VIH-10950 support telephone events

README.md, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/Program.cs, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json, docker-compose.override.yml, setup-secrets.sh
VIH-10993
* reload on config change for secret by file
* Remove deprecated VH.Core.Configuration
=> VIH-10993 turn on reload on config change

charts/vh-video-web/Chart.yaml, charts/vh-video-web/values.dev.template.yaml
=> VIH-11003 - Missing telephone numbers on ITHC environments

VideoWeb/VideoWeb/ClientApp/src/app/shared/header/header.component.html, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-11015
Fixes for axe test failures
- Make aria labels unique. The label is already in use by another element on that page, so assign a different one
=> VIH-11015 Accessibility fixes

azure-pipelines.sds.master-release.yml
=> VIH-10843 fix indentation for master release pipeline

VideoWeb/VideoWeb.Common/Caching/ConferenceCacheMapper.cs, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.Contract/VideoWeb.Contract.csproj, VideoWeb/VideoWeb.UnitTests/Mappings/ConferenceCacheMapperTests.cs, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json, charts/vh-video-web/values.dev.template.yaml
[VIH-11018](https://tools.hmcts.net/jira/browse/VIH-11018)
use System.Text.Json apis
=> VIH-11018 Change json serializer from Newtonsoft.Json to System.Text.Json

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html
VIH-11071
* Wrap the hearing control icon for dial out with a container to only show if the the participant is a host
=> VIH-11071 only show the dialout icon if the participant is a host

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html
VIH-11078
All participants should see hearing is reading on transferring in after host manually admits them in
=> VIH-11078 all participants should see hearing is reading on transferring in after host manually admits them in

VideoWeb/VideoWeb.UnitTests/Controllers/ParticipantController/DeleteParticipantTests.cs, VideoWeb/VideoWeb/Controllers/ParticipantsController.cs
VIH-11137
Inform deleted participant of updated conference to refresh their hearing list
* Added a list of expected notifications to verify the correct participants are notified when a participant is removed in `DeleteParticipantTests.cs`.
* Enhanced `UpdateCacheAndPublishUpdatedParticipantList` to handle an optional removed participant, ensuring the correct list of participants is notified in `ParticipantsController.cs`.
=> VIH-11137 Refresh hearing list for participant after being removed

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html
[VIH-11154](https://tools.hmcts.net/jira/browse/VIH-11154)
restore if directive on participants panel when not a consultation
=> VIH-11154 restore if directive on participants panel when not a consultation

azure-pipelines.sds.master-release.yml
See VIH-11181](https://tools.hmcts.net/jira/browse/VIH-11181)
enable demo image and helm buildpush
=> VIH-11181 - enable demo image buildpush

azure-pipelines.sds.master-release.yml, variables/demo.yaml
See VIH-11181](https://tools.hmcts.net/jira/browse/VIH-11181)
adds missing demo env var file to enable demo image and helm buildpush
=> VIH-11181 enable demo image build with approval

VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferenceByIdTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/CallParticipantTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ParticipantController/GetCurrentParticipantTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ParticipantController/GetParticipantsByConferenceIdTest.cs, VideoWeb/VideoWeb/Controllers/ConferenceManagementController.cs, VideoWeb/VideoWeb/Controllers/ConferencesController.cs, VideoWeb/VideoWeb/Controllers/ParticipantsController.cs
https://tools.hmcts.net/jira/browse/VIH-11176
Replace calls to `ForceGetConference` with `GetConference` for user-facing endpoints
=> VIH-11176 Replace usage of ForceGetConference

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/video-endpoint-panel-model.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/video-endpoint-panel.model.spec.ts
VIH-11177
* Treat JVS endpoints in a consultation as In Waiting Room for the Host in hearing participant list
=> VIH-11177 Treat JVS endpoints in a consultation as In Waiting Room for the Host in hearing participant list

VideoWeb/VideoWeb.Common/Models/Conference.cs, VideoWeb/VideoWeb.Common/Models/Participant.cs, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.UnitTests/Common/Models/ParticipantTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/ConsultationHelper.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/InviteToConsultationTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/JoinPrivateConsultationTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/StartConsultationTest.cs, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/Controllers/ConsultationsController.cs, VideoWeb/VideoWeb/packages.lock.json
VIH-11178
Prevent consultations with Observers
=> VIH-11178 prevent consultations with Observers

VideoWeb/VideoWeb/ClientApp/src/app/services/conference/participant.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/mappers/participant-panel-model-mapper.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/reducers/conference.reducer.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/reducers/conference.reducer.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VIH-11196
capture and reset the transfer status in the conference store
add logs to why a user is navigated away from the hearing room
=> VIH-11196 capture and reset the transfer status in the conference store after admit

VideoWeb/VideoWeb/ClientApp/src/app/services/conference/participant.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/participant.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/select-hearing-layout/select-hearing-layout.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/select-hearing-layout/select-hearing-layout.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VIH-11203
Enhance participant tracking
Remove additional api calls in place of reliance on conference store
This pull request includes several changes to improve the handling of participants and enhance the logging and state management in the waiting room components. The most important changes include adding a trackBy function for participants, enhancing logging information, and modifying the state management in the `WaitingRoomBaseDirective`.
=> VIH-11203 subscribe to JVS endpoint updates from the conference store

VideoWeb/VideoWeb.Common/Models/Conference.cs, VideoWeb/VideoWeb.EventHub/Handlers/Core/EventHandlerBase.cs, VideoWeb/VideoWeb.UnitTests/EventHandlers/CloseEventHandlerTests.cs, VideoWeb/VideoWeb.UnitTests/EventHandlers/EventHandlerTestBase.cs
https://tools.hmcts.net/jira/browse/VIH-11201
To support an issue with the conference close time not showing in the UI for closed hearings
=> VIH-11201 Update closed date time in conference cache when closing the conference

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
https://tools.hmcts.net/jira/browse/VIH-11199
=> VIH-11199 Clear audio alert if video closed

VideoWeb/VideoWeb/ClientApp/src/app/services/launch-darkly.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VIH-11216
wrap unique call tag per call behind a feature flag
=> VIH-11216 wrap unique call tag per call behind a feature flag

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel-item/participants-panel-item.component.html
add ids for elem matching used by the automated UI tests. improves stability and accuracy of testing
add better ids for elem matching
=> VIH-11150 add ids for elem matching

VideoWeb/VideoWeb/ClientApp/src/scripts/vodafone/pexrtc.js
VIH-11225
update pexrtc client to resolve issues with disconnect
=> VIH-11225 update pexrtc client to resolve issues with disconnect

VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.Contract/VideoWeb.Contract.csproj, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/EndVideoHearingTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/GetLayoutForHearingTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/GetRecommendedLayoutForHearingTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/JoinHearingInSessionTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/LeaveHearingTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/PauseVideoHearingTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/StartVideoHearingTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/SuspendHearingTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/UpdateLayoutForHearingTests.cs, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts, VideoWeb/VideoWeb/Controllers/ConferenceManagementController.cs, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json, charts/vh-video-web/values.dev.template.yaml
VIH-11223
Provide the participant role on transfer
Remove try catch block in ConferenceManagement since it is already handled by the middleware
=> VIH-11223 Provide the participant role on transfer

.github/workflows/launch-darkly-find-code-refs-in-pr.yml, .github/workflows/launch-darkly-flag-sync.yml, .github/workflows/osv-scanner-pr.yml
VIH-11246
Update to the GitHub Actions:
* Switch the full LD code scan to run against master only and on a schedule
* Add the LD code scan on diff to run against PRs only
* Turn off fail on vuln for OSV scanner
=> VIH-11246 Update GH Actions

.github/renovate.json
VIH-11252
add renovate job for Helm Chart Release function
=> VIH-11252 add renovate job for Helm Chart Release function

VideoWeb/VideoWeb.Common/Caching/ConferenceCacheMapper.cs, VideoWeb/VideoWeb/ClientApp/src/app/shared/translation-id-converter.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
VIH-11256
fix translations and trim service names
=> VIH-11256 fix translations and trim service names

VideoWeb/VideoWeb.EventHub/Hub/IEventHubClient.cs, VideoWeb/VideoWeb.EventHub/Models/UpdatedAllocationDto.cs
VIH-9762
Update the event hub client. Changes to the operation do not work smoothly as a PR
=> VIH-9762 update eventhub client

VideoWeb/VideoWeb/ClientApp/src/app/services/conference/heartbeat.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/heartbeat.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/user-media-stream-v2.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/effects/conference.effects.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/effects/conference.effects.ts, VideoWeb/VideoWeb/ClientApp/src/typings.d.ts
VIH-11264
* when a call has ended, close subscriptions created when a call is made after
* redirect the user to service error page if there is a  heartbeat issue in the disconnect reason
=> VIH-11264 close device change subscription in video call service

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/host-hearing-list/host-hearing-table/host-hearing-table.component.html, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-hearings/hearing-list-table.component.html
VIH-11149
use the case number instead of case name (not multi-day friendly) as aria labels for the select hearing button
=> VIH-11149 update aria labels for select hearing

VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/hearing-layout.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/user-media-stream.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/chat/chat-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/test-language.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/wr-participant-list-shared.component.ts, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json, azure-pipelines.sds.master-release.yml, azure-pipelines.sds.pr-release.yml, sds-git-version-config.yml
VIH-11272
add logging to confirm stream
remove excess logging that add no value
refresh stream on videocall service setup client
=> VIH-11272 add logging to confirm stream

VideoWeb/VideoWeb.EventHub/Models/UpdatedAllocationDto.cs, VideoWeb/VideoWeb/Mappings/ConferenceDetailsToUpdatedAllocationDtoMapper.cs
VIH-11301
Add conference object to UpdatedAllocationDto.cs
This makes it easier to update the full object graph in the VHO CC list
=> VIH-11301 add conference object to UpdatedAllocationDto.cs

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/services/vho-query-service.service.ts
VIH-11301
Init event subscription in the vho query service
=> VIH-11301 init event subscription in the vho query service

VideoWeb/VideoWeb.Common/Models/Conference.cs, VideoWeb/VideoWeb.UnitTests/Models/Conference/UpdateParticipantStatusTests.cs, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/reducers/conference.reducer.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/reducers/conference.reducer.ts
VIH-11313
reset the transfer direction of a participant when the hearing has been paused or suspended
=> VIH-11313 reset the transfer direction of a participant when the hearing has been paused or suspended

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/hearing-rules/hearing-rules.component.html, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/quick-links/quick-links.component.html, VideoWeb/VideoWeb/ClientApp/src/app/security/login/login.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/unsupported-browser/unsupported-browser.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/venue-list.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/join-private-consultation/join-private-consultation.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html
VIH-11315
add govuk-body to p elements
=> VIH-11315 add govuk-body to p elements

VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.UnitTests/Controllers/ParticipantController/StaffMemberJoinConferenceTests.cs, VideoWeb/VideoWeb.UnitTests/Services/ParticipantsServiceTests.cs, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/Services/ParticipantService.cs, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json, charts/vh-video-web/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10794
=> VIH-10794 Update api client

VideoWeb/VideoWeb/ClientApp/src/app/shared/chat-body-window/chat-body-window.component.scss
[VIH-8359](https://tools.hmcts.net/jira/browse/VIH-8359)
css word wrap
=> VIH-8359 - A Long single word is going out of the box in IM

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-hearings/hearing-list-table.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/helpers/element-helper.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/venue-list.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/venue-list.component.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-11184
Fixes for failing accessibility tests
- Add table column header for screen readers
- Remove invalid `aria-placeholder` element from ng-select generated input elements
=> VIH-11184 Accessibility fixes

VideoWeb/VideoWeb/ClientApp/src/app/services/models/hearing-details-updated-message.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/mock-events-service.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/services/vho-query-service.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/services/vho-query-service.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.non-event.spec.ts
[VIH-11299](https://tools.hmcts.net/jira/browse/VIH-11299)
bug fix for schedule time converted to string. updates participants when change
=> VIH-11299 - Edits to judge not updating on VHO Command centre

variables/shared.yaml
https://tools.hmcts.net/jira/browse/VIH-11302
=> VIH-11302 Remove references to obsolete variable groups

VideoWeb/VideoWeb/ClientApp/package-lock.json, VideoWeb/VideoWeb/ClientApp/package.json, VideoWeb/VideoWeb/ClientApp/src/app/app.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/app.component.testbed.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/app.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/launch-darkly.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/no-sleep-v2.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/no-sleep-v2.service.ts
VIH-11343
The original implementation was inspired by the same package but does not take advantage of the wake lock api or have fallback options. This library handles this and reduces a dependency on the media stream object which makes unnecessary noise in the logs
=> VIH-11343 implement a NoSleepService using the no-sleep-app library

VideoWeb/VideoWeb/ClientApp/src/app/services/user-media-stream-v2.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts
VIH-11385
null check current stream before verifying if it is active
=> VIH-11385 null check current stream before verifying if it is active

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
VIH-11397
Add en translation for copy ql link tooltip text
=> VIH-11397 Add en translation for copy ql link tooltip text

.github/workflows/close-pr.yml, azure-pipelines.sds.pr-release.yml
TBC
Update the variable used for the pr branch
=> VIH-11409 close pr fix

VideoWeb/VideoWeb.Common/Models/Participant.cs, VideoWeb/VideoWeb/ClientApp/src/app/services/error.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts, azure-pipelines.sds.pr-release.yml
VIH-11407
Use the 'CONNECTED' state instead of active to determine whether or not to queue renegotiations
=> VIH-11407 Update VideoCallService to use 'CONNECTED' state instead of active

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.ts
VIH-11421
enable local mute toggle when countdown is complete or participant is in a private consultation
=> VIH-11421 enable local mute toggle when countdown is complete or participant is in a private consultation

VideoWeb/VideoWeb.Common/Enums/Supplier.cs, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json, charts/vh-video-web/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-11357
=> VIH-11357 Add supplier stub
