hmcts/vh-video-web

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.ts

[VIH-4134](https://tools.hmcts.net/jira/browse/VIH-4134)
Fix bug when call participant does not appear due to incorrect time check
```
[ ] Yes
[x] No
```

Bugfix: disable private consultation when hearing is about to start

---

VideoWeb/VideoWeb/ClientApp/src/app/app.component.html
VideoWeb/VideoWeb/ClientApp/src/app/shared/beta-banner/beta-banner.component.ts

N/A
Display the beta banner after being authenticated to avoid attempting to connecting to eventhub prematurely.
```
[ ] Yes
[x] No
```

Only show banner after user is authenticated

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.ts

[VIH-4134](https://tools.hmcts.net/jira/browse/VIH-4134)
Close modals when consultation begins
```
[ ] Yes
[x] No
```

Close 'connecting...' modal when consultation begins

---

VideoWeb/VideoWeb/ClientApp/src/app/app.component.html
VideoWeb/VideoWeb/ClientApp/src/app/app.component.ts

[VIH-4886](https://tools.hmcts.net/jira/browse/VIH-4886)
Only make api calls after user is authenticated
```
[ ] Yes
[x] No
```

do not attempt profile check  if user is not authenticated

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-hearing-page/judge-hearing-page.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-hearing-page/judge-hearing-page.component.ts

[VIH-4700](https://tools.hmcts.net/jira/browse/VIH-4700)
Provide origin of iframe instead of wildcard
```
[ ] Yes
[x] No
```

provide origin host in allow rather than wildcard

---

VideoWeb/VideoWeb.AcceptanceTests/Steps/QueueSubscriberSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj

[VIH-4920](https://tools.hmcts.net/jira/browse/VIH-4920)
Updated packages with security issues
```
[ ] Yes
[x] No
```

Update vulnerable packages

---

VideoWeb/VideoWeb/ClientApp/src/styles.scss

[VIH-4917](https://tools.hmcts.net/jira/browse/VIH-4917)
Make modal background transparent
```
[ ] Yes
[ ] No
```

make modal background 100% transparent

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.ts

[VIH-4919](https://tools.hmcts.net/jira/browse/VIH-4919)
Display rejected modal when consultation request times out
```
[ ] Yes
[x] No
```

display reject modal when consultation request times out

---

VideoWeb/Testing.Common/Helpers/DateFormats.cs
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html

[VIH-4923](https://tools.hmcts.net/jira/browse/VIH-4923)
Remove am/pm from 24 hour clocks
```
[ ] Yes
[x] No
```

remove ante and post meridium from waiting room since time is 24 hours

---

VideoWeb/VideoWeb/ClientApp/package-lock.json
VideoWeb/VideoWeb/ClientApp/package.json
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.ts
VideoWeb/VideoWeb/ClientApp/src/index.html

[VIH-4927](https://tools.hmcts.net/jira/browse/VIH-4927)
removed duplicate id
```
[ ] Yes
[x] No
```

remove duplicate id

---

VideoWeb/VideoWeb.AcceptanceTests/Features/CameraWorking.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/MicrophoneWorking.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/SeeAndHearVideo.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/SwitchOnCamAndMic.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/WaitingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/WaitingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ProgressionSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs

Fixes for broken overnight tests
```
[ ] Yes
[X] No
```

Added fixes for tests

---

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-self-test/participant-self-test.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/security/logout/logout.component.html
VideoWeb/VideoWeb/ClientApp/src/app/security/logout/logout.component.ts

retrieved conference id for participant self test screen.
```
[ ] Yes
[x] No
```

Changed text for logout screen

---

VideoWeb/Testing.Common/Configuration/BookingsConfigLoader.cs
VideoWeb/VideoWeb.AcceptanceTests/Builders/ExecuteEventBuilder.cs
VideoWeb/VideoWeb.AcceptanceTests/Contexts/TestContext.cs
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingStatus.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/Login.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/Logout.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/MicrophoneWorking.feature
VideoWeb/VideoWeb.AcceptanceTests/Hooks/BrowserHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/CommonPages.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ErrorSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsStatusSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/LogoutSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ParticipantStatusSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/HearingStatus/ClosedStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/HearingStatus/DelayedStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/HearingStatus/IHearingStatusStrategies.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/HearingStatus/InSessionStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/HearingStatus/NotStartedStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/HearingStatus/PausedStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/HearingStatus/SuspendedStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/ParticipantStatus/AvailableStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/ParticipantStatus/DisconnectedStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/ParticipantStatus/IParticipantStatusStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/ParticipantStatus/InConsultationStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/ParticipantStatus/InHearingStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/ParticipantStatus/JoiningStrategy.cs
VideoWeb/VideoWeb.Common/Configuration/AzureAdConfiguration.cs

- fixes for tests
```
[ ] Yes
[X] No
```

Added more fixes for tests

---

VideoWeb/VideoWeb/ClientApp/src/scripts/Heartbeat.js

no jira
update the heartbeat.js file
```
[ ] Yes
[x] No
```

updated to the new Heartbeat.js file.

---

VideoWeb/VideoWeb/ClientApp/src/scripts/Heartbeat.js

No Jira.
Updated with the latest file.
```
[ ] Yes
[x] No
```

updated with latest hearbeat.js file.

---

VideoWeb/VideoWeb.UnitTests/Controllers/ProfileController/GetUserProfileTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/TasksController/CompleteTaskTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/TasksController/GetTasksTests.cs
VideoWeb/VideoWeb/Controllers/ConferencesController.cs
VideoWeb/VideoWeb/Controllers/ConsultationsController.cs
VideoWeb/VideoWeb/Controllers/MediaEventController.cs
VideoWeb/VideoWeb/Controllers/ParticipantsController.cs
VideoWeb/VideoWeb/Controllers/ProfilesController.cs
VideoWeb/VideoWeb/Controllers/TasksController.cs
VideoWeb/VideoWeb/Controllers/VideoEventsController.cs

[VIH-4928](https://tools.hmcts.net/jira/browse/VIH-4928)
Remove stack trace from response code
```
[ ] Yes
[x] No
```

Remove stack trace from response

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts

updated token string with bearer

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/scripts/Heartbeat.js

updated heartbeat.js (from kinly)

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.ts

[VIH-4864](https://tools.hmcts.net/jira/browse/VIH-4864)
- After 30 seconds, go back (based on platform's history)
```
[ ] Yes
[x] No
```

revert to previous page when on service error page

---

VideoWeb/VideoWeb.AcceptanceTests/Features/Errors.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs

- Test fixes
- Removed a test as the scenario is now unreproducable with automation
```
[ ] Yes
[X] No
```

More test fixes

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingStatus.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/Page.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/PracticeVideoHearingSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ProgressionSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Users/UserBrowser.cs

More fixes for tests failing on sauce labs
```
[ ] Yes
[X] No
```

Fixes for more tests

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-hearing-list/vho-hearing-list.component.scss

https://tools.hmcts.net/jira/browse/VIH-4963
style fix.
```
[ ] Yes
[x] No
```

style fix for closed hearing.

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.html

[VIH-4705](https://tools.hmcts.net/jira/browse/VIH-4705)
Reduce width of self test video to 65%
```
[ ] Yes
[x] No
```

Resize self test video so self view and change device is visisble

---

VideoWeb/VideoWeb.AcceptanceTests/Hooks/BrowserHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsStatusSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/appsettings.json

To attempt to fix issues on the build pipelines with AC test secrets
```
[ ] Yes
[X] No
```

Updated test appsettings

---

VideoWeb/VideoWeb/ClientApp/src/scripts/Heartbeat.js

No Jira
updated heartbeat.js file from kinly.
```
[ ] Yes
[x] No
```

update heatbeat.js (file from kinly)

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingAlerts.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/ParticipantStatus.feature
VideoWeb/VideoWeb.AcceptanceTests/Journeys/VhoJourney.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/AdminPanelPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/Page.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/VhoHearingListPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingAlertsSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ParticipantStatusSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/VhoHearingListSteps.cs

Fixes for locators on iframe and hearing status tests
```
[ ] Yes
[X] No
```

Fixes to hearing status tests and removed unnecessary iframe logic

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/ParticipantStatus.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/PracticeVideoHearing.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/HearingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/VhoHearingListPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/WaitingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/CommonSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingAlertsSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ParticipantStatusSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/PracticeVideoHearingSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/PrivateConsultationSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/VhoHearingListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs

Lots more fixes for acceptance tests including expanding existing tests.
```
[ ] Yes
[X] No
```

More fixes for automation tests

---

VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs

Added a wait for the pause tests to account for transfers of participants to improve stability
```
[ ] Yes
[X] No
```

Added wait

---

VideoWeb/VideoWeb/ClientApp/src/scripts/pexrtc.js

updated pexrtc scrpt

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html

[VIH-4625](https://tools.hmcts.net/jira/browse/VIH-4625)
- Update content to soft waiting room.
```
[ ] Yes
[x] No
```

update soft waiting room content

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.ts

se remove this line and everything above and fill the following sections:
[VIH-5016](https://tools.hmcts.net/jira/browse/VIH-5016)
Only display vho call alert when participant is available
```
[ ] Yes
[x] No
```

only display VHO consultation call message if participant is available

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/WaitingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs

Fixes for 2 failing tests on saucelabs. 1 is an update to the UI, and the other is to extend the pauses as tests run slow on saucelabs
```
[ ] Yes
[X] No
```

Added fixes for 2 failing tests.

---

VideoWeb/VideoWeb.AcceptanceTests/Assertions/VideoIsPlaying.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/PrivateConsultationSteps.cs

- Added delays for saucelabs private consultations
```
[ ] Yes
[X] No
```

Added delays for saucelabs private consultations

---

VideoWeb/VideoWeb.AcceptanceTests/Helpers/SeleniumEnvironment.cs

- Added capabilities to run video-web tests on saucelabs
```
[ ] Yes
[X] No
```

Added capabilities to run video-web tests on saucelabs

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/AdminPanelPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/HearingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/WaitingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/PrivateConsultationSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/VideoHearingsOfficerCallSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs

- Fixes for overnight tests
- Expanded hearing room tests
```
[ ] Yes
[X] No
```

Testfix/Fixes 

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Helpers/SeleniumEnvironment.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs

- Attempts to get the 4 person hearing test running reliably on saucelabs
```
[ ] Yes
[X] No
```

Changes to the 4 person hearing test

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature
VideoWeb/VideoWeb.AcceptanceTests/Helpers/SeleniumEnvironment.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs

- Attempt to fix saucelabs in overnight runs
- Added a failure to the VHO test if there are more than 1 other hearing present
```
[ ] Yes
[X] No
```

Added fix for Firefox on saucelabs

---

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-hearings/hearing-list-table.component.html

https://tools.hmcts.net/jira/browse/VIH-5101
updated alt text for the input element.
```
[ ] Yes
[x] No
```

updated the alt text for the input element.

---

VideoWeb/VideoWeb/Mappings/CallbackEventMapper.cs

Suspended event contains nullable participant id for Technical help

---

VideoWeb/Testing.Common/Helpers/VideoWebUriFactory.cs
VideoWeb/VideoWeb.AcceptanceTests/Builders/ExecuteEventBuilder.cs
VideoWeb/VideoWeb.AcceptanceTests/Builders/ExecuteRequestBuilder.cs
VideoWeb/VideoWeb.AcceptanceTests/Contexts/TestContext.cs
VideoWeb/VideoWeb.AcceptanceTests/Helpers/GetHearingRow.cs
VideoWeb/VideoWeb.AcceptanceTests/Properties/AssemblyInfo.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingAlertsSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/VhoHearingListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/HearingStatus/ClosedStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/HearingStatus/InSessionStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/HearingStatus/NotStartedStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/HearingStatus/PausedStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/HearingStatus/SuspendedStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/ParticipantStatus/AvailableStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/ParticipantStatus/DisconnectedStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/ParticipantStatus/InConsultationStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/ParticipantStatus/InHearingStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/ParticipantStatus/JoiningStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/ConsultationHelper.cs

- Fixed some of the tests for the moved endpoint
- Upgraded some of the NuGet packages
- Fixed some of the warnings
```
[ ] Yes
[X] No
```

Moved the event endpoint to the video web

---

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-hearings/hearing-list-table.component.html

https://tools.hmcts.net/jira/browse/VIH-5101
aria-label added.
```
[ ] Yes
[x] No
```

updated to aria-label as per feedback.

---

VideoWeb/VideoWeb/ClientApp/src/app/app.component.html
VideoWeb/VideoWeb/ClientApp/src/app/app.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/app.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/app.component.ts

https://tools.hmcts.net/jira/browse/VIH-5099
added skip to content
```
[ ] Yes
[x] No
```

added skip to content

---

VideoWeb/VideoWeb.UnitTests/Controllers/VideoEventController/SendHearingEventTests.cs
VideoWeb/VideoWeb/ConferenceCache.cs
VideoWeb/VideoWeb/Controllers/ConferencesController.cs
VideoWeb/VideoWeb/Controllers/VideoEventsController.cs

Loading conference into cache if its missing in the cache

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingAlertsSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Users/UserBrowser.cs

- Fix for a test - Window Title has changed
- Removed a useless test
```
[ ] Yes
[X] No
```

Fix for a test - Window Title has changed

---

VideoWeb/VideoWeb.AcceptanceTests/Builders/ExecuteRequestBuilder.cs
VideoWeb/VideoWeb.AcceptanceTests/Contexts/TestContext.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/BrowserHooks.cs

- Attempt to fix some of the failing media alert fails on the overnight run
```
[ ] Yes
[X] No
```

Attempt to fix failing self test alert tests on AAT

---

VideoWeb/VideoWeb/Startup.cs

removedduplicate evet hub registration

---

VideoWeb/VideoWeb/ClientApp/src/app/services/logging/loggers/console-logger.ts

No Jira
Commented out the console logs for events with email id.
```
[ ] Yes
[x] No
```

commented out console log of emails

---

VideoWeb/VideoWeb/Startup.cs

Disabled swagger url for production environmet

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature

-Ignoring a failing test from the overnight runs. The test runs too slowly on the build server as it opens 5 browsers with attached browsers to run the test and grinds it to a halt. 
```
[ ] Yes
[X] No
```

Ignoring a long failing test

---

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/camera-check/camera-check.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/declaration/declaration.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/hearing-rules/hearing-rules.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-table.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/microphone-check/microphone-check.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-hearings/hearing-list-table.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/video-check/video-check.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-hearing-list/vho-hearing-list.component.html

No Jira
updated button type
```
[ ] Yes
[x] No
```

updated button type

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingAlerts.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/WaitingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingAlertsSteps.cs

- Attempt to fix an issue where the self test is unauthorised on the env but not locally
```
[ ] Yes
[ ] No
```

Attempt to fix self test fails

---

VideoWeb/VideoWeb.AcceptanceTests/Helpers/SeleniumEnvironment.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.UnitTests/.config/dotnet-tools.json
VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj

- Added tools to use in the pipelines for mutation and security testing
- Upgraded plugins to newer versions
- Updated the version of Chromedriver for local and Saucelab builds
```
[ ] Yes
[X] No
```

Added extensions for tools and upgraded framework

---

VideoWeb/VideoWeb/ClientApp/src/app/services/device-type.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/unsupported-browser/unsupported-browser.component.ts

N/A
Removed Edge from the supported browser list
```
[ ] Yes
[x ] No
```

Removed Edge from the supported browser list

---

VideoWeb/VideoWeb.AcceptanceTests/Pages/PracticeVideoHearingPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/PracticeVideoHearingSteps.cs

- Changed the text for the clerk equipment not working screen
```
[ ] Yes
[X] No
```

Changed the text for updated Clerk Equipment Not Working screen

---

VideoWeb/VideoWeb/ClientApp/src/app/services/device-type.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/unsupported-browser/unsupported-browser.component.ts

N/A
Added Edge to the supported browser list
```
[ ] Yes
[ ] No
```

Added support for Edge

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts

No Jira
Prevent raising failed self test if test was completed.
```
[ ] Yes
[x] No
```

raise failed test if bad or incomplete score.

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/accessibility/accessibility.component.html

VIH-5023
style changes
```
[ ] Yes
[x] No
```

updated styles to highlight yellow on tabbing.

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HeaderFooter.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/CommonPages.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/Page.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/CommonSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/VideoHearingsOfficerCallSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Users/UserBrowser.cs

https://tools.hmcts.net/jira/browse/VIH-4090
https://tools.hmcts.net/jira/browse/VIH-4701
https://tools.hmcts.net/jira/browse/VIH-5023
Added AC tests
```
[ ] Yes
[X] No
```

Added tests for the header and footer

---

VideoWeb/VideoWeb.AcceptanceTests/Steps/PrivateConsultationSteps.cs

- Attempt to fix the 1 failing test on sauce labs from last nights run
```
[ ] Yes
[X] No
```

Extended the timeout for connecting people in saucelabs

---

VideoWeb/VideoWeb/ClientApp/src/app/services/user-media.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/utility/media-object.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts
VideoWeb/VideoWeb/VideoWeb.csproj

https://tools.hmcts.net/jira/browse/VIH-4976
Fix for the bug whereby a participant on MS Edge is not able to hear other participants and judge
```
[x ] Yes
[ ] No
```

Fix for Edge issue

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts

No Jira
update to not alert vho for incomplete self tests
```
[ ] Yes
[x] No
```

update to not alert VHO for judge incomplete self test.

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HeaderFooter.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/CommonLocators.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/Page.cs

- Added extra tests for the open government licence links
```
[ ] Yes
[X] No
```

Added tests for the open government licence

---

VideoWeb/VideoWeb/ClientApp/src/app/home/home.component.ts

VIH-5235
updated unauth page redirect logic
```
[ ] Yes
[x] No
```

changed unauth page redirect logic

---

VideoWeb/VideoWeb.Common/Security/HashGen/CustomTokenSettings.cs
VideoWeb/VideoWeb/Controllers/TokenController.cs
VideoWeb/VideoWeb/appsettings.json

Added config settings for custom token and hash expiry

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/analogue-clock/analogue-clock.component.ts

https://tools.hmcts.net/jira/browse/VIH-4566
initialise time on the analogue clock
```
[ ] Yes
[x] No
```

fix to set the time to current utc time on Init

---

azure-pipelines.yml

build on pushes to release/*
```
[X] Yes
[ ] No
```

build on pushes to release/*

---

VideoWeb/VideoWeb.AcceptanceTests/Features/Errors.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/WaitingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Helpers/SauceLabDrivers/ChromeSauceLabsDriver.cs
VideoWeb/VideoWeb.AcceptanceTests/Helpers/SauceLabDrivers/EdgeSauceLabsDriver.cs
VideoWeb/VideoWeb.AcceptanceTests/Helpers/SauceLabDrivers/FirefoxSauceLabsDriver.cs
VideoWeb/VideoWeb.AcceptanceTests/Helpers/SauceLabDrivers/InternetExplorerSauceLabsDriver.cs
VideoWeb/VideoWeb.AcceptanceTests/Helpers/SauceLabDrivers/SafariSauceLabsDriver.cs
VideoWeb/VideoWeb.AcceptanceTests/Helpers/SauceLabDrivers/SaucelabsDriver.cs
VideoWeb/VideoWeb.AcceptanceTests/Helpers/SeleniumEnvironment.cs
VideoWeb/VideoWeb.AcceptanceTests/Helpers/TargetBrowser.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/ErrorPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/Page.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ErrorSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ProgressionSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Users/UserBrowser.cs

- Attempt to get video web tests running on Firefox on Saucelabs
```
[ ] Yes
[X] No
```

Cross Browser Testing

---

VideoWeb/VideoWeb/ClientApp/src/index.html

https://tools.hmcts.net/jira/browse/VIH-5242
removed Edge image for IE11
```
[ ] Yes
[x] No
```

removed Edge image for IE11

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/WaitingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Helpers/Drivers/SafariDriverStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/CommonPages.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/CommonSteps.cs
VideoWeb/VideoWeb/ClientApp/src/app/shared/contact-information.ts

https://tools.hmcts.net/jira/browse/VIH-5312
updated contact us email address.
```
[ ] Yes
[x] No
```

updated: contact us email address.

---

VideoWeb/VideoWeb.AcceptanceTests/Features/Errors.feature
VideoWeb/VideoWeb.AcceptanceTests/Helpers/Drivers/EdgeDriverStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/CommonSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ErrorSteps.cs

- Added fixes for tests failing locally and on sauce labs
```
[ ] Yes
[X] No
```

Fixes for unsupported browser tests

---

VideoWeb/Testing.Common/Configuration/BookingsConfigLoader.cs
VideoWeb/Testing.Common/Configuration/HearingsServiceConfiguration.cs
VideoWeb/VideoWeb.AcceptanceTests/Contexts/TestContext.cs
VideoWeb/VideoWeb.AcceptanceTests/Helpers/Drivers/SafariDriverStrategy.cs
VideoWeb/VideoWeb.AcceptanceTests/Helpers/SeleniumEnvironment.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/BrowserHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/appsettings.json
VideoWeb/VideoWeb.Common/Configuration/AzureAdConfiguration.cs

- Cleaned up old unused config
- Removed the unnecessary check on the User-Api
- Fix for the Safari remote web driver issues
```
[ ] Yes
[X] No
```

Config cleanup for acceptance test project

---

VideoWeb/VideoWeb.AcceptanceTests/Features/Errors.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/CommonPages.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ErrorSteps.cs

- Merged the tags for the unsupported browser tests to make it easier to run on the nightly builds
- Added a fix for a failing test
```
[ ] Yes
[X] No
```

Merge for the unsupported browser test

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/header/header.component.html

https://tools.hmcts.net/jira/browse/VIH-5354
Changed header font size
```
[ ] Yes
[ X] No
```

Changed header font size to comply with standard

---

VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs
VideoWeb/VideoWeb/ClientApp/package-lock.json
VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts

NI JIRA
update to logging (exception)
```
[ ] Yes
[x] No
```

updated : logging for event hub client

---

VideoWeb/VideoWeb.Common/Configuration/AzureAdConfiguration.cs
VideoWeb/VideoWeb/ConfigureServicesExtensions.cs
VideoWeb/VideoWeb/Startup.cs
VideoWeb/VideoWeb/VideoWeb.csproj
azure-pipelines.yml

n/a
Reverses the changes made for SignalR and settings
Original PR : https://github.com/hmcts/vh-video-web/pull/287
```
[x ] Yes
[ ] No
```

Reverses the changes made for SignalR and settings

---

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-table.component.html

https://tools.hmcts.net/jira/browse/VIH-5341
Removed header 'Status' from the judge list
```
[X ] Yes
[ ] No
```

Remove the header for Status column

---

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/camera-check/camera-check.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/declaration/declaration.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/equipment-check/equipment-check.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/hearing-rules/hearing-rules.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/independent-self-test/independent-self-test.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/introduction/introduction.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-self-test/judge-self-test.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/microphone-check/microphone-check.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/switch-on-camera-microphone/switch-on-camera-microphone.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/video-check/video-check.component.html
VideoWeb/VideoWeb/ClientApp/src/app/shared/accessibility/accessibility.component.html
VideoWeb/VideoWeb/ClientApp/src/app/shared/equipment-problem/equipment-problem.component.html
VideoWeb/VideoWeb/ClientApp/src/app/shared/signon-a-computer/signon-a-computer.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html

https://tools.hmcts.net/jira/browse/VIH-5351
updated : h1 titles css style to xl as per GDS guidelines.
```
[ ] Yes
[x] No
```

VIH-5351: Standardise h1 heading size across All Apps

---

VideoWeb/VideoWeb.AcceptanceTests/Features/Accessibility.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/PracticeVideoHearing.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/PrivateConsultation.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature
VideoWeb/VideoWeb.AcceptanceTests/Journeys/Journey.cs
VideoWeb/VideoWeb.AcceptanceTests/Journeys/SelfTestJourney.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ProgressionSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-hearings/participant-hearings.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-hearings/participant-hearings.component.ts

https://tools.hmcts.net/jira/browse/VIH-5386
Changes related to Individual accesses Tech Test from Video Web
```
[ ] Yes
[ X] No
```

VIH-5386-IndividualAccessesTechTestFromVideoWeb

---

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-list.component.html

https://tools.hmcts.net/jira/browse/VIH-5434
added the check equipment button for the judge/clerk page when no hearings are scheduled for the day.
```
[ ] Yes
[x] No
```

VIH-5434: Judge self test not available when no hearings are scheduled for the day

---

README.md
VideoWeb/VideoWeb/ClientApp/src/scripts/Heartbeat.js

https://tools.hmcts.net/jira/browse/VIH-5408
Updated Heartbeat JS
```
[X ] Yes
[ ] No
```

Uploaded new Heartbeat JS

---

VideoWeb/VideoWeb/ClientApp/src/scripts/Heartbeat.js

https://tools.hmcts.net/jira/browse/VIH-5502
update to the heartbeat.js file.
```
[ ] Yes
[x] No
```

VIH-5502:Update Heartbeat.js

---

VideoWeb/VideoWeb/Startup.cs

n/a
* Fix eventhub setup that broken during 3.1 updgrade
```
[ ] Yes
[x] No
```

configure eventhub with authorisation

---

VideoWeb/VideoWeb.Contract/Responses/ConferenceForUserResponse.cs
VideoWeb/VideoWeb.Contract/Responses/TaskUserResponse.cs
VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb.UnitTests/Mappings/ConferenceForUserResponseMapperTests.cs
VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-hearing-list/vho-hearing-list.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-herings-filter/vho-hearings-filter.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-herings-filter/vho-hearings-filter.component.scss
VideoWeb/VideoWeb/Mappings/ConferenceForUserResponseMapper.cs

https://tools.hmcts.net/jira/browse/VIH-5503
Filter conferences for VH officer by tasks
```
[X ] Yes
[ ] No
```

VIH-5503 tasks filter for conferences

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participants-status-model.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-status/participant-status.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-status/participant-status.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-status/participant-status.component.ts

https://tools.hmcts.net/jira/browse/VIH-5431
Display judge status by taken in account the judge status in the another hearings
```
[ X] Yes
[ ] No
```

VIH-5431 display judge status

---

VideoWeb/VideoWeb.AcceptanceTests/Steps/SwitchOnCamAndMicSteps.cs
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/camera-check/camera-check.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/hearing-rules/hearing-rules.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/hearing-rules/hearing-rules.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/hearing-rules/hearing-rules.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/introduction/introduction.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/microphone-check/microphone-check.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-self-test/participant-self-test.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/switch-on-camera-microphone/switch-on-camera-microphone.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/video-check/video-check.component.html
VideoWeb/VideoWeb/ClientApp/src/app/shared/contact-us-folding/contact-us-folding.component.html

https://tools.hmcts.net/jira/browse/VIH-5424
```
[ ] Yes
[ ] No
```

VIH-5424: Finish other changes

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/SwitchOnCamAndMic.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/CommonPages.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/HearingListPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/CommonSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/QueueSubscriberSteps.cs

- Fixed tests that broke because of the text changes in contact details
- Fixed tests where the 'No hearings' message has changed
- Fixed tests which had a bug due to changes to the queue subscriber tests
```
[ ] Yes
[X] No
```

Fixed lots of tests that had on screen text changes

---

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/hearing-rules/hearing-rules.component.html

https://tools.hmcts.net/jira/browse/VIH-5424
```
[ ] Yes
[ ] No
```

VIH-5424: Rules bullet point text change

---

VideoWeb/VideoWeb.AcceptanceTests/Configuration/VideoWebTokens.cs
VideoWeb/VideoWeb.AcceptanceTests/Configuration/VideoWebVhServicesConfig.cs
VideoWeb/VideoWeb.AcceptanceTests/Features/PracticeVideoHearing.feature
VideoWeb/VideoWeb.AcceptanceTests/Hooks/ConfigHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/RegisterApisHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/nuget.config
azure-pipelines.yml

[VIH-5482](https://tools.hmcts.net/jira/browse/VIH-5482)
* Bug Fixes
```
[ ] Yes
[x] No
```

Update config settings for video web api url

---

VideoWeb/VideoWeb.AcceptanceTests/Features/CameraWorking.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/MicrophoneWorking.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/PracticeVideoHearing.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/SeeAndHearVideo.feature
VideoWeb/VideoWeb.AcceptanceTests/Helpers/ParticipantInformation.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/EquipmentWorkingPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/PracticeVideoHearingPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/SwitchOnCamAndMicPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/EquipmentWorkingSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/PracticeVideoHearingSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/SwitchOnCamAndMicSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj

https://tools.hmcts.net/jira/browse/VIH-5548
- Firefox driver does not emulate multiple cameras, so the change camera and microphone link does not appear
- The Firefox tests had an issue where clicking the continue button immediately after doing the self test meant the button was not being clicked. 
- Did some general tidying up removing Javascript scrolls to the function that already exists in the NuGet package
- Updated the NuGet package
```
[ ] Yes
[X] No
```

Fixes for firefox tests

---

VideoWeb/VideoWeb.AcceptanceTests/Hooks/ConfigHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/RegisterApisHooks.cs
VideoWeb/VideoWeb.Common/Security/BaseServiceTokenHandler.cs

[VIH-5482](https://tools.hmcts.net/jira/browse/VIH-5482)
Fix the setup for callback bearer token
```
[ ] Yes
[x] No
```

Generate a token for the callback scheme

---

VideoWeb/VideoWeb.AcceptanceTests/Features/Accessibility.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/camera-check/camera-check.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/microphone-check/microphone-check.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/video-check/video-check.component.ts

https://tools.hmcts.net/jira/browse/VIH-5233
- commented out the VHO acceptance test.Testing.Common.Helpers
- removed the logging for case_name in camera check page
```
[ ] Yes
[x] No
```

VIH-5233:[Video Web | Accessibility] All pages should be contained within video-check.component

---

VideoWeb/VideoWeb.UnitTests/Controllers/ParticipantController/GetTestCallResultForParticipantTests.cs
VideoWeb/VideoWeb.UnitTests/Mappings/EventTypeReasonMapperTest.cs
VideoWeb/VideoWeb/Mappings/EventTypeReasonMapper.cs

https://tools.hmcts.net/jira/browse/VIH-5569
To get reason for participant in switch statement was invalid event type,
it was changed to ParticipantJoining
```
[X ] Yes
[ ] No
```

VIH-5569 Fix Change status to ParticipantJoining

---

VideoWeb/VideoWeb.AcceptanceTests/Features/Introduction.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/ParticipantStatus.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/WaitingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/ParticipantStatusSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj

- Improved readability of status tests
- Updated NuGet package to fix a potential 'Not Run' issue
- Updated name of test run for saucelabs
```
[ ] Yes
[X] No
```

improved readbility of status tests

---

VideoWeb/VideoWeb.AcceptanceTests/Hooks/RemoveDataHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj

- Fixed an issue where closed conferences are not being cleaned
```
[ ] Yes
[X] No
```

Fixed delete conferences

---

VideoWeb/VideoWeb.AcceptanceTests/Features/Accessibility.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/CommonSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj

- Fixed accessibility tests
```
[ ] Yes
[X] No
```

VIH-5557 Added fixes for the remaining accessibility failures

---

VideoWeb/VideoWeb.AcceptanceTests/Api/PollForParticipantStatus.cs
VideoWeb/VideoWeb.AcceptanceTests/Data/DateFormats.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingAlertsSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb.UnitTests/Builders/ParticipantDetailsResponseBuilder.cs
VideoWeb/VideoWeb.UnitTests/Mappings/ParticipantResponseMapperTests.cs
VideoWeb/VideoWeb/Controllers/ConferencesController.cs
VideoWeb/VideoWeb/Mappings/ParticipantResponseMapper.cs

- Updates to fix Participant Status Error
```
[ ] Yes
[X] No
```

Updates to fix Participant Status Error

---

CODEOWNERS
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/WaitingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/PrivateConsultationSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/VideoHearingsOfficerCallSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.Services.Generator/video-api.nswag

https://tools.hmcts.net/jira/browse/VIH-5548
- Added fixes for tests
- Added a code owners file for GitHub approvals
```
[ ] Yes
[X] No
```

[VIH-5548] Fixes for a range of Firefox tests

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingAlerts.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingStatus.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/ParticipantStatus.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/PrivateConsultation.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/QueueSubscriber.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj

…ved step names
- Some tests created a hearing 30 mins into the future just before midnight, which meant they didn't appear in the UI. 
- Improved the step names of the data setup steps
```
[ ] Yes
[X] No
```

Check for hearing start times

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/BrowserSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/CommonSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/DeclarationSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/EquipmentWorkingSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingAlertsSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsStatusSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/LoginSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ParticipantStatusSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/PracticeVideoHearingSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/PrivateConsultationSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/RulesSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/SwitchOnCamAndMicSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/VhoHearingListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/VideoHearingsOfficerCallSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-chat/judge-chat.component.html

https://tools.hmcts.net/jira/browse/VIH-5549
- Added fixes for Safari
- Fixed an accessibility issue where an image element was missing an alt tag
```
[ ] Yes
[X] No
```

[VIH-5549] Fixes for failing Safari tests

---

VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingAlertsSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj

- Click method has been updated to work on Safari, which has a knockon effect to the alert tests
```
[ ] Yes
[X] No
```

[VIH-5255] Fix for alerts

---

VideoWeb/VideoWeb.AcceptanceTests/Assertions/AssertChatMessage.cs
VideoWeb/VideoWeb.AcceptanceTests/Data/Test.cs
VideoWeb/VideoWeb.AcceptanceTests/Features/Accessibility.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingAlerts.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/InstantMessaging.feature
VideoWeb/VideoWeb.AcceptanceTests/Hooks/ConfigHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/VhoHearingListPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsStatusSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/InstantMessagingSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/PracticeVideoHearingSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj

- More fixes for overnight tests
```
[ ] Yes
[X] No
```

[VIH-5255] fixes for overnights 27th feb

---

VideoWeb/VideoWeb/ClientApp/src/app/services/api/video-web-service.interface.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/api/video-web.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/MockLogger.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/MockVideoService.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-hearing-page/judge-hearing-page.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-hearing-page/judge-hearing-page.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.spec.ts

[VIH-5644](https://tools.hmcts.net/jira/browse/VIH-5644)
```
[ ] Yes
[x] No
```

added tests to judge conference status change

---

VideoWeb/VideoWeb.AcceptanceTests/Hooks/DriverHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj

- An attempt to see if killing any leftover processes will fix the overnight VHO call test
```
[ ] Yes
[X] No
```

VIH-5255 Kill any browser processes from any browser pre and post test

---

VideoWeb/VideoWeb.AcceptanceTests/Data/TestData/DefaultDataManager.cs
VideoWeb/VideoWeb.AcceptanceTests/Features/Accessibility.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/InstantMessaging.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature
VideoWeb/VideoWeb.AcceptanceTests/Hooks/ConfigHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/HealthcheckHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/HooksSequence.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/ScenarioHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/VideoHearingsOfficerCallSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj

- Added the ability to exclude certain browsers from specific tests
```
[ ] Yes
[X] No
```

[VIH-5255] Added the ability to exclude certain browsers from specific tests

---

VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html

[VIH-5665](https://tools.hmcts.net/jira/browse/VIH-5665)
* display correct text colour on participant waiting on clock - paused status
```
[ ] Yes
[x] No
```

fix colour

---

VideoWeb/VideoWeb.AcceptanceTests/Hooks/DriverHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/HooksSequence.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj

- A fix for the issue where ignored tests were not being reported correctly on sauce labs and having a knock on effect to subsequent tests
```
[ ] Yes
[X] No
```

Fix for the ignored tests on the overnight run

---

.githooks/pre-commit
.githooks/prepare-commit-msg
README.md

https://tools.hmcts.net/jira/browse/VIH-5605
Added files for git hooks to validate branch name and commit name
```
[X ] Yes
[ ] No
```

feature/VIH-5605 : added git hooks to validate branch name and commit

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/header/header.component.html

https://tools.hmcts.net/jira/browse/VIH-5675
Removed blue colour on hover the header.
```
[X ] Yes
[ ] No
```

feature/VIH-5675 : fix header on hover has blue color

---

VideoWeb/VideoWeb/ClientApp/src/scripts/pexrtc.js

https://tools.hmcts.net/jira/browse/VIH-5667
- updated the pexip.js to v23
```
[ ] Yes
[x] No
```

VIH-5667 : Regression_Test_Pexip_v.23

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-hearing-list/vho-hearing-list.component.html

https://tools.hmcts.net/jira/browse/VIH-5691
Html change to fix Network status icons alignment issue
```
[ ] Yes
[ X] No
```

VIH-5691 Network Status Icons misaligment issue fix

---

README.md
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-network-status/participant-network-status.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-network-status/participant-network-status.component.ts

https://tools.hmcts.net/jira/browse/VIH-5700
Fixed Network Bad signal Icon Issue
```
[ ] Yes
[ X] No
```

VIH-4700 Network status badsignal icon issue

---

VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs
VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferenceByIdTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForJudgeTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForVHOfficerTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/HandleConsultationRequestTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/LeavePrivateConsultationTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/RespondToAdminConsultationRequestTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/HealthController/HealthTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/InstantMessageController/GetConferenceInstantMessageHistoryTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/MediaEventController/AddMediaEventToConferenceTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/MediaEventController/AddSelfTestFailureEventToConferenceTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/ParticipantController/GetTestCallResultForParticipantTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/ProfileController/GetProfileByUsernameTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/ProfileController/GetUserProfileTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/TasksController/CompleteTaskTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/TasksController/GetTasksTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/VenueControllerTest.cs
VideoWeb/VideoWeb.UnitTests/Controllers/VideoEventController/SendHearingEventTests.cs
VideoWeb/VideoWeb/Controllers/ConferencesController.cs
VideoWeb/VideoWeb/Controllers/ConsultationsController.cs
VideoWeb/VideoWeb/Controllers/HealthCheckController.cs
VideoWeb/VideoWeb/Controllers/InstantMessagesController.cs
VideoWeb/VideoWeb/Controllers/MediaEventController.cs
VideoWeb/VideoWeb/Controllers/ParticipantsController.cs
VideoWeb/VideoWeb/Controllers/ProfilesController.cs
VideoWeb/VideoWeb/Controllers/TasksController.cs
VideoWeb/VideoWeb/Controllers/VenuesController.cs
VideoWeb/VideoWeb/Controllers/VideoEventsController.cs

https://tools.hmcts.net/jira/browse/VIH-5696
```
[ ] Yes
[ ] No
```

VIH-5696: Rename async, Task.WaitAll()

---

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-list.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-list.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/conference-helper.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/conference-helper.ts

[VIH-5709](https://tools.hmcts.net/jira/browse/VIH-5709)
* Subcribe to hearing status change for judge hearing list
```
[ ] Yes
[x] No
```

Subcribe to hearing status change for judge hearing list

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-status/participant-status.component.html
VideoWeb/VideoWeb/Startup.cs
VideoWeb/VideoWeb/VideoWeb.csproj

[VIH-5724](https://tools.hmcts.net/jira/browse/VIH-5724)
* show judge display name
```
[ ] Yes
[x] No
```

show judge display name in vho participant list

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/monitoring-graph/monitoring-graph.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/monitoring-graph/monitoring-graph.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/monitoring-graph/monitoring-graph.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/monitoring-graph/monitoring-graph.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/services/models/participant-graph-info.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/services/models/participant-graph-info.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/services/monitor-graph.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/services/monitor-graph.service.ts

https://tools.hmcts.net/jira/browse/VIH-5721
https://tools.hmcts.net/jira/browse/VIH-5701 (just part of task, added representee)
Fixed compare browser version for unsupported browser, fix css for close button, add representee to participant name on the graph.
```
[ X] Yes
[ ] No
```

feature/VIH-5701 : unsupported browser fix, add representee

---

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/abstract/equipment-check-base.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/camera-check/camera-check.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/introduction/introduction.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/introduction/introduction.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/microphone-check/microphone-check.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-hearings/hearing-list-table.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-hearings/hearing-list-table.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-hearings/participant-hearings.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-hearings/participant-hearings.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-hearings/participant-hearings.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/video-check/video-check.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/security/admin.guard.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/security/conference.guard.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/security/judge.guard.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/security/participant.guard.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/api/video-web.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/judge-event.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/models/conference-lite.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/contact-us-folding/contact-us-folding.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/contact-us-folding/contact-us-folding.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/MockLogger.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/tasks-table/tasks-table.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-hearing-page/judge-hearing-page.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.no-conference.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.no-conference.spec.ts
VideoWeb/VideoWeb/ClientApp/src/tsconfig.app.json
VideoWeb/VideoWeb/ClientApp/tslint.json

[VIH-5711](https://tools.hmcts.net/jira/browse/VIH-5711)
* reduce api calls  where possible
```
[ ] Yes
[x] No
```

remove unncessary calls to api

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-herings-filter/vho-hearings-filter.component.html

VIH-5750 
Fix casting resposne to summary model
```
[ ] Yes
[x] No
```

VIH-5750 fix casting issue for filter

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Hooks/DriverHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/HooksSequence.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb/ClientApp/package-lock.json
VideoWeb/VideoWeb/ClientApp/package.json
VideoWeb/VideoWeb/ClientApp/src/app/services/device-type.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/mappers/heartbeat-model-mapper.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/mappers/heartbeat-model-mapper.ts

https://tools.hmcts.net/jira/browse/VIH-5575
- Attempting to get Edge Chromium working on automated tests, to fake the camera and mic
- Enabled a 5 participant hearing tests (un-ignored)
```
[ ] Yes
[X] No
```

VIH-5575 Support for Edge Chromium

---

VideoWeb/VideoWeb/ClientApp/src/app/services/device-type.service.ts

https://tools.hmcts.net/jira/browse/VIH-5575
- Unlock Edge Chromium (add to supported browsers)
```
[ ] Yes
[X] No
```

VIH-5575 Unlock Edge Chromium

---

VideoWeb/VideoWeb.AcceptanceTests/Hooks/DriverHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj

… its running locally
-Added a check to only stop Edge Chromium server if its running locally
```
[ ] Yes
[X] No
```

VIH-5255 Added a check to only stop Edge Chromium server

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs

- Changed the Hearing Room tests to ensure users can always log out. This should make subsequent tests more reliable
```
[ ] Yes
[X] No
```

VIH-5255 Changes to Hearing Room tests

---

VideoWeb/VideoWeb.Common/Caching/ConferenceCache.cs
VideoWeb/VideoWeb.Common/Caching/ConferenceCacheMapper.cs
VideoWeb/VideoWeb.Common/Caching/DistributedConferenceCache.cs
VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj
VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs
VideoWeb/VideoWeb.UnitTests/Hub/EventHubBaseTests.cs
VideoWeb/VideoWeb.UnitTests/Hub/SendMessageTests.cs
VideoWeb/VideoWeb.UnitTests/Mappings/ConferenceCacheMapperTests.cs
VideoWeb/VideoWeb.UnitTests/Mappings/ConferenceResponseMapperTests.cs
VideoWeb/VideoWeb/ConfigureServicesExtensions.cs
VideoWeb/VideoWeb/VideoWeb.csproj

VIH-5730 
* use redis cache
```
[ ] Yes
[x] No
```

VIH-5730 Use redis cache

---

VideoWeb/VideoWeb/ClientApp/src/app/services/api/consultation.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/api/consultation.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/accessibility/accessibility.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-hearing-list/vho-hearing-list.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-hearing-list/vho-hearing-list.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/tsconfig.json

VIH-5765
* fix IM counter for VHO
* enable full template checking during build
```
[ ] Yes
[x] No
```

VIH-5765 apply full template type checking and fix bugs

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature

-Added a fix for the Hearing Room tests
```
[ ] Yes
[X] No
```

VIH-5255 Added a fix for the Hearing Room tests

---

VideoWeb/VideoWeb.AcceptanceTests/Builders/ParticipantsRequestBuilder.cs
VideoWeb/VideoWeb.AcceptanceTests/Builders/UpdateParticipantBuilder.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/WaitingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.AcceptanceTests/useraccounts.json
VideoWeb/VideoWeb.Services/BookingsApiClient.cs
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.ts

VIH-5853 
Update client code in video web in line with Bookings API changes
```
[ ] Yes
[x] No
```

VIH-5853 update booking api client and test setup

---

VideoWeb/VideoWeb.AcceptanceTests/Helpers/TestContext.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/DriverHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/HooksSequence.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/VhoHearingListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.Services/VideoApiClient.cs

- Fixes for sauce labs timezone issues
```
[ ] Yes
[X] No
```

VIH-5255 Fixes for sauce labs timezone issues

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.html

https://tools.hmcts.net/jira/browse/VIH-5383
```
[ ] Yes
[ ] No
```

VIH-5383 Change participant type Solicitor to Representative

---

VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb.UnitTests/Controllers/ParticipantController/UpdateJudgeDisplatNameTests.cs
VideoWeb/VideoWeb/ClientApp/src/app/services/api/video-web-service.interface.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/api/video-web.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/MockVideoService.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.ts
VideoWeb/VideoWeb/Controllers/ParticipantsController.cs

https://tools.hmcts.net/jira/browse/VIH-5454
Change judge display name in waiting room
```
[ X] Yes
[ ] No
```

VIH-5454 change judge display name

---

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-table.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-table.component.ts

https://tools.hmcts.net/jira/browse/VIH-5740
```
[ ] Yes
[ ] No
```

VIH-5740 Display Representing and also show all participants

---

VideoWeb/VideoWeb/Controllers/VideoEventsController.cs

https://tools.hmcts.net/jira/browse/VIH-5671
Fix for a bug that show hearing in session message on judge's waiting room
```
[ ] Yes
[ x] No
```

VIH-5671 Judge Waiting Room Bug Fix

---

VideoWeb/VideoWeb.AcceptanceTests/Features/Accessibility.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature
VideoWeb/VideoWeb.AcceptanceTests/Hooks/ScenarioHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/AdminPanelPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-status/participant-status.component.html

- Added the ability to skip tests on Edge Chromium 
- Skipping all Accessibility tests on any browser other than Chrome
- Added a fix for close on the Hearing Room tests
- Added a fix for the id changes to the participant status table
- Added Ids to the elements in the app
```
[ ] Yes
[X] No
```

VIH-5255 Added fixes for tests

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/VhoHearingListSteps.cs

Added the ability to scroll to the hearing list is full
```
[ ] Yes
[X] No
```

VIH-5255 Added a filter to smokiest in case VHO sees lots of hearings

---

.vscode/launch.json
.vscode/tasks.json
VideoWeb/VideoWeb.AcceptanceTests/Configuration/GenerateTemporaryTokens.cs
VideoWeb/VideoWeb.AcceptanceTests/Configuration/VideoWebConfig.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/ConfigHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingAlertsSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/VhoHearingListSteps.cs
VideoWeb/VideoWeb.Common/Security/CustomJwtTokenProvider.cs
VideoWeb/VideoWeb.Common/Security/HashGen/HashGenerator.cs
VideoWeb/VideoWeb.Common/Security/HashGen/KinlyConfiguration.cs
VideoWeb/VideoWeb.EventHub/Handlers/DisconnectedEventHandler.cs
VideoWeb/VideoWeb.IntegrationTests/Api/TokenControllerTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/TokenController/GetTokenTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/TokenController/TokenControllerTest.cs
VideoWeb/VideoWeb.UnitTests/HashGeneratorTests.cs
VideoWeb/VideoWeb/ClientApp/src/app/services/api/video-web-service.interface.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/api/video-web.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/MockVideoService.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/scripts/Heartbeat.js
VideoWeb/VideoWeb/Controllers/TokenController.cs
VideoWeb/VideoWeb/Startup.cs
VideoWeb/VideoWeb/appsettings.json
azure-pipelines.yml

VIH-5762
* Update client configuration for new Kinly environments
```
[ ] Yes
[x] No
```

VIH-5762 Update client configuration for new Kinly environments

---

VideoWeb/VideoWeb.Common/Security/CustomJwtTokenProvider.cs

VIH-5255 Fix for issue with callback token generation

---

VideoWeb/VideoWeb.AcceptanceTests/Pages/FiltersPopupPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/FiltersSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs

- Fix for clear filters
- Fix for safari clerk waiting room text needing Trim()
```
[ ] Yes
[X] No
```

VIH-5255 Fixes for tests

---

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj

- Added logging for Chrome on Sauce Labs
```
[ ] Yes
[X] No
```

VIH-5255 Added logging for Chrome on Sauce Labs

---

VideoWeb/VideoWeb.AcceptanceTests/Hooks/HooksSequence.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj

- Deleting test data after closing the browser
- Enable loggin in firefox 
```
[ ] Yes
[X] No
```

VIH-5255 Reorder teardown

---

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.Common/Extensions/ConferenceExtensions.cs
VideoWeb/VideoWeb.Contract/Request/VhoConferenceFilterQuery.cs
VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs
VideoWeb/VideoWeb.IntegrationTests/VideoWeb.IntegrationTests.csproj
VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForVHOfficerTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/HealthController/HealthTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/VenueControllerTest.cs
VideoWeb/VideoWeb.UnitTests/Hub/EventHubBaseTests.cs
VideoWeb/VideoWeb/ClientApp/src/app/services/api/video-web-service.interface.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/api/video-web.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/MockVideoService.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/services/hearings-filter-options.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/services/hearings-filter-options.service.ts
VideoWeb/VideoWeb/Controllers/ConferencesController.cs
VideoWeb/VideoWeb/Controllers/HealthCheckController.cs
VideoWeb/VideoWeb/Controllers/VenuesController.cs
VideoWeb/VideoWeb/VideoWeb.csproj

VIH-5846
add empty list for vho query filter until allocation is finished
```
[ ] Yes
[x] No
```

VIH-5846 pass empty list for vho query filter

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingAlerts.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/FiltersSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingAlertsSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Strategies/HearingStatus/SuspendedStrategy.cs

- Updating tests to suspend fixes
```
[ ] Yes
[X] No
```

VIH-5255 Added fixes for the suspend changes

---

VideoWeb/VideoWeb.AcceptanceTests/Assertions/AssertChatMessage.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/DriverHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/InstantMessagingSteps.cs

- Fixes for instability in the chat message tests
- Reenabled Chrome logging
- Fixed iframe issues on Firefox 
- Fix incorrect click method for Safari in hearing list test
```
[ ] Yes
[X] No
```

VIH-5255 Various test fixes 

---

VideoWeb/VideoWeb.AcceptanceTests/Steps/PrivateConsultationSteps.cs

-Fix for Safari private consultation
```
[ ] Yes
[X] No
```

VIH-5255 Fix for Safari private consultation

---

VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs
VideoWeb/VideoWeb/Controllers/ConferencesController.cs
VideoWeb/VideoWeb/Controllers/VideoEventsController.cs
VideoWeb/VideoWeb/appsettings.json

https://tools.hmcts.net/jira/browse/VIH-5855
```
[ ] Yes
[ ] No
```

VIH-5855 logging cleanup

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-hearing-page/judge-hearing-page.component.css
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-hearing-page/judge-hearing-page.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-hearing-page/judge-hearing-page.component.ts

https://tools.hmcts.net/jira/browse/VIH-5853
Fix for camera issues on Chrome 81 + iframe
```
[ x] Yes
[ ] No
```

VIH-5853 Fix for camera issues on Chrome 81

---

VideoWeb/VideoWeb/ClientApp/src/app/app.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/app.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/app.module.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/error.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/page-tracker.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/page-tracker.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.html
VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts

https://tools.hmcts.net/jira/browse/VIH-5789
- initial version.
```
[ ] Yes
[x] No
```

VIH-5789 Update_to_Service_Error_Messages_in_VideoWeb

---

VideoWeb/VideoWeb.AcceptanceTests/Steps/VhoVenueListSteps.cs

- Fix for the venue dropdown not being selected
```
[ ] Yes
[X] No
```

VIH-5255 Fix for the venue dropdown not being selected

---

VideoWeb/VideoWeb.AcceptanceTests/Features/Filters.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/Login.feature

- Missing fix from VHO venue list update
```
[ ] Yes
[X] No
```

VIH-5255 Fix for the VHO login page

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-hearing-page/judge-hearing-page.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-hearing-page/judge-hearing-page.component.ts

https://tools.hmcts.net/jira/browse/VIH-5869
Fix for camera issues on Chrome 81 + iframe
- Feature policy changes for camera and microphone
```
[x ] Yes
[ ] No
```

VIH-5869 Feature policy changes for camera and microphone

---

VideoWeb/VideoWeb.AcceptanceTests/Api/PollForParticipantStatus.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/FiltersSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj

-Display actual status when polling participant state
```
[ ] Yes
[X] No
```

VIH-5255 Display actual status when polling participant state

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-chat/judge-chat.component.ts

https://tools.hmcts.net/jira/browse/VIH-5878
Fix for judge IM, after reload existing IMs, judge could not send messages
```
[ X] Yes
[ ] No
```

VIH-5878 Fix judge send IM

---

CODEOWNERS
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Hooks/DriverHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj

- Disabled debugging for Hearing Room tests
- Updated NuGet package
- Refactored driver hooks
```
[ ] Yes
[X] No
```

VIH-5255 Disabled debugging for Hearing Room tests

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts

https://tools.hmcts.net/jira/browse/VIH-5889
Show sound bar on replay
```
[ X] Yes
[ ] No
```

VIH-5889 ShowSoundBarOnReplay

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.ts

VIH-5846
- set the loading data flag at start of data retrieval,
```
[ ] Yes
[x] No
```

VIH-5846 no-hearings-message

---

VideoWeb/VideoWeb.AcceptanceTests/Features/Accessibility.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/venue-list/venue-list.component.html

- Added a title to the new Venue List screen for accessibility
- Added an accessibility page for that test
- Changed the VHO and Accessibility hearing room tests as there is a Chrome issue whilst logging and running the hearing room tests at the same time.
```
[ ] Yes
[X] No
```

VIH-5255 Added a title to venue select for accessibility

---

VideoWeb/VideoWeb.AcceptanceTests/Features/InstantMessaging.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/VideoHearingsOfficerCallSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj

- Added an autoplay media allowed flag to Firefox driver
- Enabled VHO and IM tests on all browsers, not just Chrome
```
[ ] Yes
[X] No
```

VIH-5255 Re-enable IM and VHO calling on all browsers

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/mic-visualiser/mic-visualiser.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.html
VideoWeb/VideoWeb/ClientApp/src/app/testing/stubs/mic-visualiser-stub.ts

https://tools.hmcts.net/jira/browse/VIH-5889
Mix two streams to get audio bar moving for video and self screen audio
```
[ X] Yes
[ ] No
```

VIH-5889 moving audio bar for video and self audio

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.no-conference.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.ts

https://tools.hmcts.net/jira/browse/VIH-5892
Fixes VHO screen refresh issue
```
[ ] Yes
[x ] No
```

VIH-5892 VHO Screen refresh issue

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/venue-list/venue-list.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/venue-list/venue-list.component.ts

VIH-5897
Fix typo in venue list
```
[ ] Yes
[x] No
```

VIH-5897 typo fix in venue list

---

VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature

- Fix for VHO Call on Chrome/Sauce Labs
```
[ ] Yes
[X] No
```

VIH-5255 Fix for VHO Call on Chrome

---

VideoWeb/VideoWeb.UnitTests/Controllers/AudioRecordingControllerTest.cs
VideoWeb/VideoWeb/Controllers/AudioRecordingController.cs

https://tools.hmcts.net/jira/browse/VIH-5865
- changed the videoapi call to delete application
```
[ ] Yes
[x] No
```

VIH-5865 Delete_application

---

VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/tasks-table/tasks-table.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/tasks-table/tasks-table.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vh-officer.module.ts

VIH-5903
* change input for tasks table to a conference id and retrieve data within component rather than rely on other components causing
```
[ ] Yes
[x] No
```

VIH-5903 make tasks table independent

---

VideoWeb/VideoWeb.AcceptanceTests/Builders/HearingRequestBuilder.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs

- Allow the audio recording to be specified when creating a hearing
```
[ ] Yes
[X] No
```

VIH-5255 Add the option for audio recording

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-status/participant-status.component.spec.ts

https://tools.hmcts.net/jira/browse/VIH-5827
```
[ ] Yes
[ ] No
```

VIH-5827 Fix jasmine test

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/tasks-table/tasks-table.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-hearing-list/vho-hearing-list.component.html

VIH-5873
correct spacing issues for command centre
Works at 100% with as low as 13 inch screens
```
[ ] Yes
[x] No
```

VIH-5873 correct spacing issues for command centre

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/footer/footer.component.html

https://tools.hmcts.net/jira/browse/VIH-4428
- updated html to open Privacy policy in same tab.
```
[ ] Yes
[x] No
```

VIH-4428 Footer_links_should_open_up_in_the_same_tab window

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/beta-banner/beta-banner.component.html

https://tools.hmcts.net/jira/browse/VIH-5934
- updated html to open feedback link in same tab
```
[ ] Yes
[x] No
```

VIH-5934 Accessibility_Feedback_link_should_open_up_in_the_same tab

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/monitoring-graph/monitoring-graph.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-info-tooltip/participant-info-tooltip.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-network-status/participant-network-status.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-status/participant-status.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/pending-tasks/pending-tasks.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/tasks-table/tasks-table.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/unread-messages/unread-messages.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-global-styles.scss
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-hearing-list/vho-hearing-list.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-herings-filter/vho-hearings-filter.component.ts

VIH-5873
* added a global vho command centre stylesheet
* reduce font size for command centre to 1rem
```
[ ] Yes
[ ] No
```

VIH-5873 reduce font size for command centre

---

VideoWeb/VideoWeb/ClientApp/src/scripts/Heartbeat.js

https://tools.hmcts.net/jira/browse/VIH-5951
- updated file from Kinly
```
[ ] Yes
[x] No
```

VIH-5951 Update-heartbeat.js

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/monitoring-graph/monitoring-graph.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/monitoring-graph/monitoring-graph.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/monitoring-graph/monitoring-graph.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-network-status/participant-network-status.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-network-status/participant-network-status.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-network-status/participant-network-status.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-network-status/participant-network-status.component.ts

VIH-5727
* Allow graph to move with mouse
* Add arrow head to top of graph div
```
[ ] Yes
[x] No
```

VIH-5727 update monitoring graph style and location

---

VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts

https://tools.hmcts.net/jira/browse/VIH-5837
added try catch and logging error, 
added stop event service on close judge screen.
```
[ ] Yes
[x] No
```

VIH-5837 IM-bug

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingAlerts.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingAlertsSteps.cs
VideoWeb/VideoWeb.Common/Extensions/StringExtensions.cs
VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/tasks-table/tasks-table.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/tasks-table/tasks-table.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/tasks-table/tasks-table.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/tasks-table/tasks-table.component.ts

VIH-5873 
* Adjust spacing for task table on smaller screens
* Drop the domain in the username when displaying who completed a task
```
[ ] Yes
[x] No
```

VIH-5873 Adjust task table styling on smaller screens

---

VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb/ClientApp/src/scripts/Heartbeat.js

https://tools.hmcts.net/jira/browse/VIH-5951
- updated with the latest heartbeat.js file from Kinly
```
[ ] Yes
[x] No
```

VIH-5951 update heartbeat.js

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.html

https://tools.hmcts.net/jira/browse/VIH-5933
Removed ngif that toggled visibility of the self-view
```
[ ] Yes
[ ] No
```

VIH-5933 Removed ngif that toggled visibility of the self-view

---

VideoWeb/VideoWeb/ClientApp/src/app/app.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-list.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-herings-filter/vho-hearings-filter.component.scss
VideoWeb/VideoWeb/ClientApp/src/styles.scss

VIH-5946 
* Remove deprecated //deep styling
* Use the override page width solution introduced in govuk front end update 
```
[ ] Yes
[x] No
```

VIH-5946 Update fullscreen styling to use GovUK override

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/unread-messages/unread-messages.component.html

https://tools.hmcts.net/jira/browse/VIH-5947
- removed the message count from ui.
```
[ ] Yes
[x] No
```

VIH-5947 update im alert to remove the number of unread messages and replace it with an icon

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/hearings/vho-hearings.component.html

https://tools.hmcts.net/jira/browse/VIH-5716
- updated the text message when no hearings are scheduled.
```
[ ] Yes
[x] No
```

VIH-5716 video web update text for when vho has no hearings in

---

VideoWeb/VideoWeb/ClientApp/src/app/services/events.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/chat/chat-base.component.ts

https://tools.hmcts.net/jira/browse/VIH-5787
Stop to display IM messages in the console log
```
[ X] Yes
[ ] No
```

VIH-5787 Remove text of IMs from console logger

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-chat/judge-chat.component.html

https://tools.hmcts.net/jira/browse/VIH-5918
- hid the div using html hidden attr.
```
[ ] Yes
[x] No
```

VIH-5918 unsent judge i ms to persist on minimise

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/services/monitor-graph.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/services/monitor-graph.service.ts

https://tools.hmcts.net/jira/browse/VIH-5917
Adjust drawing of the monitor graph
```
[X] Yes
[ ] No
```

VIH-5917 adjust drawing of the heartbeat graph

---

VideoWeb/VideoWeb/Startup.cs

https://tools.hmcts.net/jira/browse/VIH-5919
```
[ ] Yes
[ ] No
```

VIH-5919 Fix callback incoming token throwing error

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/pending-tasks/pending-tasks.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/unread-messages/unread-messages.component.scss

https://tools.hmcts.net/jira/browse/VIH-5971
Fix for Command Centre scroll issue
```
[ ] Yes
[ ] No
```

VIH-5971 Command Centre scroll issue

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-hearing-page/judge-hearing-page.component.ts

https://tools.hmcts.net/jira/browse/VIH-5331
```
[ ] Yes
[ ] No
```

VIH-5331 Delay the audio recording stream check

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingAlerts.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingStatus.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingAlertsSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsStatusSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ParticipantStatusSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/VhoHearingListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj

- Fixes for overnight Safari tests
```
[ ] Yes
[X] No
```

VIH-5255 Fixes for Safari tests

---

VideoWeb/VideoWeb/ClientApp/src/app/services/event-bus.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/command-centre.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/tests/command-centre.component-core.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/tests/command-centre.component-events.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/tasks-table/tasks-table.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/tasks-table/tasks-table.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/tasks-table/tasks-table.component.ts

https://tools.hmcts.net/jira/browse/VIH-6018
- updated to refresh the alerts section for alerts
```
[ ] Yes
[x] No
```

VIH-6018 Alerts_not_displayed_unless_user_refreshes_the_screen

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/admin-hearing/admin-hearing.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/admin-hearing/admin-hearing.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-hearing-page/judge-hearing-page.component.ts

https://tools.hmcts.net/jira/browse/VIH-6031
- reverted code for ifram, changed to bypassSecurityTrustResourceUrl
```
[ ] Yes
[x] No
```

VIH-6031 Iframes_unable_to_load_-_unsafe_value_used_in_a_resource_URL_context

---

VideoWeb/VideoWeb.AcceptanceTests/Data/ParticipantsManager.cs
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/InstantMessaging.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/AdminPanelPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/HearingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/VhoHearingListPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/InstantMessagingSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ParticipantStatusSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/venue-list/venue-list.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/venue-list/venue-list.component.scss

- Fixed some (not all) the accessibility issues on the Venues List page
- Fixed the IM tests
- Added a test for VHO monitoring
```
[ ] Yes
[X] No
```

VIH-5255 Fixes for IM Tests and some accessibility Issues

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/venue-list/venue-list.component.html

VIH-6040
* Stop venue list from closing on each click
```
[ ] Yes
[x] No
```

VIH-6040 Stop auto closing venue list on select

---

VideoWeb/VideoWeb.EventHub/Handlers/DisconnectedEventHandler.cs
VideoWeb/VideoWeb.EventHub/Handlers/LeaveEventHandler.cs
VideoWeb/VideoWeb.UnitTests/EventHandlers/DisconnectedEventHandlerTests.cs
VideoWeb/VideoWeb.UnitTests/EventHandlers/LeaveEventHandlerTests.cs
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/services/vho-query-service.service.ts

VIH-6033
Set judge status to 'not signed in' on disconnect
```
[ ] Yes
[x] No
```

VIH-6033 judge status disconnected when hearing closes

---

VideoWeb/VideoWeb.AcceptanceTests/Pages/VhoVenueAllocationPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/InstantMessagingSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/VhoVenueListSteps.cs

- Fix for the venue list allocation
```
[ ] Yes
[X] No
```

VIH-5255 Added a fix for the VHO dropdown

---

VideoWeb/VideoWeb.AcceptanceTests/Features/Accessibility.feature

https://tools.hmcts.net/jira/browse/VIH-6032
- Ignoring test until Angular 9 upgrade
```
[ ] Yes
[X] No
```

VIH-6032 Ignoring test until Angular 9 upgrade

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html

https://tools.hmcts.net/jira/browse/VIH-6036
Remove upper case 
```
[ ] Yes
[X ] No
```

VIH-6036 RemoveUpperCaseMicMute

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/ParticipantStatus.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant-status-reader.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant-status-reader.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-status/participant-status.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.ts

https://tools.hmcts.net/jira/browse/VIH-6050
De-capitalise words in statuses and titles in command centre
```
[X ] Yes
[ ] No
```

VIH-6050 De-capitalise words for status and titles

---

VideoWeb/VideoWeb.AcceptanceTests/Steps/ParticipantStatusSteps.cs
VideoWeb/VideoWeb.Services/VideoApiClient.cs

- "In Hearing" and "In Consultation" are now "In **h**earing" and "In **c**onsultation"
```
[ ] Yes
[X] No
```

VIH-5255 Fix for statuses case changes

---

VideoWeb/VideoWeb.Services/VideoApiClient.cs

https://tools.hmcts.net/jira/browse/VIH-6046
Changes to VideoAPI client contracts to store first name and last name
```
[ ] Yes
[x ] No
```

VIH-6046 Added first and last names to participant

---

VideoWeb/VideoWeb/ClientApp/src/app/home/home.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-list.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-hearings/participant-hearings.component.html
VideoWeb/VideoWeb/ClientApp/src/app/services/device-type.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/unsupported-device/unsupported-device.component.html

https://tools.hmcts.net/jira/browse/VIH-6095
- added an isIpad method in deviceDetectorService, 
- added check in home page component.
```
[ ] Yes
[x] No
```

VIH-6095 Unblock_iPads - 

---

.gitignore
VideoWeb/VideoWeb/ClientApp/src/app/services/events.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/models/instant-message.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/chat-body-window/chat-body-window.component.html
VideoWeb/VideoWeb/ClientApp/src/app/shared/chat-body-window/chat-body-window.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/shared/chat-body-window/chat-body-window.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/chat-body-window/chat-body-window.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/chat/chat-base.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/privacy-policy/privacy-policy.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/privacy-policy/privacy-policy.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/shared.module.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.ts

VIH-6028
* display error when IMs fail to send
* allow user to retry to send failed IMs
```
[ ] Yes
[x] No
```

VIH-6028 error message on im send failure with retry

---

README.md

https://tools.hmcts.net/jira/browse/VIH-6086
Updated readme file with Stryker instructions
```
[ ] Yes
[x] No
```

VIH-6086 Updated readme file with Stryker instructions

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/chat/chat-base.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/im-helper.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/im-helper.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/mock-events-service.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.ts

VIH-5862
* if recipient is admin, ensure the sender is current participant window
```
[ ] Yes
[x] No
```

VIH-5862 ensure admin isolates conversations between participants

---

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-self-test/participant-self-test.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-self-test/participant-self-test.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts

https://tools.hmcts.net/jira/browse/VIH-6076
Set incomplete self-test if continue is pressed before test score is retrieved. Fix sound bar(was not visible)
```
[X ] Yes
[ ] No
```

VIH-6076 set Incomplete self test fix sound bar

---

VideoWeb/VideoWeb/ClientApp/src/app/services/events.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/chat/chat-base.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/unread-messages-shared/unread-message-base.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.html

VIH-6028
Fix: Pending messages will not be displayed across multiple windows for an admin anymore
```
[ ] Yes
[x] No
```

VIH-6028 ensure pending messages only appear in correct window

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html

https://tools.hmcts.net/jira/browse/VIH-5931
Changed text for delay and tech issue in waiting room
```
[ X] Yes
[ ] No
```

VIH-5931 changed text for waiting room

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.eventhub.events.spec.ts

VIH-6069
* add additional assertsions around eventhub disconnect behaviour for participant waiting room
```
[ ] Yes
[x] No
```

VIH-6069 assert on refreshed values after eventhub disconnect

---

VideoWeb/VideoWeb.AcceptanceTests/Hooks/DriverHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json

- Fix for overnight build issues
```
[ ] Yes
[X] No
```

VIH-5255 Fixed sauce labs driver creation issues

---

VideoWeb/VideoWeb/ClientApp/package.json
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.videocall.events.spec.ts

VIH-6098
* Only show video controls when user is conncted
```
[ ] Yes
[x] No
```

VIH-6098 menu controls show on page load

---

azure-pipelines.beta.yml
azure-pipelines.nightly.yml

- Fix for Incorrectly spelt tag names on overnight pipelines
```
[ ] Yes
[X] No
```

VIH-5255 Fixes for smoketest-extended tags

---

VideoWeb/VideoWeb/ClientApp/src/app/services/api/consultation.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/api/consultation.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/models/consultation-message.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/accepted-consultation/accepted-consultation.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/accepted-consultation/accepted-consultation.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/accepted-consultation/accepted-consultation.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/consultation-error/consultation-error.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/no-consultation-room/no-consultation-room.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/no-consultation-room/no-consultation-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/raise-consultation/raise-consultation.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/raise-consultation/raise-consultation.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/raise-consultation/raise-consultation.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/receive-consultation/receive-consultation.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/receive-consultation/receive-consultation.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/receive-consultation/receive-consultation.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/rejected-consultation/rejected-consultation.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/rejected-consultation/rejected-consultation.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/rejected-consultation/rejected-consultation.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/vho-raise-consultation/vho-raise-consultation.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/vho-raise-consultation/vho-raise-consultation.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/vho-raise-consultation/vho-raise-consultation.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/tests/individual-participant-status-list.component.availability.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/tests/individual-participant-status-list.component.consultation.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-space.module.ts

VIH-6105
* Refactored consultation into service class
* Notification sounds are now in the consultation service class and not in the component
* Move modal markup into own components 
```
[ ] Yes
[x] No
```

VIH-6105 Refactor consultation into service

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingAlerts.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingStatus.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/ParticipantStatus.feature
VideoWeb/VideoWeb.AcceptanceTests/Hooks/RemoveDataHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/ZapHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/WaitingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/VhoVenueListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
VideoWeb/VideoWeb/ClientApp/src/app/services/api/consultation.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/api/consultation.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/modal/modal.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/consultation-error/consultation-error.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/consultation-modals/no-consultation-room/no-consultation-room.component.html

- Add a tag for smoketest-prod to run audio recording test on Prod
- Clean up both Clerk and Judge user data to avoid it having an impact on subsequent tests
- Fixed venue changes from Birmingham, Manchester etc to Automation judge names
- Updated build names on Sauce Labs test builds
- Reduced the amount of smoketest-extended tests
- Shaed added test for PC
```
[ ] Yes
[X] No
```

VIH-5255 Fix nightly tests

---

VideoWeb/VideoWeb.AcceptanceTests/Features/InstantMessaging.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/InstantMessagingSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ParticipantStatusSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
VideoWeb/VideoWeb.AcceptanceTests/useraccounts.json

- Firefox logging fixed
- Fix for status test
- improved build names
```
[ ] Yes
[X] No
```

VIH-5255 Fixes for overnight tests

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/copy-id/copy-id.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/copy-id/copy-id.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/monitoring-graph/monitoring-graph.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/monitoring-graph/monitoring-graph.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-network-status/participant-network-status.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-network-status/participant-network-status.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-network-status/participant-network-status.component.ts

https://tools.hmcts.net/jira/browse/VIH-5995
- fix to prevent the graph displaying in incorrect position after scroll.
```
[ ] Yes
[x] No
```

VIH-5995 Participant heartbeat popup sometimes shows in incorrect places

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/command-centre.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/tests/command-centre.component-core.spec.ts

https://tools.hmcts.net/jira/browse/VIH-6137
fix bug if venue not selected, but was in previous filter, do not show that hearing
```
[ X] Yes
[ ] No
```

VIH-6137 if venue not found do not show hearing

---

VideoWeb/VideoWeb.AcceptanceTests/Features/Filters.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/FiltersPopupPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/VhoHearingListPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/FiltersSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ProgressionSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/VenueListSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json

https://tools.hmcts.net/jira/browse/VIH-5922
- Added a filter test
- Removed old filter code
- Upgraded NuGet package
```
[ ] Yes
[X] No
```

VIH-5922 Added AC test for filters

---

VideoWeb/VideoWeb/ClientApp/src/app/security/logout/logout.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/security/logout/logout.component.ts

https://tools.hmcts.net/jira/browse/VIH-6136

VIH-6136 Clear session storage on logout

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/command-centre.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/tests/command-centre.component-core.spec.ts

https://tools.hmcts.net/jira/browse/VIH-6137
new branch for fix filter
```
[ ] Yes
[ ] No
```

VIH-6137 new branch with fix for filter

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/venue-list/venue-list.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/venue-list/venue-list.component.ts

https://tools.hmcts.net/jira/browse/VIH-6149
Fix empty filter issue  for court rooms accounts
```
[X ] Yes
[ ] No
```

VIH-6149 Fix delay to get filter data

---

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html

- Updated test NuGet package
```
[ ] Yes
[X] No
```

VIH-5255 Updated NuGet

---

VideoWeb/VideoWeb.AcceptanceTests/Features/PrivateConsultation.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/tests/individual-participant-status-list.component.consultation.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.html
VideoWeb/VideoWeb/ClientApp/src/styles.scss

https://tools.hmcts.net/jira/browse/VIH-6132
Hide consultation for Observer and Panel Member
```
[ X] Yes
[ ] No
```

VIH-6132 hide consultation for observer pm

---

VideoWeb/VideoWeb/ClientApp/src/scripts/pexrtc.js

https://tools.hmcts.net/jira/browse/VIH-6130
- updated js to version on https://sip.test.hearings.hmcts.net/static/webrtc/js/pexrtc.js
```
[ ] Yes
[x] No

VIH-6130 Update_to_Pexip_version_23.4-Part2

---

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-table.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-table.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing-summary.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing-summary.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.html

https://tools.hmcts.net/jira/browse/VIH-6183
- updated participant count to include observers and panel members in the judge hearing list screen
```
[ ] Yes
[x] No
```

VIH-6183 Judge_hearing_list___Participants_count_should_also_include_observers_and_panel_members

---

VideoWeb/VideoWeb/ClientApp/src/app/services/user-media-stream.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/user-media.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/mic-visualiser/mic-visualiser.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts

VIH-6049
* Verify input value is set before creating a stream source with is
```
[ ] Yes
[x] No
```

VIH-6049 select device error

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/WaitingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Hooks/DriverHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/ParticipantListPanel.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingAlertsSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/PrivateConsultationSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json

- Disabled FF Windows logging
- Upgraded NuGet package
- Added fix for private consultations
```
[ ] Yes
[X] No
```

VIH-5255 Disabled FF Windows logging and other fixes

---

VideoWeb/VideoWeb/ClientApp/src/app/services/api/audio-recording.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/api/audio-recording.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-hearing-page/judge-hearing-page.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-hearing-page/judge-hearing-page.component.ts

https://tools.hmcts.net/jira/browse/VIH-6195
Removed stop audio recording(delete audio app) from close hearing by judge.
```
[ ] Yes
[ ] No
```

VIH-6195 Removed stop audio recording for judge

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json

- Added a retry mechanism for browser navigation
- Fixes for tests
```
[ ] Yes
[X] No
```

VIH-5255 Moved navigate to url to NgDriver from Wrapped Driver

---

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
VideoWeb/VideoWeb.AcceptanceTests/parameters.runsettings
azure-pipelines.beta.yml

- Fix for the Sunday beta builds
```
[ ] Yes
[X] No
```

VIH-5255 Beta build fix

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.ts

VIH-6170
* Clear chat between participant select to account for loading time of next chat history
```
[ ] Yes
[x] No
```

VIH-6170 clear messages between participant chat selection

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/video-call-models.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/video-call-models.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.videocall.events.spec.ts

VIH-6125 
* participant informed when they have been muted remotely 
* participants are muted locally upon remote muting so they are not caught off guard on remote unmute
```
[ ] Yes
[x] No
```

VIH-6125 remote mute icon

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.scss

VIH-6170
* adjust height of incoming video feed for participant, leaving enough room for video controls
```
[ ] Yes
[x] No
```

VIH-6170 adjust incoming feed position and size

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/chat/chat-base.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/chat/chat-base.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.spec.ts

VIH-6216
* disable auto scroll to bottom when user moves up chat history
```
[ ] Yes
[ ] No
```

VIH-6216 scroll chat disable on scroll up

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.eventhub.events.spec.ts

https://tools.hmcts.net/jira/browse/VIH-6213
Fix mute/unmute changed on a participant disconnected
```
[X ] Yes
[ ] No
```

VIH-6213 Fix mute change on disconnect

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.scss

VIH-6121
fix spacing between self view and remote mute buttons
```
[ ] Yes
[x] No
```

VIH-6121 fix spacing between self view and remote mute buttons

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/participant-network-health.component.html

VIH-6239
* fix typo in waiting room
```
[ ] Yes
[x] No
```

VIH-6239 fix typo in WR

---

VideoWeb/VideoWeb.Contract/Responses/HealthCheckResponse.cs
VideoWeb/VideoWeb.UnitTests/AppVersionTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/HealthController/HealthTests.cs
VideoWeb/VideoWeb/Controllers/HealthCheckController.cs
VideoWeb/VideoWeb/Helpers/AppVersion.cs

VIH-5629 
add app version to health check
```
[ ] Yes
[x] No
```

VIH-5629 add app version to health check

---

VideoWeb/VideoWeb.AcceptanceTests/Journeys/Journey.cs
VideoWeb/VideoWeb.AcceptanceTests/Journeys/PanelMemberJourney.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ProgressionSteps.cs

- Fix for panel member journey failures
```
[ ] Yes
[X] No
```

VIH-6140 Test fix for changed panel member journey

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/chat-body-window/chat-body-window.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/chat-body-window/chat-body-window.component.ts

https://tools.hmcts.net/jira/browse/VIH-6110
Prevent replay the same IM several times
```
[ X] Yes
[ ] No
```

VIH-6110 prevent to retry IM several times

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.ts

VIH-6127
* open participant chat window when they receive a message
```
[ ] Yes
[x] No
```

VIH-6127 open participant chat window when they receive a message

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.ts

VIH-6127
Open chat window on load when messages are unread
```
[ ] Yes
[x] No
```

VIH-6127 auto open chat window

---

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/declaration/declaration.component.html

https://tools.hmcts.net/jira/browse/VIH-6070
Fix typo on declaration page
```
[X ] Yes
[ ] No
```

VIH-6070 fix declaration page typo

---

VideoWeb/VideoWeb.AcceptanceTests/Builders/ParticipantsRequestBuilder.cs
VideoWeb/VideoWeb.AcceptanceTests/Builders/UpdateParticipantBuilder.cs
VideoWeb/VideoWeb.AcceptanceTests/Features/InstantMessaging.feature
VideoWeb/VideoWeb.Services/BookingsApiClient.cs

- Fix for missing address build issues
- Fix for IM failures now the IM window auto opens
```
[ ] Yes
[X] No
```

VIH-5255 Fixes for address and IM issues

---

VideoWeb/VideoWeb.Services/BookingsApiClient.cs

https://tools.hmcts.net/jira/browse/VIH-5617
Removed address fields from response object
```
[ ] Yes
[ ] No
```

VIH-5617 Removed address fields

---

VideoWeb/VideoWeb.UnitTests/Mappings/ConferenceResponseMapperTests.cs
VideoWeb/VideoWeb/Mappings/ConferenceResponseMapper.cs

https://tools.hmcts.net/jira/browse/VIH-6271
Judge should have T0 tailed position
```
[X] Yes
[ ] No
```

VIH-6271 judge t position

---

VideoWeb/VideoWeb.EventHub/Handlers/DisconnectedEventHandler.cs
VideoWeb/VideoWeb.UnitTests/EventHandlers/DisconnectedEventHandlerTests.cs

VIH-6173
* Judge disconnect is now a disconnected status
```
[ ] Yes
[ ] No
```

VIH-6173 Judge disconnect is now a disconnected status

---

VideoWeb/VideoWeb.Services/VideoApiClient.cs

VIH-6181
update video api client
```
[ ] Yes
[x] No
```

VIH-6181 update video api client

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.scss

VIH-6237
Change css z-index to be panel visible 
```
[ ] Yes
[ ] No
```

VIH-6204 set xindex on panel to be shown

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.scss

VIH-6204 
Added tool-tips for icon and repositioned panel component
```
[X ] Yes
[ ] No
```

VIH-6204 panel add tool tips

---

VideoWeb/VideoWeb.AcceptanceTests/Features/WaitingRoom.feature
VideoWeb/VideoWeb.EventHub/Handlers/Core/EventHandlerBase.cs
VideoWeb/VideoWeb.EventHub/Handlers/CountdownFinishedEventHandler.cs
VideoWeb/VideoWeb.EventHub/Handlers/LeaveEventHandler.cs
VideoWeb/VideoWeb.EventHub/Hub/IEventHubClient.cs
VideoWeb/VideoWeb.UnitTests/EventHandlers/CountdownFinishedEventHandlerTests.cs
VideoWeb/VideoWeb.UnitTests/EventHandlers/LeaveEventHandlerTests.cs
VideoWeb/VideoWeb/ClientApp/src/app/services/events.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/mock-events-service.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/participant-net-health-base.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/participant-network-health.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/waiting-room-monitor.component.html

VIH-6173
* waiting room network health styling fixes
* judge closing a browser updates to disconnected status
* judge unmuted when countdown has finished
```
[ ] Yes
[x] No
```

VIH-6173 judge wr and status

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.scss
VideoWeb/VideoWeb/ClientApp/src/styles.scss

VIH-6173
* self view fades in and out
* judge unmuted after countdown is finished
```
[ ] Yes
[x] No
```

VIH-6173 fade self view in hearing room

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/participant-net-health-base.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/participant-network-health.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/participant-network-health.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/waiting-room-monitor.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-global-styles.scss

VIH-6353
* add network indicator to judge hearing page
```
[ ] Yes
[x] No
```

VIH-6353 add network indicator to judge hearing page

---

VideoWeb/VideoWeb.AcceptanceTests/Data/Test.cs
VideoWeb/VideoWeb.AcceptanceTests/Features/Accessibility.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/HearingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/Page.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/BrowserSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.html

VIH-6173
* updated assertions for new clerk experience
```
[ ] Yes
[x] No
```

VIH-6173 update ui tests

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts

VIH-6372
* Judge can unmute individual participants
* Update tooltip text between mute and unmute
```
[ ] Yes
[x] No
```

VIH-6372 Judge can unmute individual participants

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/participant-network-health.component.html

VIH-6368
Update text for network connetion health
```
[ ] Yes
[x] No
```

VIH-6368 Update text for network connetion health

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.scss

https://tools.hmcts.net/jira/browse/VIH-6375
styling for tooltip for participant names in panel
```
[X ] Yes
[ ] No
```

VIH-6375 panel long name

---

azure-pipelines.beta.yml
azure-pipelines.release.yml
azure-pipelines.yml

VIH-6376
* revert back to kinly test 1 environment
```
[ ] Yes
[x] No
```

VIH-6376 revert back to kinly test 1 environment

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/privacy-policy/privacy-policy.component.html

https://tools.hmcts.net/jira/browse/VIH-6114
- amended text
```
[ ] Yes
[x] No
```

VIH-6114 Amend_Privacy_Policy_wording_to_include_audio

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-global-styles.scss

https://tools.hmcts.net/jira/browse/VIH-6369
Panel is not overlay the video and changed tooltips
```
[ X] Yes
[ ] No
```

VIH-6369 update judge panel

---

VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb/ClientApp/src/app/shared/privacy-policy/privacy-policy.component.html

https://tools.hmcts.net/jira/browse/VIH-6114
- updated text in other sections
```
[ ] Yes
[x] No
```

VIH-6114 amend privacy policy wording to include audio

---

VideoWeb/VideoWeb.AcceptanceTests/Api/PollForConferenceStatus.cs
VideoWeb/VideoWeb.AcceptanceTests/Api/PollForParticipant.cs
VideoWeb/VideoWeb.AcceptanceTests/Api/PollForParticipantStatus.cs
VideoWeb/VideoWeb.AcceptanceTests/Api/PollForUpdatedConference.cs
VideoWeb/VideoWeb.AcceptanceTests/Api/PollForUpdatedParticipant.cs
VideoWeb/VideoWeb.AcceptanceTests/Helpers/Tasks.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/RemoveDataHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingAlertsSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsStatusSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/PracticeVideoHearingSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/QueueSubscriberSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/TestHelpersSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
VideoWeb/VideoWeb.Common/Helpers/ApiRequestHelper.cs
VideoWeb/VideoWeb.IntegrationTests/Api/TokenControllerTests.cs

- Fixed for serialisation issue on callbacks
```
[ ] Yes
[X] No
```

VIH-5255 Fixed callbacks

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-alert/participant-alert.component.html

VIH-6377 judge panel
Tooltip for alert and adjust hearing control.
```
[ X] Yes
[ ] No
```

VIH-6377 alert tooltip and hearing control layout

---

azure-pipelines.beta.yml
azure-pipelines.nightly.yml
azure-pipelines.release.yml
azure-pipelines.wowza-check.yml
azure-pipelines.yml

VIH-6286
add support across all pipelines for better FW await
```
[ ] Yes
[x] No
```

VIH-6286 add support across all pipelines for better FW await

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-alert/participant-alert.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-alert/participant-alert.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/participant-network-health.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/waiting-room-monitor.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts

https://tools.hmcts.net/jira/browse/VIH-6377
Adjust judge panel layout
```
[ X] Yes
[ ] No
```

VIH-6377 judge panel layout

---

azure-pipelines.nightly.yml

VIH-5255 video-web nightlies dont retry (temp fix)

---

VideoWeb/VideoWeb.AcceptanceTests/Strategies/HearingStatus/InSessionStrategy.cs
VideoWeb/VideoWeb.Services/UserApiClient.cs
VideoWeb/VideoWeb.Services/VideoApiClient.cs

- Fix for test after video start event changes
```
[ ] Yes
[X] No
```

VIH-5255 Hearing In Session test fix

---

VideoWeb/VideoWeb.AcceptanceTests/Helpers/GetHearingRow.cs
VideoWeb/VideoWeb.AcceptanceTests/Helpers/HearingRow.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs
VideoWeb/VideoWeb.Contract/Responses/ConferenceForJudgeResponse.cs
VideoWeb/VideoWeb.Services/UserApiClient.cs
VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb.UnitTests/Mappings/ConferenceForJudgeResponseMapperTests.cs
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-table.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-table.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/JudgeHearingSummary.ts
VideoWeb/VideoWeb/Mappings/ConferenceForJudgeResponseMapper.cs

WIP
https://tools.hmcts.net/jira/browse/VIH-6427
Show number of video access points in judge hearing list 
```
[ X] Yes
[ ] No
```

VIH-6427 display number endpoints

---

VideoWeb/VideoWeb.Common/Caching/ConferenceCacheMapper.cs
VideoWeb/VideoWeb.Common/Models/Conference.cs
VideoWeb/VideoWeb.Common/Models/Endpoint.cs
VideoWeb/VideoWeb.Common/Models/EndpointStatus.cs
VideoWeb/VideoWeb.Common/Models/ParticipantStatus.cs
VideoWeb/VideoWeb.EventHub/Enums/EndpointState.cs
VideoWeb/VideoWeb.EventHub/Enums/EventType.cs
VideoWeb/VideoWeb.EventHub/Handlers/Core/EventHandler.cs
VideoWeb/VideoWeb.EventHub/Handlers/Core/EventHandlerBase.cs
VideoWeb/VideoWeb.EventHub/Handlers/EndpointDisconnectedEventHandler.cs
VideoWeb/VideoWeb.EventHub/Handlers/EndpointJoinedEventHandler.cs
VideoWeb/VideoWeb.EventHub/Hub/IEventHubClient.cs
VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb.UnitTests/Builders/EventComponentHelper.cs
VideoWeb/VideoWeb.UnitTests/ConferenceCacheTest.cs
VideoWeb/VideoWeb.UnitTests/DistributedConferenceCacheTests.cs
VideoWeb/VideoWeb.UnitTests/EventHandlers/EndpointDisconnectedEventHandlerTests.cs
VideoWeb/VideoWeb.UnitTests/EventHandlers/EndpointJoinedEventHandlerTests.cs
VideoWeb/VideoWeb.UnitTests/EventHandlers/EventHandlerFactoryTests.cs
VideoWeb/VideoWeb.UnitTests/EventHandlers/EventHandlerTestBase.cs
VideoWeb/VideoWeb.UnitTests/Mappings/ConferenceCacheMapperTests.cs
VideoWeb/VideoWeb.UnitTests/Mappings/EndpointCacheMapperTests.cs

VIH-6156
VIH-6358
VIH-6359
* Add EndpointJoined event handler
* Add EndpointDisconnected event handler
```
[ ] Yes
[x] No
```

VIH-6156 endpoint events

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/tests/individual-participant-status-list.component.availability.spec.ts

https://tools.hmcts.net/jira/browse/VIH-6352
Display endpoints to participant in WR
```
[X ] Yes
[ ] No
```

VIH-6352 added endpoints to participant wr

---

VideoWeb/VideoWeb.UnitTests/Controllers/ParticipantController/GetParticipantsWithContactDetailsByConferenceIdAsync.cs
VideoWeb/VideoWeb.UnitTests/Hub/SendHeartbeatTests.cs
VideoWeb/VideoWeb.UnitTests/Mappings/CallbackEventMapperTests.cs
VideoWeb/VideoWeb.UnitTests/Mappings/ConferenceCacheMapperTests.cs
VideoWeb/VideoWeb.UnitTests/Mappings/ParticipantStatusResponseForVhoMapperTests.cs
VideoWeb/VideoWeb/ClientApp/src/app/services/events.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/models/EndpointStatusMessage.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/mock-events-service.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/tests/judge-waiting-room.component.eventhub.events.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VideoWeb/VideoWeb/Controllers/ParticipantsController.cs
VideoWeb/VideoWeb/Controllers/VideoEventsController.cs
VideoWeb/VideoWeb/Mappings/CallbackEventMapper.cs

VIH-6156
* subscribe to endpoint status changes
```
[ ] Yes
[x] No
```

VIH-6156 subscribe to endpoint status changes

---

VideoWeb/VideoWeb.Services/BookingsApiClient.cs
VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-alert/participant-alert.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-alert/participant-alert.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.scss

https://tools.hmcts.net/jira/browse/VIH-6441
- updated UI.
```
[ ] Yes
[x] No
```

VIH-6441 Side_panel_icon_poor_connection

---

VideoWeb/VideoWeb.Contract/Responses/ParticipantForUserResponse.cs
VideoWeb/VideoWeb.UnitTests/Mappings/ParticipantForUserResponseMapperTests.cs
VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
VideoWeb/VideoWeb/Helpers/ParticipantTilePositionHelper.cs
VideoWeb/VideoWeb/Mappings/ConferenceResponseMapper.cs
VideoWeb/VideoWeb/Mappings/ParticipantForUserResponseMapper.cs

https://tools.hmcts.net/jira/browse/VIH-6438
Fix for a bug that prevents users from muting participants
```
[ x] Yes
[ ] No
```

VIH-6438 Mute participants

---

VideoWeb/VideoWeb.EventHub/Enums/EndpointState.cs
VideoWeb/VideoWeb.EventHub/Enums/EventType.cs
VideoWeb/VideoWeb.EventHub/Exceptions/RoomTransferException.cs
VideoWeb/VideoWeb.EventHub/Handlers/EndpointTransferEventHandler.cs
VideoWeb/VideoWeb.Services/BookingsApiClient.cs
VideoWeb/VideoWeb.Services/TestApiClient.cs
VideoWeb/VideoWeb.Services/UserApiClient.cs
VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb.UnitTests/Builders/EventComponentHelper.cs
VideoWeb/VideoWeb.UnitTests/Controllers/VideoEventController/SendHearingEventTests.cs
VideoWeb/VideoWeb.UnitTests/EventHandlers/EndpointTransferEventHandlerTests.cs
VideoWeb/VideoWeb.UnitTests/EventHandlers/EventHandlerFactoryTests.cs
VideoWeb/VideoWeb.UnitTests/Mappings/CallbackEventMapperTests.cs
VideoWeb/VideoWeb/Controllers/VideoEventsController.cs
VideoWeb/VideoWeb/Mappings/CallbackEventMapper.cs

VIH-6511 
* Add endpoint transfer event
* Push InConsultation statuses
* bugfix: Correctly map endpoint events before sending off to Video API
```
[ ] Yes
[x] No
```

VIH-6511 endpoint transfer event

---

VideoWeb/VideoWeb.Common/Caching/ConferenceCacheMapper.cs
VideoWeb/VideoWeb.Common/Caching/EndpointCacheMapper.cs
VideoWeb/VideoWeb.UnitTests/Mappings/EndpointCacheMapperTests.cs

https://tools.hmcts.net/jira/browse/VIH-6525

VIH-6525 Fix defence advocate null

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/BrowserSteps.cs

- More fixes for overnight tests
```
[ ] Yes
[x] No
```

VIH-5255 More fixes for overnight tests

---

VideoWeb/VideoWeb.AcceptanceTests/Properties/AssemblyInfo.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/BrowserSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ParticipantStatusSteps.cs

https://tools.hmcts.net/jira/browse/VIH-6349
- Enable Parallisation on test runs
- Fixes for some overnight tests
```
[ ] Yes
[X] No
```

VIH-6349 Enable Parallisation on test runs

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts

https://tools.hmcts.net/jira/browse/VIH-6539
Fix for mute
```
[ ] Yes
[ x] No
```

VIH-6539 Mute and Umute issues

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/participant-panel-model.ts
VideoWeb/VideoWeb/ClientApp/src/scripts/pexrtc.js

VIH-6433
Update pexip client to support safari versions greater than 13.1
```
[ ] Yes
[x] No
```

VIH-6433 update pexip client to handle latest safari versions

---

VideoWeb/VideoWeb.AcceptanceTests/Pages/JudgeParticipantPanel.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.ts

https://tools.hmcts.net/jira/browse/VIH-6457
- added hearing role to participant display list
```
[ ] Yes
[x] No
```

VIH-6457 Judge_sees_hearing_roles_in_participant_list_in_Judge_WR

---

VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.html

VIH-6508
Change text for representee in participants list
```
[X ] Yes
[ ] No
```

VIH-6508 changed representee text

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/tests/individual-participant-status-list.component.availability.spec.ts

VIH-6508
changed test in participant list
```
[X ] Yes
[ ] No
```

VIH-6508 fix for role text participant list

---

VideoWeb/VideoWeb.AcceptanceTests/Features/ParticipantStatus.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/AccessibilitySteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/CommonSteps.cs
VideoWeb/VideoWeb.Services/TestApiClient.cs
VideoWeb/VideoWeb.Services/UserApiClient.cs
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/command-centre.component.html

- Fixes for accessibility issue and status test
```
[ ] Yes
[x] No
```

VIH-5255 Fixes for accessibility issue and status test

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/scripts/Heartbeat.js
azure-pipelines.yml

VIH-6574
fix hb between hearings
```
[ ] Yes
[x] No
```

VIH-6574 fix hb between hearings

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/monitoring-graph/monitoring-graph.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/monitoring-graph/monitoring-graph.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/monitoring-graph/monitoring-graph.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/monitoring-graph/monitoring-graph.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/services/models/graph-settings.ts

https://tools.hmcts.net/jira/browse/VIH-6193

VIH-6193 network graph browser string

---

VideoWeb/VideoWeb.Contract/Responses/ParticipantResponseVho.cs
VideoWeb/VideoWeb.UnitTests/Mappings/ParticipantResponseForVhoMapperTests.cs
VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/venue-list/venue-list.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/tests/individual-participant-status-list.component.availability.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/hearing-role-model.ts
VideoWeb/VideoWeb/Mappings/ParticipantResponseForVhoMapper.cs
azure-pipelines.beta.yml
azure-pipelines.nightly.yml
azure-pipelines.release.yml
azure-pipelines.wowza-check.yml

https://tools.hmcts.net/jira/browse/VIH-6445
- added a separate winger group in the UI for judge and individual lists in WR.
```
[ ] Yes
[x] No
```

VIH-6445 Show_Wingers_in_separate_box_in_judge_and_Participant_WR

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/participant-net-health-base.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/participant-network-health.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/participant-network-health.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/tests/participant-network-health.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html

VIH-6384
only show poor network in waiting room
---
particpant waiting room
---
judge waiting room
```
[ ] Yes
[x] No
```

VIH-6384 only show poor network in waiting room

---

VideoWeb/VideoWeb.EventHub/Mappers/HeartbeatRequestMapper.cs
VideoWeb/VideoWeb.Services/TestApiClient.cs
VideoWeb/VideoWeb.UnitTests/Mappings/HeartbeatRequestMapperTests.cs
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-alert/participant-alert.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-alert/participant-alert.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/participant-net-health-base.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/tests/participant-network-health.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/tests/waiting-room-monitor.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/waiting-room-monitor.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html

VIH-6384
* Hearing room: only show network message on poor only
* BUGFIX: return Poor when packet loss is >= 15 instead of bad
```
[ ] Yes
[x] No
```

VIH-6384 network connection message on poor only

---

VideoWeb/VideoWeb/ClientApp/src/app/services/events.service.ts

VIH-6603
Allow upto 5 minutes of no messages before disconnecting from SignlaR
```
[ ] Yes
[x] No
```

VIH-6603 increase signalr client no message timeout to 5 minutes

---

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
VideoWeb/VideoWeb.Services/BookingsApiClient.cs
VideoWeb/VideoWeb.Services/VideoApiClient.cs
azure-pipelines.nightly.yml

https://tools.hmcts.net/jira/browse/VIH-6614
- Add Edge MacOS to overnights
```
[ ] Yes
[X] No
```

VIH-6614 Add Edge MacOS to overnights

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs

- Parallel allocation workaround
```
[ ] Yes
[X] No
```

VIH-5255 Parallel allocation workaround

---

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-self-test/participant-self-test.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-self-test/participant-self-test.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-self-test/participant-self-test.component.ts

VIH-6636
disconnect from pexip self test to immediately execute end of test sequence
```
[ ] Yes
[x] No
```

VIH-6636 click continue quickly and often on self test

---

VideoWeb/VideoWeb.AcceptanceTests/Helpers/Users.cs
VideoWeb/VideoWeb.Services/VideoApiClient.cs

- Fix for Winger test
```
[ ] Yes
[X] No
```

VIH-5255 Fix for Winger test

---

VideoWeb/VideoWeb.AcceptanceTests/Hooks/HealthcheckHooks.cs

- Retry on Forbidden firewall issues
```
[ ] Yes
[X] No
```

VIH-5255 Retry on Forbidden firewall issues

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingsList.feature
VideoWeb/VideoWeb.AcceptanceTests/Helpers/GetHearingRow.cs
VideoWeb/VideoWeb.AcceptanceTests/Helpers/HearingRow.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/JudgeHearingListPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs

https://tools.hmcts.net/jira/browse/VIH-6621
- Added tests for hearing list participant counts
```
[ ] Yes
[X] No
```

VIH-6621 Added tests for hearing list participant counts

---

VideoWeb/VideoWeb.AcceptanceTests/Features/WaitingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/ClerkWaitingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs

- Fix breaking progression issue
```
[ ] Yes
[X] No
```

VIH-6315 Fix breaking progression issue

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html

VIH-6551
* remove duplicate modal
* move change device button into same row as poor network message
```
[ ] Yes
[x] No
```

VIH-6551 UI tweaks and fixes

---

VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature
VideoWeb/VideoWeb.Services/VideoApiClient.cs

- Fix for VHO monitoring
```
[ ] Yes
[X] No
```

VIH-5255 Fix for VHO monitoring

---

VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-table.component.html
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/JudgeHearingSummary.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/judge-hearing-summary.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts

https://tools.hmcts.net/jira/browse/VIH-6633
Display witnesses in participant total in hearing list
```
[ ] Yes
[ x] No
```

VIH-6633 Display witnesses in participant total in hearing list

---

VideoWeb/VideoWeb/ClientApp/src/styles.scss

VIH-5181 
* disable click events for video elements
* stops users from being able to 'Show controls' for video elements
```
[ ] Yes
[x] No
```

VIH-5181 disable click events for video elements

---

VideoWeb/VideoWeb/ClientApp/src/app/services/error.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.html
VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/error-message.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/judge-hearing-summary.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/tests/judge-waiting-room.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.videocall.events.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts

VIH-6668
* check for heartbeat before attempting to kill on pexip error
* display appropriate message in error component when user denies permission
```
[ ] Yes
[x] No
```

VIH-6668 log pexip errors

---

VideoWeb/VideoWeb/ClientApp/src/app/services/user-media.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/user-media.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/tests/judge-waiting-room.component.eventhub.events.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/tests/judge-waiting-room.component.spec.ts

https://tools.hmcts.net/jira/browse/VIH-6662
https://tools.hmcts.net/jira/browse/VIH-6665
Fix persist media devices from self-test to wr, initialise preferred devices in the cache
```
[ X] Yes
[ ] No
```

VIH-6665 fix change devices to persists

---

VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingAlertsSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/judge-hearing-list/judge-hearing-table.component.html
VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/participant-hearings/hearing-list-table.component.html

- Fix for Daylight Saving
- FIx for accessibility issue
```
[ ] Yes
[X] No
```

VIH-5255 Fix for Daylight Saving

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/command-centre.component.scss

https://tools.hmcts.net/jira/browse/VIH-6597

VIH-6597 fix_border_around_conference_list

---

VideoWeb/VideoWeb.AcceptanceTests/Pages/HearingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs

- Fix for close hearing on FF
```
[ ] Yes
[X] No
```

VIH-5255 Fix for close hearing on FF

---

VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/analogue-clock/analogue-clock.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/analogue-clock/analogue-clock.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/tests/individual-participant-status-list.component.consultation.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.analogue-time.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.eventhub.events.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts

VIH-5871
- Display waiting room for witness until they are in hearing 
- Updated analogue clock for witnesses
```
[ ] Yes
[x] No
```

VIH-5871 witness enters waiting room

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.scss

https://tools.hmcts.net/jira/browse/VIH-6699
Mirrored self view for change device 
```
[ ] Yes
[X] No
```

VIH-6699 mirror self-view on change device

---

VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingsListSteps.cs
VideoWeb/VideoWeb.UnitTests/Mappings/ConferenceResponseMapperTests.cs
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing-summary.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/hearing-role-model.ts

https://tools.hmcts.net/jira/browse/VIH-6640
VIH-6640 Rename hearing roles
```
[ ] Yes
[ x] No
```

VIH-6640 Rename hearing roles

---

VideoWeb/VideoWeb.EventHub/Mappers/HeartbeatRequestMapper.cs
VideoWeb/VideoWeb.UnitTests/Mappings/HeartbeatRequestMapperTests.cs

https://tools.hmcts.net/jira/browse/VIH-6712
Fix mapping the participant network icon in VHO command Center to poor signal.
```
[ ] Yes
[ ] No
```

VIH-6712 fix network icon mismatch

---

VideoWeb/VideoWeb/ClientApp/src/app/services/logging/loggers/app-insights-logger.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts
VideoWeb/VideoWeb/ClientApp/src/typings.d.ts

VIH-6705
*  Add additional logging around pexip events and interaction
* log exceptions under traces too with severity level 3 (error)
```
[ ] Yes
[x] No
```

VIH-6705 Add additional logging around pexip events and interaction

---

VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
azure-pipelines.nightly.yml

- Increase retries
- Added extra wait for FF
```
[ ] Yes
[X] No
```

VIH-5255 Increase retries and added extra wait for FF

---

VideoWeb/VideoWeb/ClientApp/package-lock.json
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/analogue-clock/analogue-clock.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/analogue-clock/analogue-clock.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html

VIH-5871
Changed witness analogue clock colour from yellow to blue for delayed hearing
```
[ ] Yes
[x] No
```

VIH-5871 Witness waiting room clock colour

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/participant-net-health-base.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-network-health/tests/participant-network-health.component.spec.ts

https://tools.hmcts.net/jira/browse/VIH-6725
Signal notification should alert user for poor and bad network signal
```
[ X] Yes
[ ] No
```

VIH-6725 Signal notification in participants WR

---

VideoWeb/VideoWeb/ClientApp/src/app/services/error.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/video-call-models.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.videocall.events.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts

capture when internet connection has been lost
VIH-6727 
* improve pexip error logging
* capture when internet connection has been lost and display appropriate connection lost message
```
[ ] Yes
[x] No
```

VIH-6727 improve pexip error logging

---

VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/CallWitnessTests.cs
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts

VIH-6728
fix judge lowering hand
```
[ ] Yes
[x] No
```

VIH-6728 fix judge lowering hand

---

VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/DismissWitnessTests.cs
VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/mock-video-call-service.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts
VideoWeb/VideoWeb/Controllers/ConferenceManagementController.cs

VIH-6234
* dismiss witness from hearing (non-ui)
```
[ ] Yes
[x] No
```

VIH-6234 dismiss witness from hearing (non-ui)

---

VideoWeb/VideoWeb/ClientApp/src/app/services/error.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/error.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/tests/judge-waiting-room.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.videocall.events.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts

VIH-6655
* log data for selftest
* add method to handle pexip errors
```
[ ] Yes
[x] No
```

VIH-6655 log data for selftest v2

---

VideoWeb/VideoWeb/ClientApp/src/app/services/logging/loggers/app-insights-logger.service.ts

https://tools.hmcts.net/jira/browse/VIH-6735
Fix login redirect on Firefox
```
[ ] Yes
[ ] No
```

VIH-6735 fix redirect on Firefox

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-info-tooltip/participant-info-tooltip.component.html
VideoWeb/VideoWeb/ClientApp/src/styles.scss

https://tools.hmcts.net/jira/browse/VIH-6107
Fix email overflow in participant details tool tip
```
[ ] Yes
[ ] No
```

VIH-6107 fix email overflow in tool tip

---

azure-pipelines.release.yml

VIH-6736 
Point sandbox to Kinly Dev
```
[x] Yes
[] No
```

VIH-6736 Point sandbox to Kinly Dev

---

azure-pipelines.release.yml

VIH-6736
Add missing env variable
```
[ ] Yes
[x] No
```

VIH-6736 Add missing env variable

---

VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/confirm-close-hearing-popup/confirm-close-hearing-popup.component.html

- Attempt to fix issue where tests on FF cannot close the hearing
```
[ ] Yes
[X] No
```

VIH-5255 Attempted fix for FF close hearing button

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing-base.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/analogue-clock/analogue-clock.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/analogue-clock/analogue-clock.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-context-menu/judge-context-menu.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts

VIH-6235
* capture when transfer request fails and show icon again for judge
* close context menu on click
* clock fixes
* black face for hearing in session status and black container
* black inner face for suspend status
```
[ ] Yes
[x] No
```

VIH-6235 bugs when calling witness

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing-base.ts

VIH-6235
Bugfix select hearing from list
```
[ ] Yes
[x] No
```

VIH-6235 Bugfix select hearing from list

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing-base.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts

VIH-6235
* stop remote mute when witness joins
```
[ ] Yes
[x] No
```

VIH-6235 local mute witness on join

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.analogue-time.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.eventhub.events.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.videocall.events.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/notification-sounds.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/notification-sounds.service.ts

VIH-6593 
move the hearing alert sound to the sound service
```
[ ] Yes
[*] No
```

VIH-6593 move hearing alert sound to sound service

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html

https://tools.hmcts.net/jira/browse/VIH-6752
Position disconnect icon on the judge panel
```
[X ] Yes
[ ] No
```

VIH-6752 position Disconnect icon on the panel

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.eventhub.events.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/notification-sounds.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/notification-sounds.service.ts
VideoWeb/VideoWeb/ClientApp/src/test.ts

VIH-6276
* play a hearing alert sound when hearing starts and stop the sound if it is still playing when hearing is paused/suspended/closed
```
[ ] Yes
[x] No
```

VIH-6276 play hearing alert sound when hearing starts.

---

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json

- Attempt to resolve FF click issue with JS Click
```
[ ] Yes
[X] No
```

VIH-5255 Attempt to resolve FF click issue with JS Click

---

VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
VideoWeb/VideoWeb.Services/BookingsApiClient.cs

- Another attempt to resolve the Judge Close issue on FF
```
[ ] Yes
[X] No
```

VIH-5255 Another attempt to resolve the Judge Close issue on FF

---

VideoWeb/VideoWeb/ClientApp/src/app/services/error.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.html
VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts

VIH-6769
change reconnect no connection text
```
[ ] Yes
[x] No
```

VIH-6769 change no internation connection text

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts

VIH-6710
Set transferring in
Duplicate test removed
```
[ ] Yes
[X] No
```

VIH-6710 set transferringIn when transferring

---

VideoWeb/VideoWeb.AcceptanceTests/Pages/VhoHearingListPage.cs

VIH-6590
Added telephone icon field in hearing list page in web client
```
[ ] Yes
[x] No
```

VIH-6590 vho copies telephoneconfid in command centre

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts

VIH-6833
handRaised and isSpotlighted to false on dismiss witness
```
[ ] Yes
[X] No
```

VIH-6833 handRaised and isSpotlighted to false on dismiss witness

---

azure-pipelines.beta.yml
azure-pipelines.nightly.yml

- Increase retries on overnights
```
[ ] Yes
[X] No
```

VIH-5255 Increase retries on overnights

---

.vscode/settings.json
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-alert/participant-alert.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/karma.conf.js
VideoWeb/VideoWeb/ClientApp/src/styles.scss

VIH-6596
* The judge chat window will remain open, even during session
* The judge's network health has been moved to the participant panel list to make room for the chat window
* Hovering on poor network icon will display a tooltip with a descriptive message
```
[ ] Yes
[x] No
```

VIH-6596 enable judge im during hearing

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts
VideoWeb/VideoWeb/ClientApp/src/typings.d.ts

VIH-6297
extend video call service to support audio only calls
```
[ ] Yes
[x] No
```

VIH-6297 extend video call service to support audio only calls

---

VideoWeb/VideoWeb.Contract/Responses/ParticipantContactDetailsResponseVho.cs
VideoWeb/VideoWeb.Services/TestApiClient.cs
VideoWeb/VideoWeb.UnitTests/Controllers/ParticipantController/GetParticipantsWithContactDetailsByConferenceIdAsync.cs
VideoWeb/VideoWeb.UnitTests/Mappings/ParticipantStatusResponseForVhoMapperTests.cs
VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant-contact-details.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant-contact-details.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-info-tooltip/participant-info-tooltip.component.html
VideoWeb/VideoWeb/Mappings/ParticipantStatusResponseForVhoMapper.cs

VIH-6685
display hearing role in vho tooltip
```
[ ] Yes
[x] No
```

VIH-6685 display hearing role in vho tooltip

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/models/selected-user-media-device.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/selected-user-media-device.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.html
VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/video-call-models.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VideoWeb/VideoWeb/ClientApp/src/typings.d.ts

VIH-6581
* participant can select audio only
* participant will connect to a hearing with no outgoing stream but will still be able to see a hearing
```
[ ] Yes
[x] No
```

VIH-6581 participant can select audio only

---

VideoWeb/VideoWeb/ClientApp/src/app/services/error.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/error.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/user-media.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/user-media.service.ts

https://tools.hmcts.net/jira/browse/VIH-6756
add error message in the case if preferred device is not longer connected 
```
[ X] Yes
[ ] No
```

VIH-6756 add error if preferred device not connected

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/error-camera-microphone/error-camera-microphone.component.html

https://tools.hmcts.net/jira/browse/VIH-6756
added margin to the top of page
```
[ ] Yes
[ X] No
```

VIH-6756 add top margin to error page

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/confirmation/confirm-start-hearing-popup.component.html

* VIH-6836
* Fix the typo in the confirmation popup to start or resume a hearing. 
```
[ ] Yes
[x] No
```

VIH-6836 Add missing word in the confirmation popup

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/admin-im-list/admin-im-list.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/admin-im-list/admin-im-list.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/admin-im-list/admin-im-list.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/tests/judge-waiting-room.component.spec.ts

VIH-6596
* show judge as available to VHO, unless disconnected
* disable IM for judges on an iPad when the video is on screen
```
[ ] Yes
[x] No
```

VIH-6596 enable judge im in hearing

---

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-info-tooltip/participant-info-tooltip.component.html
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-info-tooltip/participant-info-tooltip.component.ts

VIH-6685
* Do not show hearing roles for CACD  (i.e. where case type group is 'None')
```
[ ] Yes
[x] No
```

VIH-6685 Do not show hearing roles for CACD 

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/audio-alert/audio-alert.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/audio-alert/audio-alert.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/tests/judge-waiting-room.component.spec.ts

VIH-6907
Alert when a problem is detected with the audio recording
```
[ ] Yes
[x] No
```

VIH-6907 - audio recording alert

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.html

https://tools.hmcts.net/jira/browse/VIH-6822
fix typo in the content of firewall error page
```
[ ] Yes
[ ] No
```

VIH-6822 typo in text of error page for firewall

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts
VideoWeb/VideoWeb/ClientApp/src/typings.d.ts

VIH-6301
initialise correct hearing icons when hearing starts
```
[ ] Yes
[x] No
```

VIH-6301 initialise correct hearing icons

---

VideoWeb/VideoWeb.UnitTests/Helpers/ParticipantTilePositionHelperTest.cs
VideoWeb/VideoWeb/Helpers/ParticipantTilePositionHelper.cs

VIH-6663
Add JOH role to set a tiled display name
```
[ ] Yes
[ ] No
```

VIH-6663 add JOH role to set tile display name

---

VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs
VideoWeb/VideoWeb.EventHub/Hub/IEventHubClient.cs
VideoWeb/VideoWeb.EventHub/Models/ParticipantMediaStatus.cs
VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb.UnitTests/Hub/EventHubBaseTests.cs
VideoWeb/VideoWeb.UnitTests/Hub/SendMediaDeviceStatusTests.cs
VideoWeb/VideoWeb.UnitTests/Hub/TransferRequestTests.cs
VideoWeb/VideoWeb/Extensions/ConfigureServicesExtensions.cs

VIH-6707
Add ParticipantMediaStatus message to EventHubClient.cs
```
[ ] Yes
[x] No
```

VIH-6707 Add ParticipantMediaStatus message to SignalR Client

---

VideoWeb/VideoWeb/ClientApp/src/app/app.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/app.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/connection-status.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/connection-status.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/error.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/error.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.html
VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.ts
VideoWeb/VideoWeb/ClientApp/src/typings.d.ts

VIH-6906
Error handling for pexip, due to the error being the same for user offline and pexip down ive had to implement a connection status check too.
```
[ ] Yes
[X] No
```

VIH-6906 pexip error and offline error

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.html
VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.ts

VIH-6953
ignore clicks until toggle transition is completed to avoid multiple calls to pexip before the original is complete
```
[ ] Yes
[x] No
```

VIH-6953 disable clicks during toggle transition

---

VideoWeb/VideoWeb.EventHub/Models/ParticipantMediaStatus.cs
VideoWeb/VideoWeb.UnitTests/Hub/SendMediaDeviceStatusTests.cs
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant-media-status.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/participant-panel-model.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts

VIH-6829
* Update eventhub client to include video mute status
```
[ ] Yes
[x] No
```

VIH-6829 include participant video muted in EventHub Client

---

VideoWeb/VideoWeb.AcceptanceTests/Builders/CallbackEventRequestBuilder.cs
VideoWeb/VideoWeb.EventHub/Handlers/EndpointTransferEventHandler.cs
VideoWeb/VideoWeb.EventHub/Handlers/TransferEventHandler.cs
VideoWeb/VideoWeb.EventHub/Handlers/VhOfficerCallEventHandler.cs
VideoWeb/VideoWeb.EventHub/Models/CallbackEvent.cs
VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb.UnitTests/EventHandlers/EndpointTransferEventHandlerTests.cs
VideoWeb/VideoWeb.UnitTests/EventHandlers/TransferEventHandlerTests.cs
VideoWeb/VideoWeb.UnitTests/EventHandlers/VhOfficerCallEventHandlerTests.cs
VideoWeb/VideoWeb.UnitTests/Mappings/CallbackEventMapperTests.cs
VideoWeb/VideoWeb/Mappings/CallbackEventMapper.cs

VIH-6879 
change transfer from and transfer to in CallbackEvent.cs to type string to support new room labels
```
[ ] Yes
[x] No
```

VIH-6879 Update callback contract

---

VideoWeb/VideoWeb.EventHub/Exceptions/RoomTransferException.cs
VideoWeb/VideoWeb.EventHub/Handlers/EndpointTransferEventHandler.cs
VideoWeb/VideoWeb.EventHub/Handlers/TransferEventHandler.cs
VideoWeb/VideoWeb.EventHub/Models/CallbackEvent.cs
VideoWeb/VideoWeb.Services/TestApiClient.cs
VideoWeb/VideoWeb.Services/VideoApiClient.cs
VideoWeb/VideoWeb.UnitTests/Controllers/VideoEventController/SendHearingEventTests.cs
VideoWeb/VideoWeb.UnitTests/EventHandlers/TransferEventHandlerTests.cs
VideoWeb/VideoWeb/Mappings/CallbackEventMapper.cs

VIH-6879
update callback event mapping to video API - use strings instead of enums to support new consultation rooms
```
[ ] Yes
[x] No
```

VIH-6879 update callback event mapping to video api

---

VideoWeb/VideoWeb.AcceptanceTests/Features/WaitingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/WaitingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs

- Fixes to resolve overnight 
```
[ ] Yes
[x] No
```

VIH-5552 Overnight failure fixes

---

VideoWeb/VideoWeb.AcceptanceTests/Hooks/DriverHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/HooksSequence.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs

https://tools.hmcts.net/jira/browse/VIH-7062
- Refactoring the driver hooks for local parallel test execution
```
[ ] Yes
[X] No
```

VIH-7062 update to driver hooks for local parallel execution

---

VideoWeb/VideoWeb/ClientApp/src/app/services/events.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/events.service.ts

https://tools.hmcts.net/jira/browse/VIH-6748
https://tools.hmcts.net/jira/browse/VIH-6826
check for Disconnecting state before start connection signalR
```
[ ] Yes
[ ] No
```

VIH-6748 check for disconnecting state before start connection

---

VideoWeb/VideoWeb/Controllers/MediaEventController.cs

https://tools.hmcts.net/jira/browse/VIH-7081
fix logger in MediaEnentController
```
[ X] Yes
[ ] No
```

VIH-7081 fix logger in media event controller

---

VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferenceByIdTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/CallWitnessTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/DismissWitnessTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/StartVideoHearingTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/ConsultationController/CallVideoEndpointTests.cs
VideoWeb/VideoWeb.UnitTests/Controllers/VideoEventController/SendHearingEventTests.cs
VideoWeb/VideoWeb.UnitTests/Helpers/ParticipantTilePositionHelperTest.cs
VideoWeb/VideoWeb.UnitTests/Mappings/ClaimsPrincipalToUserProfileResponseMapperTests.cs
VideoWeb/VideoWeb.UnitTests/Mappings/ConferenceResponseMapperTests.cs
VideoWeb/VideoWeb.UnitTests/stryker-config.json
VideoWeb/VideoWeb/Controllers/ConferenceManagementController.cs
VideoWeb/VideoWeb/Controllers/ConsultationsController.cs
VideoWeb/VideoWeb/Helpers/ConferenceHelper.cs
VideoWeb/VideoWeb/Mappings/ConferenceResponseMapper.cs
VideoWeb/VideoWeb/Mappings/ConferenceResponseVhoMapper.cs

https://tools.hmcts.net/jira/browse/VIH-5601
- Resolved all mutation errors
```
[ ] Yes
[x] No
```

VIH-5601 mutation issue fix

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/analogue-clock/analogue-clock.component.ts

VIH-6987
* add parentheses so isSuspended actually gets invoked
```
[ ] Yes
[x] No
```

VIH-6987 add missing parens

---

VideoWeb/VideoWeb.Services/TestApiClient.cs
VideoWeb/VideoWeb/ClientApp/src/app/home/home.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/home/home.component.ts
azure-pipelines.nightly.yml

https://tools.hmcts.net/jira/browse/VIH-7073
- removed check for iPads, 
- updated yaml for nightly tests for android.
```
[ ] Yes
[x] No
```

VIH-7073 Enable tablets for iOS and Android for all participant types

---

.gitignore
VideoWeb/VideoWeb.AcceptanceTests/Hooks/ConfigHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/Hooks/ZapHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
VideoWeb/VideoWeb.AcceptanceTests/parameters.runsettings
VideoWeb/VideoWeb.IntegrationTests/VideoWeb.IntegrationTests.csproj
VideoWeb/VideoWeb.IntegrationTests/packages.lock.json
VideoWeb/VideoWeb.UnitTests/Mappings/ClaimsPrincipalToUserProfileResponseMapperTests.cs
VideoWeb/VideoWeb/Mappings/ConferenceResponseMapper.cs

https://tools.hmcts.net/jira/browse/VIH-7058
- enabling environment switching for local test execution
```
[ ] Yes
[X] No
```

VIH-7058 enabling environment switching in local test execution

---

VideoWeb/VideoWeb/Controllers/AudioRecordingController.cs

https://tools.hmcts.net/jira/browse/VIH-7086

VIH-7086 Add auth to audio recording endpoints

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant-status-reader.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant-status-reader.ts

VIH-6524
InConsultation status for judge
```
[ ] Yes
[X] No
```

VIH-6524 InConsultation status for judge

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.html

VIH-6842
Judge status is visible to JOHs in the waiting room page
```
[ ] Yes
[x] No
```

VIH-6842 johs see judge status in wr

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html

VIH-6842
update join consultation room text
```
[ ] Yes
[x] No
```

VIH-6842 update join consultation room text

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/tests/judge-waiting-room.component.spec.ts

VIH-7123 
Bugfix - Disable IM for judges in a private consultation
```
[ ] Yes
[x] No
```

VIH-7123 Bugfix Disable IM for judges in a private consultation

---

VideoWeb/VideoWeb.AcceptanceTests/Features/JudgePrivateConsultation.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/HearingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Pages/JudgeWaitingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/JudgePrivateConsultationSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/ProgressionSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs

https://tools.hmcts.net/jira/browse/VIH-6523
https://tools.hmcts.net/jira/browse/VIH-6524
- New automation tests for Judge joining/leaving private consultation
- New automation tests for JOH's joining/leaving private consultation
```
[ ] Yes
[X] No
```

VIH-6523 automation tests for judge and joh private consultations

---

VideoWeb/VideoWeb.Services/TestApiClient.cs
VideoWeb/VideoWeb/Controllers/MediaEventController.cs
VideoWeb/VideoWeb/Extensions/ConfigureServicesExtensions.cs
VideoWeb/VideoWeb/Startup.cs

VIH-6984
Refactor tests to cover DI errors, including in controllers.
```
[ ] Yes
[x] No
```

VIH-6984 cannot select no and continue

---

VideoWeb/VideoWeb/ClientApp/src/app/services/connection-status.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/connection-status.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/error.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/MockLoggerToConsole.ts
VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/mock-connection-status.service.ts

VIH-6769
Wait for two good pings before emitting connection status as "online".
```
[ ] Yes
[x] No
```

VIH-6769  updates to reconnect button logic

---

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.ts

VIH-7137
ensure participants are unmuted when they join a consultation
```
[ ] Yes
[x] No
```

VIH-7137 ensure participants are unmuted when they join a consultation

---

VideoWeb/VideoWeb.AcceptanceTests/Features/JudgePrivateConsultation.feature
VideoWeb/VideoWeb.AcceptanceTests/Pages/JudgeWaitingRoomPage.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/JudgePrivateConsultationSteps.cs
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs

https://tools.hmcts.net/jira/browse/VIH-6842
- Tests added for Judge and JOH status in consultation
```
[ ] Yes
[X] No
```

VIH-6842 Tests added for in consultation status of Judge and JOHs

---

VideoWeb/VideoWeb.AcceptanceTests/Features/WaitingRoom.feature
VideoWeb/VideoWeb.AcceptanceTests/Steps/WaitingRoomSteps.cs

https://tools.hmcts.net/jira/browse/VIH-6758
- adding in participant status verification in JOH waiting room tests
```
[ ] Yes
[X] No
```

VIH-6758 Adding participation status checks to JOH waiting room tests

---

VideoWeb/VideoWeb.AcceptanceTests/Hooks/ConfigHooks.cs
VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json

https://tools.hmcts.net/jira/browse/VIH-7058
- Separating the test secrets from the app secrets
```
[ ] Yes
[X] No
```

VIH-7058 Separating the test secrets from the app secrets

---

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json
VideoWeb/VideoWeb.Services/BookingsApiClient.cs

https://tools.hmcts.net/jira/browse/VIH-7058
- Added missing package for Windows User Secrets
```
[ ] Yes
[X] No
```

VIH-7058 Added missing package for Windows User Secrets

---

VideoWeb/VideoWeb/ClientApp/src/app/security/participant-status.guard.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/security/participant-status.guard.ts

https://tools.hmcts.net/jira/browse/VIH-7108
Fire a Joining event for users that have the JudicialOfficeHolder role (in addition to the Representative and Individual roles)
```
[ ] Yes
[x] No
```

VIH-7108 Joining status missing for Participants

---

azure-pipelines.nightly.yml

- Temp Remove Android overnight tests
```
[ ] Yes
[X] No
```

VIH-5552 Remove Android overnight tests

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/chat/chat-base.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/models/participant-response-extend.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/services/models/session-keys.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/unread-messages/unread-messages.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-chat/vho-chat.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/tests/individual-participant-status-list.component.availability.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/tests/individual-participant-status-list.component.consultation.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-participant-status-list/judge-participant-status-list.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/tests/judge-waiting-room.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-chat/participant-chat.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/logged-user-resolve.service.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.non-event.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/wr-participant-list-shared.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/wr-participant-list-shared.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-space-routing.module.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-space.module.ts

https://tools.hmcts.net/jira/browse/VIH-7082
Fix to get Logged user in ngOnInit
```
[ X] Yes
[ ] No
```

VIH-7082 fix for ithc to get logged user

---

VideoWeb/VideoWeb/ClientApp/src/app/services/error.service.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/services/error.service.ts

https://tools.hmcts.net/jira/browse/VIH-7142
Remove subscriber from network check for waiting room
```
[X ] Yes
[ ] No
```

VIH-7142 Remove subscriber from network check for waiting room

---

VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs
VideoWeb/VideoWeb.IntegrationTests/packages.lock.json
VideoWeb/VideoWeb.Services/BookingsApiClient.cs
VideoWeb/VideoWeb.Services/TestApiClient.cs
VideoWeb/VideoWeb.UnitTests/packages.lock.json
VideoWeb/VideoWeb/Program.cs
VideoWeb/VideoWeb/VideoWeb.csproj
VideoWeb/VideoWeb/packages.lock.json

VIH-7170
Update configuration provider for SDS
```
[ ] Yes
[x] No
```

VIH-7170 add new configuration provider for sds

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.spec.ts
VideoWeb/VideoWeb/ClientApp/src/app/shared/error/error.component.ts

https://tools.hmcts.net/jira/browse/VIH-7198
Bug fix
```
[ ] Yes
[ ] No
```

VIH-7198 Bug fix for internet connection

---

VideoWeb/VideoWeb/ClientApp/src/app/shared/contact-us-folding/contact-us-folding.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.scss
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts
VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.spec.ts

VIH-7152
Add "What is a private meeting?" accordian to Waiting Room page
```
[ ] Yes
[x] No
```

VIH-7152 Explain private consultation in waiting room
