VideoWeb/Testing.Common/Helpers/BookingsApiUriFactory.cs, VideoWeb/VideoWeb.AcceptanceTests/Configuration/IConferenceRetriever.cs, VideoWeb/VideoWeb.AcceptanceTests/Hooks/DataSetupHooks.cs
In order for the queue subscriber to create the conference on the video-api, once a hearing has been created, the status needs to be updated to created on that hearing. 
```
[ ] Yes
[X] No
```
=> Updated to refliect new booking status funcionality on bookings-api

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/individual-participant-status-list/individual-participant-status-list.component.ts
[VIH-4903](https://tools.hmcts.net/jira/browse/VIH-4903)
On status change, the participant status list is refreshed so that PCs can be started after a conference is closed
```
[ ] Yes
[x] No
```
=> refresh participant status list to filter on status updates

VideoWeb/Testing.Common/Helpers/VideoApiUriFactory.cs, VideoWeb/VideoWeb.AcceptanceTests/Helpers/SeleniumEnvironment.cs, VideoWeb/VideoWeb.AcceptanceTests/Hooks/DataSetupHooks.cs, VideoWeb/VideoWeb.AcceptanceTests/Pages/CommonPages.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/PracticeVideoHearingSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/PrivateConsultationSteps.cs
- Changed the way closed conferences are deleted (workaround until the delete endpoint is fixed). - Extended timeouts for failing saucelabs tests
```
[ ] Yes
[X] No
```
=> Test cleanup workaround

VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts
[VIH-4614](https://tools.hmcts.net/jira/browse/VIH-4614)
- Raise a failed self test event on a bad score immediately rather than waiting for the user to click continue
```
[ ] Yes
[x] No
```
=> raise self test failure event immediately when a bad score is returned.

VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts
No Jira
removed : logging for the self test as participant id does not exist for clerk/rep journey
```
[ ] Yes
[x] No
```
=> SelfTest Error(Clerk/Rep/Judge Journey)

VideoWeb/VideoWeb.EventHub/Handlers/Core/EventHandlerBase.cs, VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs, VideoWeb/VideoWeb.UnitTests/Controllers/VideoEventController/SendHearingEventTests.cs, VideoWeb/VideoWeb/ClientApp/src/app/app.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/api/config.service.spec.ts, VideoWeb/VideoWeb/Controllers/VideoEventsController.cs
https://tools.hmcts.net/jira/browse/VIH-5422
VIH-5422: HOTFIX VideoWeb: Fix logging in the callback end point
added logging for the VideoEventsController.
modified the endpoint to return an OkResult.
updated app.component for set focus on main container (removed Render2 as its obsolete)
update config.spec.ts to use of instead of obsolete Observable.
```
[ ] Yes
[x] No
```
=> VIH-5422: HOTFIX VideoWeb: Fix logging in the callback end point

VideoWeb/VideoWeb.AcceptanceTests/Features/InstantMessaging.feature, VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature, VideoWeb/VideoWeb.AcceptanceTests/Pages/AdminPanelPage.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/InstantMessagingSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/VhoHearingListSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/VideoHearingsOfficerCallSteps.cs
- Added fixes for final few failing tests
- Added delays as the VHo call tests were clicking the link too fast
- Edited the test as Kinly have now removed the link to VHO call when users are in PC or hearing
- Skipped a step on Safari due to a specific issue with Safaridriver
```
[ ] Yes
[X] No
```
=> Added fixes for final few failing tests

VideoWeb/VideoWeb.AcceptanceTests/Hooks/DriverHooks.cs, VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.Services/VideoApiClient.cs
- Fix for the null object on browser teardown issue for queue subscriber tests
```
[ ] Yes
[X] No
```
=> testfix/VIH-5552 : Fixed teardown method for tests without a browser

VideoWeb/VideoWeb.AcceptanceTests/Data/Test.cs, VideoWeb/VideoWeb.AcceptanceTests/Features/HearingRoom.feature, VideoWeb/VideoWeb.AcceptanceTests/Features/VideoHearingsOfficerCall.feature, VideoWeb/VideoWeb.AcceptanceTests/Steps/BrowserSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/Steps/InstantMessagingSteps.cs, VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj
- Removed refresh
- Added a switch for when Judge is already connected to the Iframe 
- Extended waits
```
[ ] Yes
[X] No
```
=> VIH-5255 Improve hearing room tests

VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts
https://tools.hmcts.net/jira/browse/VIH-5896
Fix one issue with participant id, if participant is null we use independent self test score request and in message should not be used participant id(as it's undefined) 
```
[ X] Yes
[ ] No
```
=> VIH-5896 Check for null participant object

VideoWeb/VideoWeb.AcceptanceTests/Features/Filters.feature, VideoWeb/VideoWeb.AcceptanceTests/Hooks/ZapHooks.cs, VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, azure-pipelines.nightly.yml
- Edge is supported but not by automation tests. Removing from overnight tests
```
[ ] Yes
[X] No
```
=> VIH-5255 Remove test for Edge from overnights

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VIH-6176
* judge self-view open by default
* judge manually disconnected from pexip on close hearing
* mute non-judge participants after countdown is complete
```
[ ] Yes
[x] No
```
=> VIH-6176 hearing room defaults

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
VIH-6372
* End button renamed to close
* Unmutes a conference after manually unmuting individuals after a conference mute
```
[ ] Yes
[x] No
```
=> VIH-6372 unmute individuals after conference mute

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
VIH-6372
* mute the conference after the last person is muted manually
* safely updated button to unmute all and correctly unmutes all participants
```
[ ] Yes
[x] No
```
=> VIH-6372 trigger conference mute and unmute after last manual mute and unmute

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.scss
VIH-6283
* set grid cell width to 40px rather than auto to ensure all rows have the same width
```
[ ] Yes
[x] No
```
=> VIH-6283 set icon width rather than use auto

VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts
VIH-6661
* do not wait for test score response. this allows the app to move on without having to wait for a score to return
```
[ ] Yes
[x] No
```
=> VIH-6661 do not wait for test score response

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
VIH-6593
Fixed bug where a second witness being called in would freeze at warning screen. Multiple witnesses can now be called in at once.
```
[ ] Yes
[x] No
```
=> VIH-6593 Fixed bug to call multiple witnesses

VideoWeb/VideoWeb/ClientApp/Dockerfile, VideoWeb/VideoWeb/Dockerfile, VideoWeb/VideoWeb/Startup.cs, VideoWeb/VideoWeb/appsettings.Development.json, VideoWeb/docker-compose.override.yml
VIH-6788
Tested docker containers run for production use
angular container changes would be needed if we were to use for local dev (to copy the pacakge json and resore as part of build to speed up startup times. Also only seemed to be able to get the `ngBaseUri` going when i used `links` which is deprecated but not a blocker for the prod build
```
[ ] Yes
[X] No
```
=> VIH-6788 - docker testing

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, VideoWeb/VideoWeb.Common/Caching/ConferenceCache.cs, VideoWeb/VideoWeb.Common/Caching/DistributedConferenceCache.cs, VideoWeb/VideoWeb.Common/Caching/IConferenceCache.cs, VideoWeb/VideoWeb.Common/Models/CivilianRoom.cs, VideoWeb/VideoWeb.Common/Models/Conference.cs, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.Contract/VideoWeb.Contract.csproj, VideoWeb/VideoWeb.EventHub/VideoWeb.EventHub.csproj, VideoWeb/VideoWeb.IntegrationTests/packages.lock.json, VideoWeb/VideoWeb.UnitTests/ConferenceCacheTest.cs, VideoWeb/VideoWeb.UnitTests/Controllers/VideoEventController/BaseSendHearingEventTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/VideoEventController/SendHearingEventTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/VideoEventController/SendVmrHearingEventTests.cs, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb.sln, VideoWeb/VideoWeb/Controllers/VideoEventsController.cs, VideoWeb/VideoWeb/Extensions/ConferenceEventRequestExtensions.cs, VideoWeb/VideoWeb/Extensions/ConfigureServicesExtensions.cs, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json
VIH-7176 
* When a participant joins a VMR, the transfer event returns room id as the participant. When this happens, we need to iterate over each participant in the VMR and handle the event.
* When a participant joins or leaves a room, the cache needs to be updated to reflect this since the cache is only updated when the `GetConferenceById` is called. This would not happen once the participant is in the WR
```
[ ] Yes
[x] No
```
=> VIH-7176 handle room events

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/select-hearing-layout/select-hearing-layout.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/select-hearing-layout/select-hearing-layout.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/select-hearing-layout/select-hearing-layout.component.ts
https://tools.hmcts.net/jira/browse/VIH-7468
Accessibility Fixes
GDS javascript overrides the span with a button. This change changes it back to the translated text. Has to be done from ts or its done before GDS runs.
```
[ ] Yes
[ x] No
```
=> VIH-7468 Accessibility Fixes

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.spec.ts
https://tools.hmcts.net/jira/browse/VIH-6902
Modified the participant-waiting-room component so that Interpreter or Interpretee cannot start a private consultation or they cannot join a private consultation without an invite.
```
[ ] Yes
[X ] No
```
=> VIH-6902 Interpreter-Interpretee Private Consultations

VideoWeb/VideoWeb.UnitTests/Mappings/SharedParticipantRoomMapperTests.cs, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts, VideoWeb/VideoWeb/Mappings/SharedParticipantRoomMapper.cs
VIH-7482
* ensure tile positions are unique
* make sure video stream isn't muted when browser is refreshed mid-hearing
```
[ ] Yes
[x] No
```
=> VIH-7482 video hearing bug fixes for tile position and muted video element

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.eventhub.events.spec.ts
VIH-7453
* revert leave consultation from UI on hearing start
* The witness attempts to leave a consultation room even if they are not in one
* The CountDownEventHandler in VideoAPI will transition witnesses out of consultation rooms
```
[ ] Yes
[x] No
```
=> VIH-7453 revert leave consultation from UI on hearing start

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/unread-messages-participant/unread-messages-participant.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/unread-messages-shared/unread-message-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/unread-messages/unread-messages.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/unread-messages/unread-messages.component.ts
VIH-7548
* unread components need to handle incoming messages differently
handle ims for a participant when the unread array is empty
```
[ ] Yes
[x] No
```
=> VIH-7548 handle ims for participant when unread array is empty

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-global-styles.scss, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.non-event.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts, azure-pipelines.yml
truncate very long case names and replace them with a tooltip to see all
VIH-7569
* truncate long case names in hearing room screen
* optionally display a show more text with displays the full case name as a tooltip
```
[ ] Yes
[x] No
```
=> VIH-7569 truncate long case names in hearing room screen

VideoWeb/VideoWeb/ClientApp/src/app/shared/pipes/multiline.pipe.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/panel-model-base.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/participant-panel.model.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts
VIH-7612 
* Update participant panel order list logic to use user and hearing roles where possible
* Display the HMCTS crest icon for panel members
```
[ ] Yes
[x] No
```
=> VIH-7612 order panel members after judge and before the rest

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-status/participant-status.component.scss
VIH-7670
break all for the participant list in the VHO Command Centreto stop the name and status from overlapping
```
[ ] Yes
[x] No
```
=> VIH-7670 participant status and name overlapping in VHO CC

VideoWeb/VideoWeb.AcceptanceTests/Steps/DataSetupSteps.cs
VIH-7699 - Specflow expects that the backing method has the same set of parameters as the Gherkin, so if the backing method has additional parameters it will not be recognised.
Example:
Given I have a hearing in (.*) minutes time
requires a method with the same
method(int minutes)
It's a **Specflow issue** that it does not recognise that method(int minutes, bool value = false ) can be called.
https://tools.hmcts.net/jira/browse/VIH-7699
```
[ ] Yes
[X ] No
```
=> VIH-7699 - Specflow expects that the backing method has the same set of parameters

VideoWeb/VideoWeb.AcceptanceTests/Steps/HearingRoomSteps.cs
This test was locating users on the VHO page by ID however, for the format of the id has changed as this comes from Kinly.
The change is to locate the user by their display name as used by other AC tests.
https://tools.hmcts.net/jira/browse/VIH-7654
This test was locating users on the VHO page by ID however, for the format of the id has changed as this comes from Kinly.
The change is to locate the user by their display name as used by other AC tests.
```
[ ] Yes
[x] No
```
=> VIH-7654 Get users from VHO page by display name instead of id

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/linked-participant-panel-model.ts
https://tools.hmcts.net/jira/browse/VIH-7795
- Changed a find to return the first non-interpreter in the group of linked participants.
```
[ ] Yes
[x] No
```
=> VIH-7795 Participant list not loading in Judge view during Hearing

azure-pipelines.beta.yml, azure-pipelines.nightly.yml, azure-pipelines.release.yml, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-7538
vh-video-web requires a new kinly API key to generate jwt tokens. This will be exclusively used only vh-video-web
vh-video-api will keep the existing kinly api key
```
[x] Yes
[ ] No
```
=> VIH-7538 - Kinly HeartBeat API key added - pipelines

VideoWeb/VideoWeb/ClientApp/src/app/services/device-type.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/device-type.service.ts
VIH-7917
we are looking for "mac" os rather than "ios" in isIpad method, but I think we still need "mac" for some other apple devices so I added "ios"
```
[ ] Yes
[x] No
```
=> VIH-7917 iPad users on Safari are seeing the "unsupported device" page

VideoWeb/VideoWeb/ClientApp/src/app/services/unload-detector.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/unload-detector.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.eventhub.events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/tests/judge-waiting-room.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.analogue-time.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.eventhub.events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.spec.ts
https://tools.hmcts.net/jira/browse/VIH-7967
https://tools.hmcts.net/jira/browse/VIH-7968
https://tools.hmcts.net/jira/browse/VIH-7976
- Added a "unload detector" service which detects events (window / document) that should cause the application to unload resource i.e. disconnect from pexip.
- Refactored the three waiting rooms to consume the new service.
```
[ ] Yes
[x] No
```
=> VIH-7967 PM video feed is duplicated in hearing when user refresh on iPad

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/notification-toastr.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json, VideoWeb/VideoWeb/ClientApp/src/styles.css
VIH-7657
Change toastr to display as white when in consultation. Put a space between role and party for a natural breakpoint. Also adding a word wrap in case of particularly long words
```
[ ] Yes
[x] No
```
=> VIH-7657 toastr style issues

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, VideoWeb/VideoWeb.IntegrationTests/VideoWeb.IntegrationTests.csproj, VideoWeb/VideoWeb.IntegrationTests/packages.lock.json, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8120
Required VideoApi.Client update on video web. (VHO command center failing when retrieving hearings with Staff Member participants)
```
[ ] Yes
[x] No
```
=> VIH-8120 VideoApi.Client update

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts
https://tools.hmcts.net/jira/browse/VIH-8273
- hiding screen share button for all devices other than desktop/mac
```
[ ] Yes
[x] No
```
mobile devices:
ipad:
desktop:
=> VIH-8273 changed logic to only show share screen for desktop devices

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
https://tools.hmcts.net/jira/browse/VIH-8405
prevent pexip from disconnecting until atleast one attempt has been made to connect back to eventhub
```
[ ] Yes
[x] No
```
=> VIH-8405 prevents disconnection from pexip when eventhub connection is lost

VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs, VideoWeb/VideoWeb.UnitTests/Hub/DisconnectionTests.cs, VideoWeb/VideoWeb/ClientApp/src/app/services/events-hub.service.ts, VideoWeb/VideoWeb/Extensions/ConfigureServicesExtensions.cs
https://tools.hmcts.net/jira/browse/VIH-8405
- amending signalr configuration for the server time out. Currently its set to 5 mins, however its recommended to have the keep alive timeout set to half of what the server time out is. Also reducing the timeout to 1 minute
- Updated the log level for when an exception occurs disconnecting from eventhub
**Does this PR introduce a breaking change?** 
```
[ ] Yes
[x] No
```
=> VIH-8405 update signalr config

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts
[VIH-8578](https://tools.hmcts.net/jira/browse/VIH-8578)
- As suggested by Alan (from Pexip) we have implemented a method to clean up and recreate the PexRtc instance when the server disconnects, the client disconnects or a (pexip) error is raised. This should hopefully resolve the "Invalid Token" issue. Pexip is not designed to use the same client instance when reconnecting a call the was previously closed.
```
[ ] Yes
[x] No
```
=> VIH-8578 clean up pex rtc when disconnecting from Pexip

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8599
Add missing translations for SSCS types and roles:
SSCS Tribunal	- Tribiwnlys SSCS
Support Worker -Gweithiwr Cymorth
Family Member - Aelod o'r Teulu
Friend - Ffrind
Joint Party - Parti ar y Cyd
Appraiser - Gwerthuswr
Disability Member (DQM) - Aelod Anabledd (DQM)
Financial Member - Aelod Cyllidol
Legal Member - Aelod Cyfreithiol
Medical Member - Aelod Meddygol
DWP Presenting Officer - Swyddog Cyflwyno'r DWP
```
[ ] Yes
[ x] No
```
=> VIH-8599 Welsh translations for SSCS types and roles

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
https://tools.hmcts.net/jira/browse/VIH-8706
- Reset remote mute in local store when host joins paused hearing when other host started the hearing.
- Resetting the remote mute status in the component store when the participant panel loans instead of reloading the waiting room.
```
[ ] Yes
[x] No
```
=> VIH-8706 Reset remote mute in local store when host joins paused hearing

VideoWeb/VideoWeb/ClientApp/src/app/shared/force-play-video.directive.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/force-play-video.directive.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.non-event.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VIH-8707 
Adding destroyed property to force play directive that prevents calling play on the element after ngOnDestroy has already been called.
```
[ ] Yes
[x] No
```
=> VIH-8707 Don't play video if parent element has been destroyed

azure-pipelines.yml
There is an issue with the nightly pipelines where the binaries used will have been deleted being obsolete, this will increase the frequency of the builds to avoid this.
```
[ ] Yes
[ ] No
```
=> VIH-8748 - Increase Frequency of Pipeline builds

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.ts
https://tools.hmcts.net/jira/browse/VIH-8745
Fixes an issue where the endpoint participants are displayed before witnesses in the JOH consultation.
Also updates the ordering of the participants in the JOH consultation to match those in the waiting room.
This involves splitting up of witnesses and observers, so that observers can be displayed at the bottom.
```
[ ] Yes
[x] No
```
=> VIH-8745 Endpoint is displayed before witness in JOH consultation

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/linked-participant-panel-model.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/linked-participant-panel-model.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/panel-model-base.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
https://tools.hmcts.net/jira/browse/VIH-8756
Fixes an issue where if a participant is dismissed from a hearing with their hand raised, the hand is lowered but only visible to the host that dismissed them - the second host still sees their hand raised.
Currently the hand is lowered and spotlight removed through the dismissed() function, which sets the handRaised and isSpotlighted properties to false. These are only applied to the person doing the dismissal.
To fix the issue, instead of setting the flags, we lower the hand and remove from spotlight using the pexip API calls. This streams an event to all observers and also ensures that the hand raised and spotlighted states are persisted if the participant is to re-join after being dismissed.
**Does this PR introduce a breaking change?** …
=> VIH-8756 - Hand raised status persisted when QL/Witness is dismissed

VideoWeb/VideoWeb/ClientApp/src/app/services/conference/video-control-cache.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/video-control-cache.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
https://tools.hmcts.net/jira/browse/VIH-8702
Moved the VideoControlCacheService constructor logic inside of a function 'initHearingControlState' which can be re-invoked on the participant-panel ngOnInit; this will force the hearingControlStates object to be set to the latest cache value upon entering the hearing
```
[ ] Yes
[x ] No
```
=> VIH-8702 Fix for handraised icon not persisting for the 2nd host joining the hearing

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
https://tools.hmcts.net/jira/browse/VIH-8720
This addresses an issue when a judge calls the witness and interpreter into a hearing. A staff member then joins the hearing. The vmr unmutes locally. The judge then leaves the hearing. The vmr then mutes locally again. When the judge re-joins the hearing the vmr should be muted.
```
[ ] Yes
[x ] No
```
=> VIH-8720 witness interpreter vmr incorrect mic status

VideoWeb/VideoWeb/ClientApp/src/app/shared/mappers/participant-panel-model-mapper.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/mappers/participant-panel-model-mapper.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/panel-model-base.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/wr-participant-list-shared.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/wr-participant-list-shared.component.ts
https://tools.hmcts.net/jira/browse/VIH-8763
Updates the sorting of participants within video web and makes it consistent across all rooms (waiting room, consultation room and hearing room).
- For each group in the hierarchy (panel members, staff members etc) order by display name
- Order non-judge participants by case group type (applicant, respondent etc) then by name, or if not available, display name. Keep interpretee above the interpreter, and QL participants at the bottom
- For the hearing room, order panel members by hearing role then name, to keep panel members together, and wingers together
- Display QL observers below observers
- Add test coverage for all rooms and test cases
```
[ ] Yes
[x] No
```
=> VIH-8763 Participants are not sorted by hierarchy in WR, consultation and hearing

VideoWeb/VideoWeb/ClientApp/package-lock.json, VideoWeb/VideoWeb/ClientApp/package.json, VideoWeb/VideoWeb/ClientApp/src/app/services/logging/loggers/app-insights-logger.service.ts
https://tools.hmcts.net/jira/browse/VIH-8788
Updates the microsoft/applicationinsights-web package to the latest version. This contains bug fixes to fix issues with the application insights logs not being fully populated for exceptions.
We also now pass "exception" rather than "error" to trackException as "error" has been deprecated.
```
[ ] Yes
[x] No
```
=> VIH-8788 - Update applicationinsights-web package to 2.7.3

VideoWeb/VideoWeb/Extensions/ConfigureAuthSchemeExtensions.cs
https://tools.hmcts.net/jira/browse/VIH-8774
Fix for production validation errors.
This was happening because we are trying to authenticate the request against every registered scheme applied to a policy. The issue arose because we use more than one JWT and only one can be used on any given request.
This fix means every time the authorization policy is hit, it will execute one of the schemes based on the content of the token.
```
[ ] Yes
[x] No
```
=> VIH-8774 Fix for production validation errors

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8805
Adds missing translations for the new case role groups.
```
[ ] Yes
[x] No
```
=> VIH-8805 Add missing translations for war pensions appeals

VideoWeb/VideoWeb/ClientApp/src/app/services/conference/video-control-cache.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/video-control-cache.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.ts, VideoWeb/VideoWeb/ClientApp/src/scripts/pexrtc.js
Updated all cache control service SET functions, to first reinitialise the hearing control state, then pass their update in as a callback, to ensure update to cache is in sync first. Also added new 'clearHandRaiseStatusForAll' function that clears the hand raise status in the cache for all participants. This is also called when pausing or suspending a hearing, as cache will become out of sync, when next pexip connection is made when restarting the hearing and control states are reset. Also added supporting tests.
Finally added a Handshake function, that subscribes to a new participant joining, this is to force an interaction with a second host and make sure they receive a ParticipantUpdate request from each participant when they join, to cover the off chance that the cache is still …
=> VIH-8702 Fix for handraised status not persisting for 2nd host

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.ts
https://tools.hmcts.net/jira/browse/VIH-8702
https://tools.hmcts.net/jira/browse/VIH-8861
Have updated the hearing control logic to now fully rely on an update from the 'newParticipantEnteredHandshake'. In the previous iteration this could be sent too early; meaning it was a little flakey as a 2nd host would re-init the control values after participants had sent their updates. So have added a 3 second delay to give them time. Have stripped out unnecessary updates to video-control-cache service. Have also updated LowerAllHands, judge button to call lowerHandById, forEach linked participant as well as ClearAllBuzz. This is because linked participants were not receiving the participantUpdate event to lower their hand via this pexip control.
**Does this PR introduce a breaking change?** …
=> VIH-8861 video control states not persisting(vmr)

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/participant-status/participant-status.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/vho-shared/participant-status-base/participant-status-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-context-menu/judge-context-menu.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-context-menu/judge-context-menu.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-context-menu/judge-context-menu.component.ts, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-8753
Applies some additional changes necessary after adding the Criminal Injuries Compensation case type.
- Fixes an issue with the hearing role being displayed instead of the case type group for panel members in the hearing room context menu tooltip. Until now panel members have had a hearing role of "Panel Member" so this hasn't been a problem - the same text has been displayed. This is resolved by not showing the case role text for panel members in addition to judges.
- Fixes an issue with lay members and medical members showing in the wrong position in the command centre participant list. This was due to them not being recognised as panel members.
```
[ ] Yes
[x] No
```
=> VIH-8753 Video web fixes for Criminal Injuries Compensation case type

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-context-menu/judge-context-menu.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-context-menu/judge-context-menu.component.ts
https://tools.hmcts.net/jira/browse/VIH-8821
Fixes an error when members without a case type group are in a hearing.
The showHearingRole() function (introduced recently) is using a flaky method of determining whether the participant is a judge or panel member. Updated it to use the hearing role instead of the case group type.
```
[ ] Yes
[x] No
```
=> VIH-8753 Fix judge context menu error

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
https://tools.hmcts.net/jira/browse/VIH-8854
Set the hasTriedToLeaveConsultation bool to false within the 'accepted' consultation invite, event handler. This would normally be done when clicking to join a consultation button, however this is step is missed when being invited to one instead. This would result in the video not being unmuted, when they rejoin.
```
[ ] Yes
[ x] No
```
=> VIH-8854 Audio lost when invited to a consultation

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/wr-participant-list-shared.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/wr-participant-list-shared.component.ts
https://tools.hmcts.net/jira/browse/VIH-8934
When repositioning the interpreter underneath the interpretee, all the indices shifted up one, so upon removing the old interpreter position, the wrong participant would be removed, instead leaving two instances of the interpreter.
```
[ ] Yes
[x ] No
```
=> VIH-8945 fix for duplicating interpreter

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
https://tools.hmcts.net/jira/browse/VIH-8937
Fixes some issues with the panel member hearing controls which happen after a new participant is added to the hearing.
- States are reset (raised hand is lowered, muted is changed to unmuted, spotlight is removed)
- Controls don't work (clicking on them doesn't toggle)
There is a splice operation in place to replace a panel member with one from another array. However this panel member has been mapped to a different object type and doesn't have the state (muted, hand raised etc) properties, so we need to re-apply them for the states to be persisted.
We also need to re-assign a pexip id for the controls to work.
```
[ ] Yes
[x] No
```
=> VIH-8937 Fix for issues with panel member hearing controls after participant added

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/tests/participant-waiting-room.component.spec.ts
https://tools.hmcts.net/jira/browse/VIH-8974
The current implementation had no restrictions on what type of user 'Individuals' could invite into the private consultation. Have added an additional rule along side the 'CanInvite' check. Aswell as the list of participants a private consultation can be started with.
```
[ ] Yes
[x] No
```
=> VIH-8974 anyone can invite into a consultation bug

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
https://tools.hmcts.net/jira/browse/VIH-9039
updated getPrivateConsultationParticipants method, and renamed, as it's used by more than just private consultations, also JOHConsultation ect.. added in conditional filter and updated tests
```
[ ] Yes
[ x] No
```
=> VIH-9039 exempt participants from private consultation panel

VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/venue-list.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/venue-list.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/vh-officer-venue-list/vh-officer-venue-list.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/venue-list/vh-officer-venue-list/vh-officer-venue-list.component.ts
https://tools.hmcts.net/jira/browse/VIH-9854
Fixes for some issues when selecting the 'Allocated to me' option in the CSO list for viewing hearings.
- Use a case-insensitive search when looking up the logged in user in the CSO list
- If the user isn't found, remove the 'Allocated to me' option
- When navigating back to the page and re-applying the previous filter, de-select the user if they no longer exist in the list
- Refactor by moving `getLoggedInCso` into a separate function
```
[ ] Yes
[x] No
```
=> VIH-9854 Fix Allocated to me issues

azure-pipelines.yml
The AC tests were inadvertently disabled in a previous commit, changing them back to true
```
[ ] Yes
[x] No
```
=> VIH-0000 Run AC tests in reform pipeline

VideoWeb/VideoWeb/ClientApp/src/app/app.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/app.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/quick-links/quick-links.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/logging/loggers/app-insights-logger.service.ts
https://tools.hmcts.net/jira/browse/VIH-9941
Fixes an error when using the quick links url to join a hearing.
This reverts some changes made as part of the angular 15 upgrade. By using `combineLatest` with the idp and security provider, it can return an invalid combination (quick link config + oidc service) as they can change independently, causing the error. To remedy this, revert back to the original mechanism where we get the client settings, and then the idp and security provider together.
Also removes an unused method (`checkAuth`) and its test.
```
[ ] Yes
[x] No
```
=> VIH-9441 Fix for quick links error

VideoWeb/VideoWeb.AcceptanceTests/VideoWeb.AcceptanceTests.csproj, VideoWeb/VideoWeb.AcceptanceTests/packages.lock.json, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForStaffMemberTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForVHOfficerTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/UserDataControllerTest.cs, VideoWeb/VideoWeb.UnitTests/Extensions/ConferenceForVhOfficerResponseExtensionsTests.cs, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/Controllers/ConferencesController.cs, VideoWeb/VideoWeb/Controllers/UserDataController.cs, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json, charts/vh-video-web/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-9988
Updated implementation where conferences are queried with hearing venue names, via video api - to query via booking api instead. Added test coverage
```
[ ] Yes
[X] No
```
=> VIH-9988 video web querying venues needs refactoring

VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs, VideoWeb/VideoWeb.EventHub/Services/ConferenceManagementService.cs, VideoWeb/VideoWeb.UnitTests/Builders/ConferenceCacheModelBuilder.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/ConferenceManagementControllerTestBase.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceManagement/DismissParticipantTests.cs, VideoWeb/VideoWeb.UnitTests/Hub/EventHubBaseTests.cs, VideoWeb/VideoWeb.UnitTests/Hub/UpdateParticipantHandStatusTests.cs, VideoWeb/VideoWeb.UnitTests/Services/ConferenceManagementServiceTests.cs, VideoWeb/VideoWeb/ClientApp/src/app/services/logging/loggers/app-insights-logger.service.ts, VideoWeb/VideoWeb/ClientApp/src/index.html, VideoWeb/VideoWeb/Controllers/ConferenceManagementController.cs, VideoWeb/VideoWeb/Extensions/ConfigureServicesExtensions.cs
* Invoke hand lowered via EventHubClient after dismissal (forcing UI to lower hand in instance where message is lost)
* Set rule to ignore connection check request to app insights
* update incorrect favicon paths
```
[ ] Yes
[x] No
```
=> VIH-8905 Invoke hand lowered via EventHubClient after dismissal

VideoWeb/VideoWeb.Common/Models/Conference.cs, VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs, VideoWeb/VideoWeb.UnitTests/Hub/SendMessageTests.cs, azure-pipelines.sds.pr-release.yml
VIH-10308
When a SM with the VHO role joins a hearing, they will pass the condition `IsParticipantInConference`. This rule should be updated to check the role is not staff member so that the user can still be treated with their VHO role
=> VIH-10308 Bugfix unable to send IM as Staff Member once joined to a conference

VideoWeb/VideoWeb.Common/UserProfileService.cs, VideoWeb/VideoWeb.UnitTests/AuthenticationSchemes/EJudiciarySchemeTests.cs, VideoWeb/VideoWeb.UnitTests/Builders/ClaimsPrincipalBuilder.cs, VideoWeb/VideoWeb.UnitTests/Builders/EjudClaimsPrincipalBuilder.cs, VideoWeb/VideoWeb.UnitTests/Hub/UserProfileServiceTests.cs, VideoWeb/VideoWeb.UnitTests/Mappings/ClaimsPrincipalToUserProfileResponseMapperTests.cs, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/host-hearing-list/host-hearing-list.component-base.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/host-hearing-list/host-hearing-list.component-base.ts, VideoWeb/VideoWeb/Mappings/ClaimsPrincipalToUserProfileResponseMapper.cs
https://tools.hmcts.net/jira/browse/VIH-10338
The GivenName and Surname claims don't exist for Ejud issued tokens, so add handling for these being null.
Also show the Display Name on the hearing list page when the First Name or Last Name are null.
=> VIH-10338 Fix - unable to log in to video web with ejud account

VideoWeb/VideoWeb/ClientApp/src/app/vh-officer/command-centre/command-centre.component.scss
https://tools.hmcts.net/jira/browse/VIH-10354
Fix overlapping elements on the command centre page.
The cause is these height styles which apply a fixed height to the container. This styling had been added as part of a previous ticket to add a scrollbar. It is not needed as it is already part of the `im-participant-list` css class.
```
.im-participant-list {
@include govuk-grid-column(one-third);
overflow-y: auto;
height: 70vh;
max-height: 100vh;
}
```
=> VIH-10354 VHO Command centre Alerts section zoom in overlapping

VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForHostTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForIndividualTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForStaffMemberTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForVHOfficerTests.cs, VideoWeb/VideoWeb/Controllers/ConferencesController.cs
https://tools.hmcts.net/jira/browse/VIH-10375
When bookings api returns no hearings for a vho or staff member, return an empty list instead of throwing a 500 error
Also update the error handling for querying by individual and host for consistency
=> VIH-10375 Return empty list instead of 500 error when no hearings exist

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts
https://tools.hmcts.net/jira/browse/VIH-10603
Fixes an issue where when the host requests to start a hearing muted, their mic is still audible.
The culprit is the `|| this.startWithAudioMuted`. Because `this.isAudioMuted` gets set to true, a call is not made to kinly API to physically mute the participant after the hearing countdown finishes, even though the icon shows they are muted.
=> VIH-10603 Fix - mic still audible when host chooses to enter hearing muted

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/cy.json, VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
https://tools.hmcts.net/jira/browse/VIH-10623
Adds some case type translations that were missing
=> VIH-10623 Add missing case type translations

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
VIH-10642
When updating a participant list, a user may need to re-connect to join as a VMR (if they are linked) or re-connect as a single participant (if they are unlinked)
=> VIH-10642 Reconnect user when linked participant list for user changes

VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.eventhub-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/waiting-room-base.component.ts
https://tools.hmcts.net/jira/browse/VIH-10653
Removes a redundant call to add a newly added endpoint to the conference endpoints array. The array has already been updated by this point as part of `getConference`, so no need to add it to the array a second time
=> VIH-10653 Fix for newly added endpoints appearing in participants list twice

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel.component.ts
https://tools.hmcts.net/jira/browse/VIH-10664
Fixes an issue where adding a second panel member to a hearing once it is in session causes the 2 panel members to appear in the participants list twice.
There should only be one panel member model in the list, because all panel members are grouped under one item. So don't add a second one if one already exists
=> VIH-10664 Fix for newly added panel members appearing in participants list twice

VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/models/hearing.ts, VideoWeb/VideoWeb/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-10640
removed redundant error catch
=> VIH-10640 - pm waiting room page unable to auto update and throwing an unexpected error when edit last minute party during hearing

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts
VIH-10709 
* handle null for pexipApi call object
* using an arrow function in the subscribe call. This will ensure that `this` inside the subscribe callback refers to the component instance. the current implementation meant that `this` was `undefined` when debugging and so the code blocks would not trigger as expected
=> VIH-10709 bug fix toggle mute not reliable

VideoWeb/VideoWeb.Common/Caching/DistributedUserClaimsCache.cs, VideoWeb/VideoWeb.Common/UserProfileService.cs, VideoWeb/VideoWeb.EventHub/Hub/EventHubClient.cs, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/reducers/conference.reducer.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/reducers/conference.reducer.ts
[VIH-10734](https://tools.hmcts.net/jira/browse/VIH-10734)
**Claims Cache Bug 1**
If a user logs into video web with no roles to map, this resulted in the mappers failing and throw an unhandled exception resulting in the user to be redirected to the not authorised page.
Impact: the disconnect function that clears the cache did not execute. If a user were to change their role and sign back in, the cache would find the user and return an empty list. As before it would cause the claims mapper to fail and the user is caught in a loop where they cannot connect safely enough to trigger the disconnect function and so stuck with no claims and held in the not authorised page until the cache clears after 4 hours.
**Claims Cache Bug 2**
The disconnect function obfuscated the username before calling …
=> VIH-10734 Bugfix claims and reducers

VideoWeb/VideoWeb.UnitTests/AuthenticationSchemes/EJudiciarySchemeTests.cs, VideoWeb/VideoWeb/AuthenticationSchemes/EJudiciaryScheme.cs
https://tools.hmcts.net/jira/browse/VIH-10746
A change was made recently to prevent panel members accessing the judge waiting room, and vice versa. Subsequently johs on V2, who can double as both panel members and judges, require both the judge and judicial office holder claims in order to access the waiting room as either role
=> VIH-10746 Fix for not being able to access panel member waiting room as ejud user

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/wr-participant-list-shared.component.ts
VIH-10787
* Fix display of participant list in waiting room when there are endpoints present
=> VIH-10787 bugfix endpoints not listed when no participants are booked in a hearing

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/private-consultation-room-controls/private-consultation-room-controls.component.html
fix the typo for ngIf which is case sensitive
VIH-10871 
change device button not appearing in consultation or hearing. this is due to a typo where `ngIf` is case-sensitive
=> VIH-10871 change device button not appearing in consultation or hearing

VideoWeb/VideoWeb.Common/AppRoleService.cs, VideoWeb/VideoWeb/AuthenticationSchemes/AadSchemeBase.cs
VIH-10868
* move Sempahores out from AadSchemeBase.cs and into AppRoleService.cs to check cache first before calling api, and then check cache again when the semaphore is gained
* Increase from 1 to 3 max concurrent requests. On app start the web app makes multiple concurrent requests, this should help alleviate blocking a hot code path
=> VIH-10868 refactor semaphores out of hot code path

VideoWeb/VideoWeb.UnitTests/Controllers/ParticipantController/GetParticipantsByConferenceIdTest.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ParticipantController/GetParticipantsWithContactDetailsByConferenceIdAsync.cs, VideoWeb/VideoWeb/Controllers/ParticipantsController.cs
https://tools.hmcts.net/jira/browse/VIH-10833
Reverts a recent change to fetching participants - use `ForceGetConference` to get them from the db instead of the cache when building the participants list, to ensure participants have the latest statuses in the hearing
=> VIH-10833 Fix for quick link users showing as disconnected when joining after the judge

VideoWeb/VideoWeb/ClientApp/src/app/services/conference/participant.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/tests/judge-waiting-room.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/video-call-models.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/actions/conference.actions.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/effects/conference.effects.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/effects/conference.effects.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/effects/video-call.effects.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/effects/video-call.effects.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/models/vh-conference.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/reducers/conference.reducer.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/reducers/conference.reducer.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/selectors/conference.selectors.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base.component.video-call-events.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-space.module.ts, VideoWeb/VideoWeb/ClientApp/src/typings.d.ts
VIH-10773
* create a new action for create a Pexip participant
* Use effects to subscribe to create Pexip participant to create audio mixes when a participant is connected to a conference
* if the participant is an interpreter it will send the audio to the respective mixes
=> VIH-10773 create audio mixes when a participant is connected to a conference

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participants-panel/participants-panel-item/participants-panel-item.component.ts
VIH-10919
When a participant is in the waiting room and available, then show the status 'available' and not 'joining'. A joining message is displayed when they are being admitted
=> VIH-10919 update the tooltip text for a participant in the waiting room

VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForHostTests.cs, VideoWeb/VideoWeb.UnitTests/Controllers/ConferenceController/GetConferencesForStaffMemberTests.cs, VideoWeb/VideoWeb/Controllers/ConferencesController.cs
https://tools.hmcts.net/jira/browse/VIH-11037
Fixes a 400 error received when loading the hearing list page for a staff member or judge, when there are no hearings
Avoid calling video api to fetch the conferences, when there are no hearings
=> VIH-11037 Fix for 400 error when no hearings

VideoWeb/VideoWeb.EventHub/Handlers/LeaveEventHandler.cs, VideoWeb/VideoWeb.UnitTests/EventHandlers/LeaveEventHandlerTests.cs
VIH-11040 
This pull request introduces a new condition to handle participants who leave a conference because they have connected on another device.
Changes in event handling:
* [`VideoWeb/VideoWeb.EventHub/Handlers/LeaveEventHandler.cs`](diffhunk://#diff-446e63876be507cd5a344fd588b60fe84bff9a4e8f08b988bf92fc3e69d35dcdL20-R26): Added a check to detect if a participant has connected on another device and handle the `Leave` event accordingly.
=> VIH-11040 redirect users detected on a another device from the waiting room too

VideoWeb/VideoWeb/Controllers/VideoEventsController.cs, VideoWeb/VideoWeb/Extensions/ConfigureAuthSchemeExtensions.cs, VideoWeb/VideoWeb/Startup.cs
VIH-10931
This pull request includes various changes to the `VideoWeb` project, primarily focusing on updating authentication schemes and event tracking. The most important changes involve renaming telemetry events, adding a new configuration parameter for Vodafone, and modifying the authentication scheme setup to accommodate this new parameter.
* [`VideoWeb/VideoWeb/Controllers/VideoEventsController.cs`](diffhunk://#diff-02a9a86219f48af5035f671441b5aba9d51928ce23ad0ad79e43c1a35fd85a2aL44-R44): Renamed the telemetry event from "KinlyCallback" to "SupplierCallback".
* [`VideoWeb/VideoWeb/Extensions/ConfigureAuthSchemeExtensions.cs`](diffhunk://#diff-c0b96f0117c7188c9bc542a31a4d0e81c0b3dc5a2f08d41265f599e656f7147bL24-L31): Added a `vodafoneEnabled` parameter to the `RegisterAuthSchemes` …
=> VIH-10931 use the Vodafone feature flag to determine which callback secret to use

VideoWeb/VideoWeb/ClientApp/src/app/services/launch-darkly.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/launch-darkly.service.ts
https://tools.hmcts.net/jira/browse/VIH-11072
Fixes an issue where dom1 and other feature flags are being incorrectly determined as switched off
- Wait for the flags to load when retrieving a flag, to avoid prematurely evaluating it as unavailable and switched off
- Do this by emitting a value for the `flagsReadySubject` once the flags have been loaded
=> VIH-11072 Fix flag evaluation issue with launch darkly service

VideoWeb/VideoWeb/ClientApp/src/app/services/conference/heartbeat.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/conference/heartbeat.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/user-media-stream.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts
VIH-11050
* Added an `initialising` flag to prevent multiple initializations of the heartbeat service. (`VideoWeb/VideoWeb/ClientApp/src/app/services/conference/heartbeat.service.ts`)
* Introduced a `closeCurrentStream` method to stop all tracks of the current stream. (`VideoWeb/VideoWeb/ClientApp/src/app/services/user-media-stream.service.ts`)
* Updated the `disconnect` method to call the new `closeCurrentStream` method from `UserMediaStreamService`. (`VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts`)
=> VIH-11050 disconnect from camera and microphone when user leaves the waiting room

VideoWeb/VideoWeb/ClientApp/package-lock.json, VideoWeb/VideoWeb/ClientApp/package.json, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/switch-on-camera-microphone/switch-on-camera-microphone.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/on-the-day/switch-on-camera-microphone/switch-on-camera-microphone.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/no-sleep.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/no-sleep.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/user-media-stream-v2.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/user-media-stream-v2.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/user-media.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.html, VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/self-test/self-test.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/effects/video-call.effects.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/tests/waiting-room-base-setup.ts, azure-pipelines.sds.master-release.yml, azure-pipelines.sds.pr-release.yml
VIH-10946
simplify the device stream management and enable audio only toggle in the hearing room
=> VIH-10946 enable audio only toggle in the hearing room

VideoWeb/VideoWeb.Common/Models/Conference.cs, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.Contract/VideoWeb.Contract.csproj, VideoWeb/VideoWeb.UnitTests/Builders/ConferenceCacheModelBuilder.cs, VideoWeb/VideoWeb.UnitTests/Common/Models/GetNonScreenedParticipantsAndEndpointsTests.cs, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json
VIH-11084
This pull request includes several updates to the `VideoWeb` project, focusing on enhancing the functionality of the `GetNonScreenedParticipantsAndEndpoints` method, updating package dependencies, and adding unit tests.
* [`VideoWeb/VideoWeb.Common/Models/Conference.cs`](diffhunk://#diff-3433ff3d66a049500148fe6ca52abe84dd11ba56e74ec1c271e44a315aef1598R215-R220): Modified the `GetNonScreenedParticipantsAndEndpoints` method to return only host participants if no participants or endpoints have screening.
* Update API Clients
=> VIH-11084 if there is no screening then only judges and SMs are hosts

VideoWeb/VideoWeb.Common/Models/Conference.cs, VideoWeb/VideoWeb.UnitTests/Models/Conference/AreEntitiesScreenedFromEachOtherTests.cs, VideoWeb/VideoWeb.UnitTests/Models/Conference/CanParticipantJoinConsultationRoomTests.cs, VideoWeb/VideoWeb/ClientApp/src/app/services/user-media.service.ts
VIH-11125
Improvements to participant screening:
* [`VideoWeb/VideoWeb.Common/Models/Conference.cs`](diffhunk://#diff-3433ff3d66a049500148fe6ca52abe84dd11ba56e74ec1c271e44a315aef1598L171-R201): Modified the `AreEntitiesScreenedFromEachOther` method to exclude certain participant roles from screening and added a helper method `SupportsScreening` to encapsulate this logic.
=> VIH-11125 bugfix QL unable to start a consultation

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/effects/conference.effects.ts
VIH-11130
* **Bug fix**: initialise call tag on setup client rather than before each call
* This will effectively give a participant the same call tag per session (i.e until they refresh the browser)
This change will need a bit of rigorous testing to avoid any uncertain side effects but should make connection less complex for the new supplier
=> VIH-11130 bug fix initialise call tag on setup client rather than before each call

VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json
VIH-11123
This pull request includes a minor update to the `en.json` file to correct a typographical error.
* [`VideoWeb/VideoWeb/ClientApp/src/assets/i18n/en.json`](diffhunk://#diff-06ccab0b90df1765c8177815fedd9949b3ced4b1a38af1a26b9aaba47d134a77L518-R518): Removed an unnecessary non-breaking space (`&thinsp;`) from the "hearing-ready" message.
=> VIH-11123 Fix typo in hearing readiness message in English localization

VideoWeb/VideoWeb/ClientApp/package-lock.json, VideoWeb/VideoWeb/ClientApp/package.json, VideoWeb/VideoWeb/ClientApp/src/app/services/user-media-stream-v2.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/user-media.service.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/shared/select-media-devices/select-media-devices.component.ts
VIH-11134
This pull request includes several updates to improve the handling of media devices and streams in the `VideoWeb` application. The changes include adding null checks, restructuring the return values, and sorting devices to prioritize defaults.
* [`VideoWeb/VideoWeb/ClientApp/src/app/services/user-media-stream-v2.service.ts`](diffhunk://#diff-d1c13d4b18580c21d3396394840f016430e319f6b81231036e79752bb26e911cL116-R116): Added null checks to ensure that audio and video tracks are safely accessed when combining streams.
* [`VideoWeb/VideoWeb/ClientApp/src/app/services/user-media.service.ts`](diffhunk://#diff-bb96c235363777c66ead262d9d70746c73e389898627b8c365e18d47492aae20L91-R110): Modified the device filtering logic to return an object containing default group IDs and devices, and …
=> VIH-11134 bugfix additional handling of null streams

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/reducers/conference.reducer.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/reducers/conference.reducer.ts
VIH-11151
If a conference is refreshed, the redux store loses the original media device status for partcipants and pexip info for endpoints
=> VIH-11151 retain local media status and retain pexip info for conference endpoints when conference is refreshed

VideoWeb/VideoWeb.Common/Models/EndpointStatus.cs, VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.Contract/VideoWeb.Contract.csproj, VideoWeb/VideoWeb.EventHub/Enums/EndpointState.cs, VideoWeb/VideoWeb.EventHub/Handlers/EndpointTransferEventHandler.cs, VideoWeb/VideoWeb.EventHub/VideoWeb.EventHub.csproj, VideoWeb/VideoWeb.UnitTests/EventHandlers/EndpointTransferEventHandlerTests.cs, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/ClientApp/src/app/services/clients/api-client.ts, VideoWeb/VideoWeb/ClientApp/src/app/testing/mocks/data/conference-test-data.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/models/video-endpoint-panel-model.ts, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json
VIH-11189
* Added `InHearing` status to `EndpointStatus` in `VideoWeb/VideoWeb.Common/Models/EndpointStatus.cs`.
* Added `InHearing` state to `EndpointState` in `VideoWeb/VideoWeb.EventHub/Enums/EndpointState.cs`.
* Updated `DeriveEndpointState` method to handle `InHearing` state and status in `VideoWeb/VideoWeb.EventHub/Handlers/EndpointTransferEventHandler.cs`.
* Changed project SDK from `Microsoft.NET.Sdk` to `Microsoft.NET.Sdk.Web` in `VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj` and `VideoWeb/VideoWeb.EventHub/VideoWeb.EventHub.csproj`. SignalR is now a part of the framework and the nuget packages are obsolete and vulnerable
=> VIH-11189 add InHearing value to endpoint status enum

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/joh-waiting-room/joh-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.html, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.html
VIH-11222
remove host wants to join
=> VIH-11222 remove host wants to join

VideoWeb/VideoWeb/ClientApp/src/app/services/models/consultation-rules.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/services/models/consultation-rules.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/private-consultation-participants/private-consultation-participants.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/waiting-room-shared/wr-participant-list-shared.component.ts
https://tools.hmcts.net/jira/browse/VIH-11132
For private consultations, hide the call/invite button when participants are screened
- When the current user is screened from the target participant, or vice versa
- When one of the screening participant pair is already in the consultation
Updates the `participantHasInviteRestrictions` logic, and refactors it into a separate class (ConsultationRules) along with the tests
=> VIH-11132 Hide invite button for screened participants

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/judge-waiting-room/judge-waiting-room.component.ts
Changed the reconnectWowzaAgent function to an arrow function, as it loses 'this' context, and is treating audioRecordingService as undefined when being called as a callback from the toaster. Should now inherit 'this' from its lexical scope meaning it wont jump over these functions.
=> VIH-0000 Changed the reconnectWowzaAgent function to an arrow function

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/reducers/conference.reducer.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/reducers/conference.reducer.ts
VIH-11245
The participant would display notifications for conference they are booked to but is not their active one. Ignore updates if the ids to not match. To replace the hearing, dispatch the leaveConference action first
=> VIH-11245 ignore conference updates that do not match the active conference

VideoWeb/VideoWeb.Common/VideoWeb.Common.csproj, VideoWeb/VideoWeb.UnitTests/Extensions/ConferenceEventRequestExtensionsTests.cs, VideoWeb/VideoWeb.UnitTests/VideoWeb.UnitTests.csproj, VideoWeb/VideoWeb.UnitTests/packages.lock.json, VideoWeb/VideoWeb/Controllers/VideoEventsController.cs, VideoWeb/VideoWeb/Extensions/ConferenceEventRequestExtensions.cs, VideoWeb/VideoWeb/VideoWeb.csproj, VideoWeb/VideoWeb/packages.lock.json
VIH-11273
Assign the conference role when an event comes in. Used by the supplier on transfer
=> VIH-11273 Assign the conference role when an event comes in

VideoWeb/VideoWeb.EventHub/Handlers/JoinedEventHandler.cs, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/hearing-controls/hearing-controls-base.component.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/effects/conference.effects.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/effects/notification.effects.ts
VIH-11274
apply host microphone preferences after joining a hearing in session
this currently relies on the countdown complete event but late joiners will miss this event if a countdown has completed
=> VIH-11274 apply host microphone preferences after joining a hearing in session

VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts, VideoWeb/VideoWeb/ClientApp/src/typings.d.ts
VIH-10695
update pexip client in line with audio only toggle.
Currently the image for audio only is a custom one out of the box. If a user were to mute their video Pexip provides a slightly different UX for participants. The audio only toggle handling should give the same experience.
Before:
After:
=> VIH-10695 update pexip client in line with audio only toggle

VideoWeb/VideoWeb/ClientApp/src/app/app.module.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/effects/notification.effects.spec.ts, VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/store/effects/notification.effects.ts
VIH-11404
Due to endpoints being published despite no change to the service bus to update their role with the supplier, the UI needs to handle whether or not to display the toast notifcation. Simiilar to participants added
=> VIH-11404 Refactor NotificationEffects to track previous endpoints and improve notification logic on endpoint updates
